import type {
  ControlItem,
  CrimeFraudStats,
  KnowledgeItem,
  KnowledgeRelation,
  MatrixLayerId,
  Person,
  ProcessNode,
  ScenarioTemplate,
  StaffComposition,
} from "./types";

export const PRACTICE_NAME = "Ridgeview Family Dental";

export const LAYER_META: Record<
  MatrixLayerId,
  { name: string; matrixName: string; blurb: string }
> = {
  surface: {
    name: "Surface Reality",
    matrixName: "The Construct",
    blurb: "Patients, chairs, schedule pressure, cash in drawer.",
  },
  process: {
    name: "Process Layer",
    matrixName: "Workflow Code",
    blurb: "Documented workflows, value streams, SOPs, Lean maps.",
  },
  knowledge: {
    name: "Knowledge / Tribal",
    matrixName: "Hidden Matrix",
    blurb: "Who actually knows how things work — SPOFs and succession risk.",
  },
  control: {
    name: "Control & Governance",
    matrixName: "Ruleset",
    blurb: "Internal controls, segregation of duties, residual risk.",
  },
  source: {
    name: "Source / Architecture",
    matrixName: "Infrastructure",
    blurb: "PMS, claims systems, vendors, data flows.",
  },
  continuity: {
    name: "Continuity / Exit",
    matrixName: "Red Pill",
    blurb: "What breaks when key people or systems disappear.",
  },
};

export const people: Person[] = [
  { id: "p1", name: "Dr. Elena Vargas", role: "Owner / Dentist", active: true, tenureYears: 12 },
  { id: "p2", name: "Maya Chen", role: "Office Manager", active: true, tenureYears: 7 },
  { id: "p3", name: "Jordan Blake", role: "Front Desk Lead", active: true, tenureYears: 5 },
  { id: "p4", name: "Sam Ortiz", role: "Hygienist", active: true, tenureYears: 4 },
  { id: "p5", name: "Riley Kim", role: "Dental Assistant", active: true, tenureYears: 2 },
  { id: "p6", name: "Chris Patel", role: "Billing Specialist", active: true, tenureYears: 3 },
];

export const knowledge: KnowledgeItem[] = [
  {
    id: "k1",
    name: "Insurance denial appeals",
    description: "Full denial workflow, payer quirks, appeal letter patterns.",
    criticality: "critical",
    category: "process",
    linkedProcessIds: ["proc-claims"],
  },
  {
    id: "k2",
    name: "Daily deposit & reconciliation",
    description: "Cash drawer, EFT matching, PMS vs bank deposit process.",
    criticality: "critical",
    category: "process",
    linkedProcessIds: ["proc-cash"],
  },
  {
    id: "k3",
    name: "PMS admin configuration",
    description: "User roles, fee schedules, claim templates, report setup.",
    criticality: "critical",
    category: "system",
    linkedProcessIds: ["proc-claims", "proc-schedule"],
  },
  {
    id: "k4",
    name: "Vendor invoice approval",
    description: "Lab bills, supply orders, approval thresholds.",
    criticality: "important",
    category: "vendor",
    linkedProcessIds: ["proc-ap"],
  },
  {
    id: "k5",
    name: "Sterilization protocol",
    description: "Instrument flow, spore testing, documentation.",
    criticality: "critical",
    category: "clinical",
    linkedProcessIds: ["proc-clinical"],
  },
  {
    id: "k6",
    name: "Payroll exception handling",
    description: "OT, bonuses, PTO edge cases in payroll export.",
    criticality: "important",
    category: "process",
    linkedProcessIds: ["proc-payroll"],
  },
  {
    id: "k7",
    name: "Write-off & adjustment authority",
    description: "Who may adjust balances and how they are documented.",
    criticality: "critical",
    category: "compliance",
    linkedProcessIds: ["proc-ar"],
  },
];

export const relations: KnowledgeRelation[] = [
  { personId: "p3", knowledgeId: "k1", level: "expert" },
  { personId: "p3", knowledgeId: "k2", level: "expert" },
  { personId: "p6", knowledgeId: "k1", level: "basic" },
  { personId: "p2", knowledgeId: "k2", level: "proficient" },
  { personId: "p2", knowledgeId: "k3", level: "expert" },
  { personId: "p6", knowledgeId: "k3", level: "basic" },
  { personId: "p2", knowledgeId: "k4", level: "expert" },
  { personId: "p1", knowledgeId: "k4", level: "aware" },
  { personId: "p4", knowledgeId: "k5", level: "expert" },
  { personId: "p5", knowledgeId: "k5", level: "proficient" },
  { personId: "p2", knowledgeId: "k6", level: "expert" },
  { personId: "p6", knowledgeId: "k7", level: "expert" },
  { personId: "p2", knowledgeId: "k7", level: "proficient" },
];

export const processes: ProcessNode[] = [
  {
    id: "proc-schedule",
    name: "Scheduling & chair utilization",
    layer: "process",
    description: "Booking, confirmations, same-day openings.",
    dependencies: [],
    controlIds: ["c-schedule"],
    stage: 0,
    ownerPersonIds: ["p3", "p2"],
    inputs: ["Patient demand", "Provider templates"],
    outputs: ["Confirmed chair schedule"],
    risks: [
      {
        id: "r-sched-1",
        title: "No-show cascade",
        kind: "revenue",
        severity: 3,
        likelihood: 4,
        note: "Gaps open late; hygiene production drops without recovery protocol.",
      },
      {
        id: "r-sched-2",
        title: "PMS template SPOF",
        kind: "continuity",
        severity: 4,
        likelihood: 2,
        note: "Only office manager can rebuild templates after staff change.",
        linkedKnowledgeId: "k3",
      },
    ],
    ideas: [
      {
        id: "i-sched-1",
        title: "Same-day fill list automation",
        category: "tech",
        effort: "medium",
        impact: "high",
        note: "Text waitlist when cancellation hits > 90 minutes out.",
        status: "exploring",
      },
      {
        id: "i-sched-2",
        title: "Document template rebuild SOP",
        category: "training",
        effort: "low",
        impact: "medium",
        note: "Screen-record PMS admin steps for billing backup.",
        status: "planned",
      },
    ],
    wastes: [
      {
        id: "w-sched-1",
        kind: "muda_waiting",
        label: "Chair idle after late cancel",
        note: "Average 40 min unrecovered hygiene slots/week.",
      },
    ],
  },
  {
    id: "proc-clinical",
    name: "Clinical delivery",
    layer: "process",
    description: "Hygiene and restorative chairside flow.",
    dependencies: ["proc-schedule"],
    controlIds: ["c-clinical"],
    stage: 1,
    ownerPersonIds: ["p1", "p4"],
    inputs: ["Schedule", "Sterile instruments", "Chart history"],
    outputs: ["Completed procedures", "Clinical notes"],
    risks: [
      {
        id: "r-clin-1",
        title: "Incomplete same-day notes",
        kind: "compliance",
        severity: 3,
        likelihood: 3,
        note: "Claims delayed when notes lag; audit exposure.",
      },
    ],
    ideas: [
      {
        id: "i-clin-1",
        title: "Note close checklist at checkout",
        category: "policy",
        effort: "low",
        impact: "medium",
        note: "Block next appointment book until note status green.",
        status: "backlog",
      },
    ],
    wastes: [
      {
        id: "w-clin-1",
        kind: "muda_motion",
        label: "Instrument hunt mid-procedure",
        note: "Tray setup variance between assistants.",
      },
    ],
  },
  {
    id: "proc-claims",
    name: "Claims & denials",
    layer: "process",
    description: "Submit, track, appeal insurance claims.",
    dependencies: ["proc-clinical"],
    controlIds: ["c-claims", "c-sod-billing"],
    stage: 2,
    ownerPersonIds: ["p6", "p3"],
    inputs: ["Clinical notes", "Fee schedule", "Eligibility"],
    outputs: ["Paid claims", "Denial queue"],
    risks: [
      {
        id: "r-claims-1",
        title: "Sole denial expert leaves",
        kind: "continuity",
        severity: 5,
        likelihood: 3,
        note: "Jordan sole expert on appeals — revenue lag multiplies.",
        linkedKnowledgeId: "k1",
        linkedScenarioId: "sc-front-desk-leaves",
      },
      {
        id: "r-claims-2",
        title: "Billing posts write-offs alone",
        kind: "fraud",
        severity: 4,
        likelihood: 3,
        note: "SoD gap: claims + adjustments without dual control.",
        linkedControlId: "c-sod-billing",
        linkedScenarioId: "sc-writeoff-abuse",
      },
    ],
    ideas: [
      {
        id: "i-claims-1",
        title: "Cross-train Chris on appeals",
        category: "training",
        effort: "medium",
        impact: "high",
        note: "Shadow 10 denials; document payer quirks wiki.",
        status: "planned",
      },
      {
        id: "i-claims-2",
        title: "Owner approval > $150 write-off",
        category: "control",
        effort: "low",
        impact: "high",
        note: "PMS threshold + weekly exception report.",
        status: "exploring",
      },
    ],
    wastes: [
      {
        id: "w-claims-1",
        kind: "muda_rework",
        label: "Denial rework loops",
        note: "Re-submit without root-cause codes wastes 6+ hrs/week.",
      },
      {
        id: "w-claims-2",
        kind: "mura",
        label: "Uneven denial ownership",
        note: "One person batch-dumps; others idle.",
      },
    ],
  },
  {
    id: "proc-cash",
    name: "Cash handling & deposits",
    layer: "process",
    description: "Patient payments, drawer, bank deposit.",
    dependencies: [],
    controlIds: ["c-cash", "c-sod-cash"],
    stage: 2,
    ownerPersonIds: ["p3"],
    inputs: ["Patient payments", "Drawer float"],
    outputs: ["Bank deposit", "PMS payment posts"],
    risks: [
      {
        id: "r-cash-1",
        title: "Posting + recon not segregated",
        kind: "fraud",
        severity: 5,
        likelihood: 4,
        note: "Classic embezzlement opportunity path.",
        linkedControlId: "c-sod-cash",
        linkedScenarioId: "sc-cash-sod-failure",
      },
      {
        id: "r-cash-2",
        title: "Deposit knowledge SPOF",
        kind: "continuity",
        severity: 4,
        likelihood: 3,
        note: "Jordan expert on daily deposit & recon.",
        linkedKnowledgeId: "k2",
      },
    ],
    ideas: [
      {
        id: "i-cash-1",
        title: "Owner independent bank rec weekly",
        category: "control",
        effort: "low",
        impact: "high",
        note: "Highest ROI detection control for small practices.",
        status: "planned",
      },
      {
        id: "i-cash-2",
        title: "Dual count + camera on drawer close",
        category: "control",
        effort: "medium",
        impact: "medium",
        note: "May unlock insurance premium credit.",
        status: "backlog",
      },
    ],
    wastes: [
      {
        id: "w-cash-1",
        kind: "muda_overprocessing",
        label: "Triple entry of payments",
        note: "PMS, spreadsheet, and sticky notes for same payment.",
      },
    ],
  },
  {
    id: "proc-ar",
    name: "A/R & adjustments",
    layer: "process",
    description: "Patient balances, write-offs, collections.",
    dependencies: ["proc-claims"],
    controlIds: ["c-ar", "c-sod-ar"],
    stage: 3,
    ownerPersonIds: ["p6", "p2"],
    inputs: ["Open claims", "Patient balances"],
    outputs: ["Collections", "Adjustments"],
    risks: [
      {
        id: "r-ar-1",
        title: "Undocumented write-offs",
        kind: "fraud",
        severity: 4,
        likelihood: 3,
        note: "Adjustments without reason codes hide leakage.",
        linkedKnowledgeId: "k7",
        linkedScenarioId: "sc-writeoff-abuse",
      },
    ],
    ideas: [
      {
        id: "i-ar-1",
        title: "Monthly adjustment aging report",
        category: "control",
        effort: "low",
        impact: "high",
        note: "Owner signs exception report.",
        status: "planned",
      },
      {
        id: "i-ar-2",
        title: "Reason-code required in PMS",
        category: "tech",
        effort: "low",
        impact: "medium",
        note: "Block save without code + note.",
        status: "exploring",
      },
    ],
    wastes: [
      {
        id: "w-ar-1",
        kind: "muda_waiting",
        label: "Balances age past 90 days",
        note: "No cadence on patient payment plans.",
      },
    ],
  },
  {
    id: "proc-ap",
    name: "Accounts payable",
    layer: "process",
    description: "Vendor invoices, labs, supplies.",
    dependencies: [],
    controlIds: ["c-ap", "c-sod-ap"],
    stage: 3,
    ownerPersonIds: ["p2"],
    inputs: ["Vendor invoices", "Lab slips"],
    outputs: ["Paid vendors"],
    risks: [
      {
        id: "r-ap-1",
        title: "Vendor setup + payment same person",
        kind: "fraud",
        severity: 5,
        likelihood: 3,
        note: "Fictitious vendor path without dual release.",
        linkedControlId: "c-sod-ap",
        linkedScenarioId: "sc-vendor-fraud",
      },
    ],
    ideas: [
      {
        id: "i-ap-1",
        title: "Dual ACH release > $500",
        category: "control",
        effort: "medium",
        impact: "high",
        note: "Bank dual approval; owner is second signer.",
        status: "planned",
      },
      {
        id: "i-ap-2",
        title: "New-vendor monthly review",
        category: "policy",
        effort: "low",
        impact: "medium",
        note: "Print vendor master changes; owner initials.",
        status: "backlog",
      },
    ],
    wastes: [
      {
        id: "w-ap-1",
        kind: "muri",
        label: "OM owns all AP alone",
        note: "Overburden + no backup when Maya is out.",
      },
    ],
  },
  {
    id: "proc-payroll",
    name: "Payroll",
    layer: "process",
    description: "Time, exceptions, payroll export.",
    dependencies: [],
    controlIds: ["c-payroll"],
    stage: 4,
    ownerPersonIds: ["p2", "p1"],
    inputs: ["Time punches", "OT exceptions"],
    outputs: ["Payroll file", "Pay stubs"],
    risks: [
      {
        id: "r-pay-1",
        title: "Exception handling tribal only",
        kind: "continuity",
        severity: 3,
        likelihood: 3,
        note: "Maya sole expert on OT/bonus edge cases.",
        linkedKnowledgeId: "k6",
      },
    ],
    ideas: [
      {
        id: "i-pay-1",
        title: "Exception playbook one-pager",
        category: "training",
        effort: "low",
        impact: "medium",
        note: "Owner can run one cycle without Maya.",
        status: "exploring",
      },
    ],
    wastes: [
      {
        id: "w-pay-1",
        kind: "muda_rework",
        label: "Manual OT recalculation",
        note: "Spreadsheet after export every pay period.",
      },
    ],
  },
];

export const controls: ControlItem[] = [
  {
    id: "c-cash",
    name: "Cash handling control",
    description: "Separate custody of cash from deposit reconciliation.",
    duties: ["custody", "recording", "reconciliation"],
    segregated: false,
    compensatingControls: ["Owner reviews bank statements monthly"],
    residualRiskAccepted: false,
  },
  {
    id: "c-sod-cash",
    name: "SoD: payments vs reconciliation",
    description: "Same person posts payments and reconciles bank.",
    duties: ["recording", "reconciliation"],
    segregated: false,
    compensatingControls: ["Office manager spot-checks deposits weekly"],
    residualRiskAccepted: true,
  },
  {
    id: "c-sod-billing",
    name: "SoD: claims adjustments",
    description: "Billing can submit claims and post write-offs.",
    duties: ["authorization", "recording"],
    segregated: false,
    compensatingControls: ["Monthly adjustment report to owner"],
    residualRiskAccepted: false,
  },
  {
    id: "c-sod-ap",
    name: "SoD: vendor setup vs payment",
    description: "AP can create vendors and release payments.",
    duties: ["authorization", "custody"],
    segregated: false,
    compensatingControls: ["Dual release on payments > $1,000"],
    residualRiskAccepted: false,
  },
  {
    id: "c-sod-ar",
    name: "SoD: A/R write-offs",
    description: "Write-off authority without independent approval.",
    duties: ["authorization", "recording"],
    segregated: true,
    compensatingControls: [],
    residualRiskAccepted: false,
  },
  {
    id: "c-claims",
    name: "Denial aging review",
    description: "Weekly review of open denials > 30 days.",
    duties: ["review"],
    segregated: true,
    compensatingControls: [],
    residualRiskAccepted: false,
  },
  {
    id: "c-ap",
    name: "Invoice matching",
    description: "Match packing slip to invoice before payment.",
    duties: ["review", "authorization"],
    segregated: true,
    compensatingControls: [],
    residualRiskAccepted: false,
  },
  {
    id: "c-ar",
    name: "A/R aging review",
    description: "Owner reviews 90+ aging monthly.",
    duties: ["review"],
    segregated: true,
    compensatingControls: [],
    residualRiskAccepted: false,
  },
  {
    id: "c-payroll",
    name: "Payroll approval",
    description: "Owner approves payroll before transmission.",
    duties: ["authorization"],
    segregated: true,
    compensatingControls: [],
    residualRiskAccepted: false,
  },
  {
    id: "c-schedule",
    name: "Schedule change audit",
    description: "Daily confirmation of schedule changes.",
    duties: ["review"],
    segregated: true,
    compensatingControls: [],
    residualRiskAccepted: false,
  },
  {
    id: "c-clinical",
    name: "Clinical documentation check",
    description: "Charts closed same day with required elements.",
    duties: ["review"],
    segregated: true,
    compensatingControls: [],
    residualRiskAccepted: false,
  },
];

export const staffComposition: StaffComposition = {
  teamSize: 6,
  soleOwnerKnowledgeCount: 2,
  avgTenureYears: 5.5,
  segregationScore: 42,
  dualControlPayments: false,
  independentBankRec: false,
};

/** Industry-oriented illustrative base rates for demo (educational, not actuarial advice). */
export const crimeFraudStats: CrimeFraudStats = {
  industryEmbezzlementRate: 0.18,
  typicalLossMid: 35000,
  typicalLossHigh: 125000,
  medianDetectionDays: 90,
  detectionDaysP95: 210,
  source:
    "Illustrative synthesis of small professional practice fraud / embezzlement studies (e.g. ACFE Report to the Nations patterns for small orgs; dental practice management fraud case literature). Educational demo rates — not firm-specific actuarial pricing.",
};

export const scenarios: ScenarioTemplate[] = [
  {
    id: "sc-front-desk-leaves",
    title: "Front desk lead leaves with sole denial knowledge",
    description:
      "Jordan (sole expert on insurance denial appeals) resigns with 2 weeks notice. No cross-training documented.",
    knowledgeId: "k1",
    controlId: "c-claims",
    baseTimelineDays: { p50: 45, p95Low: 28, p95High: 75 },
    baseFinancialImpact: { expected: 18500, low: 8000, high: 42000 },
    statSources: [
      "Denial aging / revenue cycle lag patterns in dental practice management literature",
      "Key-person risk: revenue leakage when sole expert exits mid-cycle",
    ],
    cascadeLayers: ["knowledge", "process", "surface", "continuity"],
    mitigations: [
      {
        id: "m1",
        label: "Cross-train billing on denial appeals (documented SOP)",
        effort: "medium",
        riskReduction: 0.55,
        costAnnual: 2400,
      },
      {
        id: "m2",
        label: "Hire temporary RCM support for 90 days",
        effort: "high",
        riskReduction: 0.65,
        costAnnual: 12000,
      },
      {
        id: "m3",
        label: "Record Jordan's denial playbook before exit",
        effort: "low",
        riskReduction: 0.35,
        costAnnual: 400,
      },
    ],
  },
  {
    id: "sc-cash-sod-failure",
    title: "Unsegregated cash + reconciliation control fails",
    description:
      "Same person posts payments and reconciles bank with weak independent review. Opportunity + weak SoD elevates fraud and error risk.",
    controlId: "c-sod-cash",
    baseTimelineDays: { p50: 90, p95Low: 45, p95High: 210 },
    baseFinancialImpact: { expected: 28000, low: 5000, high: 95000 },
    statSources: [
      crimeFraudStats.source,
      "ACFE-style small organization fraud: longer detection when custody + recording combined",
    ],
    cascadeLayers: ["control", "process", "surface", "continuity"],
    mitigations: [
      {
        id: "m4",
        label: "Independent bank recon by owner weekly",
        effort: "low",
        riskReduction: 0.5,
        costAnnual: 0,
      },
      {
        id: "m5",
        label: "Split posting vs deposit custody",
        effort: "medium",
        riskReduction: 0.7,
        costAnnual: 0,
      },
      {
        id: "m6",
        label: "Camera + dual count on cash drawer close",
        effort: "medium",
        riskReduction: 0.4,
        costAnnual: 800,
      },
    ],
  },
  {
    id: "sc-writeoff-abuse",
    title: "Write-off authority without dual control",
    description:
      "Billing can post large adjustments without independent approval. Control gap + staff composition raises residual risk.",
    controlId: "c-sod-billing",
    knowledgeId: "k7",
    baseTimelineDays: { p50: 120, p95Low: 60, p95High: 240 },
    baseFinancialImpact: { expected: 22000, low: 4000, high: 70000 },
    statSources: [
      crimeFraudStats.source,
      "Revenue leakage studies: undocumented adjustments and weak dual control",
    ],
    cascadeLayers: ["control", "knowledge", "process", "continuity"],
    mitigations: [
      {
        id: "m7",
        label: "Require owner approval for write-offs > $150",
        effort: "low",
        riskReduction: 0.6,
        costAnnual: 0,
      },
      {
        id: "m8",
        label: "Monthly adjustment exception report",
        effort: "low",
        riskReduction: 0.45,
        costAnnual: 0,
      },
    ],
  },
  {
    id: "sc-vendor-fraud",
    title: "Vendor setup + payment not segregated",
    description:
      "AP can create vendors and release payments. Classic fraud path when dual release is missing.",
    controlId: "c-sod-ap",
    baseTimelineDays: { p50: 100, p95Low: 50, p95High: 200 },
    baseFinancialImpact: { expected: 40000, low: 8000, high: 125000 },
    statSources: [
      crimeFraudStats.source,
      "Billing schemes / fictitious vendor patterns in small entity fraud literature",
    ],
    cascadeLayers: ["control", "source", "process", "continuity"],
    mitigations: [
      {
        id: "m9",
        label: "Dual bank release on all ACH > $500",
        effort: "medium",
        riskReduction: 0.75,
        costAnnual: 0,
      },
      {
        id: "m10",
        label: "Independent new-vendor review monthly",
        effort: "low",
        riskReduction: 0.5,
        costAnnual: 0,
      },
    ],
  },
];
