import type { ControlItem, ScenarioTemplate } from "../types";
import type { IndustryTemplate } from "./types";
import {
  baseFinancialControls,
  baseFraudScenarios,
  DEFAULT_FRAUD_STATS,
  DEFAULT_STAFF,
} from "./shared-controls";

/**
 * A general contractor or specialty trade of 5 to 40 people: office staff, a
 * project manager and superintendent running the jobs, and field crews.
 *
 * The controls and scenarios below follow schemes documented in contractor
 * prosecutions and in the ACFE's occupational-fraud taxonomy: payments to a
 * subcontractor or supplier that does not exist, change orders inflated for a
 * kickback, materials ordered to a job and taken elsewhere, and field hours
 * padded or paid to people who never worked. The case library holds
 * construction and trades cases for each (see evidence/cases.ts).
 */
const constructionControls: ControlItem[] = [
  {
    id: "c-change-orders",
    name: "Change-order approval",
    description:
      "Every change order is priced against the contract and approved in writing, before the work or the payment, by someone other than the project manager who negotiated it.",
    duties: ["authorization", "review"],
    segregated: false,
    compensatingControls: ["Owner reads the change-order log against each job budget monthly"],
    residualRiskAccepted: false,
  },
  {
    id: "c-sub-verify",
    name: "New subcontractor and supplier check",
    description:
      "Before a first payment, someone who does not pay bills confirms the company's license, insurance certificate, W-9 and address against public records.",
    duties: ["authorization", "review"],
    segregated: false,
    compensatingControls: ["Owner reads the list of new vendors each month"],
    residualRiskAccepted: false,
  },
  {
    id: "c-lien-waivers",
    name: "Lien waivers with every payment",
    description:
      "No subcontractor or supplier payment is released without a conditional waiver for this payment and an unconditional waiver for the last one.",
    duties: ["review"],
    segregated: true,
    compensatingControls: [],
    residualRiskAccepted: false,
  },
  {
    id: "c-field-time",
    name: "Field time approval",
    description:
      "Crew hours are paid only when the superintendent has approved them against the daily reports and the crew roster for that job.",
    duties: ["authorization", "review"],
    segregated: false,
    compensatingControls: ["Owner compares the people paid with the people on the job sites"],
    residualRiskAccepted: false,
  },
  {
    id: "c-materials",
    name: "Materials receiving and job cost review",
    description:
      "Deliveries are signed for at the job by someone other than the person who ordered them, and the project manager compares material cost by job with the estimate.",
    duties: ["custody", "review"],
    segregated: false,
    compensatingControls: ["Monthly job cost report read by the owner"],
    residualRiskAccepted: false,
  },
];

/*
 * The scenario timelines and loss figures are the same illustrative model
 * inputs the shared scenarios use for the closest scheme (vendor fraud for
 * billing schemes, the cash scenario for payroll, the write-off scenario for
 * non-cash theft). They are assumptions for the model, not measurements.
 */
const constructionScenarios: ScenarioTemplate[] = [
  {
    id: "sc-fictitious-sub",
    title: "Payments to a subcontractor that does not exist",
    description:
      "Someone who sets up vendors and releases payments adds a subcontractor with a real-sounding name and a bank account they control, then codes its invoices to a busy job where the extra cost reads as an overrun.",
    controlId: "c-sub-verify",
    baseTimelineDays: { p50: 100, p95Low: 50, p95High: 200 },
    baseFinancialImpact: { expected: 40000, low: 8000, high: 125000 },
    cascadeLayers: ["control", "source", "process", "continuity"],
    mitigations: [
      {
        id: "m-con-1",
        label: "Someone who pays no bills checks license, insurance and W-9 before a first payment",
        effort: "low",
        riskReduction: 0.5,
        costAnnual: 0,
      },
      {
        id: "m-con-2",
        label: "Dual bank release on subcontractor payments above a set amount",
        effort: "medium",
        riskReduction: 0.75,
        costAnnual: 0,
      },
    ],
  },
  {
    id: "sc-change-order-kickback",
    title: "Change orders inflated for a kickback",
    description:
      "The person who negotiates change orders with a subcontractor also approves the subcontractor's pay applications. The subcontractor bills more than the extra work is worth and returns part of it to that person.",
    controlId: "c-change-orders",
    knowledgeId: "k2",
    baseTimelineDays: { p50: 100, p95Low: 50, p95High: 200 },
    baseFinancialImpact: { expected: 40000, low: 8000, high: 125000 },
    cascadeLayers: ["control", "process", "surface", "continuity"],
    mitigations: [
      {
        id: "m-con-3",
        label: "Owner approves change orders above a set amount before work starts",
        effort: "low",
        riskReduction: 0.6,
        costAnnual: 0,
      },
      {
        id: "m-con-4",
        label: "Competing quotes for extra work above a set amount",
        effort: "medium",
        riskReduction: 0.45,
        costAnnual: 0,
      },
    ],
  },
  {
    id: "sc-material-theft",
    title: "Materials ordered to a job and taken elsewhere",
    description:
      "The person who orders materials also signs for them. Lumber, wire, fixtures or equipment are charged to an open job and delivered to a side job or resold, and the cost reads as job cost.",
    controlId: "c-materials",
    baseTimelineDays: { p50: 120, p95Low: 60, p95High: 240 },
    baseFinancialImpact: { expected: 22000, low: 4000, high: 70000 },
    cascadeLayers: ["control", "process", "surface", "continuity"],
    mitigations: [
      {
        id: "m-con-5",
        label: "Someone other than the buyer signs for deliveries at the job",
        effort: "low",
        riskReduction: 0.5,
        costAnnual: 0,
      },
      {
        id: "m-con-6",
        label: "Monthly material cost by job compared with the estimate",
        effort: "low",
        riskReduction: 0.35,
        costAnnual: 0,
      },
    ],
  },
  {
    id: "sc-field-time-padding",
    title: "Padded field hours and crew members who never worked",
    description:
      "Timesheets from the field go to payroll without a check against the daily reports. Extra hours, or a former crew member left on payroll with a changed bank account, are paid with the rest of the run.",
    controlId: "c-field-time",
    knowledgeId: "k5",
    baseTimelineDays: { p50: 90, p95Low: 45, p95High: 210 },
    baseFinancialImpact: { expected: 28000, low: 5000, high: 95000 },
    cascadeLayers: ["control", "process", "surface", "continuity"],
    mitigations: [
      {
        id: "m-con-7",
        label: "Superintendent approves crew hours against daily reports before payroll",
        effort: "low",
        riskReduction: 0.5,
        costAnnual: 0,
      },
      {
        id: "m-con-8",
        label: "Owner reads new hires, rate changes and bank changes every payroll",
        effort: "low",
        riskReduction: 0.45,
        costAnnual: 0,
      },
    ],
  },
];

export const constructionTemplate: IndustryTemplate = {
  id: "construction",
  businessName: "Summit Ridge Builders",
  people: [
    { id: "p1", name: "Marcus Hale", role: "Owner / President", active: true, tenureYears: 18 },
    { id: "p2", name: "Dana Whitfield", role: "Office Manager", active: true, tenureYears: 11 },
    { id: "p3", name: "Luis Moreno", role: "Project Manager", active: true, tenureYears: 7 },
    { id: "p4", name: "Tanya Brooks", role: "Superintendent", active: true, tenureYears: 9 },
    { id: "p5", name: "Kevin Walsh", role: "Estimator", active: true, tenureYears: 5 },
    { id: "p6", name: "Ray Delgado", role: "Foreman", active: true, tenureYears: 6 },
    { id: "p7", name: "Priya Nair", role: "Project Accountant", active: true, tenureYears: 3 },
    { id: "p8", name: "Jamal Carter", role: "Payroll Administrator", active: true, tenureYears: 4 },
  ],
  knowledge: [
    {
      id: "k1",
      name: "Estimating unit costs & bid history",
      description: "Unit costs, labor productivity rates, and which subcontractor bids won before.",
      criticality: "critical",
      category: "process",
      linkedProcessIds: ["proc-estimating"],
    },
    {
      id: "k2",
      name: "Job cost codes & change-order log",
      description: "Cost code structure, committed costs, and every approved and pending change.",
      criticality: "critical",
      category: "process",
      linkedProcessIds: ["proc-jobcost"],
    },
    {
      id: "k3",
      name: "Pay applications & retainage",
      description:
        "Schedule of values, percent complete, retainage held by clients and held from subcontractors.",
      criticality: "critical",
      category: "process",
      linkedProcessIds: ["proc-claims", "proc-ar"],
    },
    {
      id: "k4",
      name: "Lien waivers & insurance certificates",
      description:
        "Conditional and unconditional waivers per payment, and which certificates expire when.",
      criticality: "critical",
      category: "compliance",
      linkedProcessIds: ["proc-ap"],
    },
    {
      id: "k5",
      name: "Certified payroll & prevailing wage",
      description:
        "Wage determinations, worker classifications, and weekly certified payroll reports on public jobs.",
      criticality: "critical",
      category: "compliance",
      linkedProcessIds: ["proc-payroll"],
    },
    {
      id: "k6",
      name: "Subcontractor & supplier relationships",
      description:
        "Who performs, who pays on time, credit terms, and who to call when a job slips.",
      criticality: "important",
      category: "vendor",
      linkedProcessIds: ["proc-ap", "proc-jobcost"],
    },
    {
      id: "k7",
      name: "Equipment & small tool tracking",
      description: "Which truck, machine or tool is on which job, fuel cards, and service dates.",
      criticality: "important",
      category: "process",
      linkedProcessIds: ["proc-materials"],
    },
  ],
  relations: [
    { personId: "p5", knowledgeId: "k1", level: "expert" },
    { personId: "p1", knowledgeId: "k1", level: "proficient" },
    { personId: "p3", knowledgeId: "k2", level: "expert" },
    { personId: "p7", knowledgeId: "k2", level: "proficient" },
    { personId: "p7", knowledgeId: "k3", level: "expert" },
    { personId: "p2", knowledgeId: "k3", level: "basic" },
    { personId: "p2", knowledgeId: "k4", level: "expert" },
    { personId: "p8", knowledgeId: "k5", level: "expert" },
    { personId: "p3", knowledgeId: "k6", level: "expert" },
    { personId: "p1", knowledgeId: "k6", level: "proficient" },
    { personId: "p4", knowledgeId: "k7", level: "proficient" },
    { personId: "p6", knowledgeId: "k7", level: "basic" },
  ],
  processes: [
    {
      id: "proc-estimating",
      name: "Estimating & bidding",
      layer: "process",
      description: "Takeoffs, subcontractor and supplier quotes, bid submission.",
      dependencies: [],
      controlIds: [],
      stage: 0,
      ownerPersonIds: ["p5", "p1"],
      inputs: ["Plans and specifications", "Subcontractor quotes", "Unit cost history"],
      outputs: ["Submitted bids", "Awarded contracts"],
      risks: [
        {
          id: "r-est-1",
          title: "Subcontractor quotes opened and levelled by one person",
          kind: "fraud",
          severity: 4,
          likelihood: 2,
          note: "Whoever sees every quote first can tell a favored subcontractor the number to beat.",
        },
        {
          id: "r-est-2",
          title: "Unit costs live in one estimator's spreadsheet",
          kind: "continuity",
          severity: 4,
          likelihood: 3,
          note: "Bids stop, or go out underpriced, when the estimator is out during bid season.",
          linkedKnowledgeId: "k1",
        },
      ],
      ideas: [
        {
          id: "i-est-1",
          title: "Log every quote on receipt with its time and amount",
          category: "control",
          effort: "low",
          impact: "medium",
          note: "Quotes arrive at a shared inbox; the log is closed before anyone levels the bids.",
          status: "planned",
        },
        {
          id: "i-est-2",
          title: "Second person reviews bids above a set amount",
          category: "control",
          effort: "low",
          impact: "high",
          note: "The owner checks quantities, markup and the chosen subcontractors before submission.",
          status: "exploring",
        },
      ],
      wastes: [
        {
          id: "w-est-1",
          kind: "muda_overprocessing",
          label: "Takeoffs redone for every revision",
          note: "Plan revisions trigger a full recount because quantities are not kept by area.",
        },
      ],
    },
    {
      id: "proc-jobcost",
      name: "Job costing & change orders",
      layer: "process",
      description: "Budgets by cost code, committed costs, change orders, over/under billing.",
      dependencies: ["proc-estimating"],
      controlIds: ["c-change-orders"],
      stage: 1,
      ownerPersonIds: ["p3", "p7"],
      inputs: ["Awarded contract and budget", "Subcontract agreements", "Field change requests"],
      outputs: ["Job cost report", "Approved change orders", "Work-in-progress schedule"],
      risks: [
        {
          id: "r-job-1",
          title: "Project manager negotiates and approves change orders alone",
          kind: "fraud",
          severity: 5,
          likelihood: 3,
          note: "An inflated change order with a kickback behind it reads as ordinary extra work.",
          linkedControlId: "c-change-orders",
          linkedScenarioId: "sc-change-order-kickback",
          linkedKnowledgeId: "k2",
        },
        {
          id: "r-job-2",
          title: "Extra work done without a signed change order",
          kind: "revenue",
          severity: 4,
          likelihood: 4,
          note: "Field says yes to the client; the office never bills it, or bills it after the client disputes it.",
        },
      ],
      ideas: [
        {
          id: "i-job-1",
          title: "Owner signs change orders above a set amount",
          category: "control",
          effort: "low",
          impact: "high",
          note: "Pricing and the subcontractor's backup go to the owner before work starts.",
          status: "planned",
        },
        {
          id: "i-job-2",
          title: "Monthly work-in-progress review",
          category: "control",
          effort: "medium",
          impact: "high",
          note: "Cost to date, estimated cost to complete and billing by job, read by the owner and the project accountant together.",
          status: "exploring",
        },
      ],
      wastes: [
        {
          id: "w-job-1",
          kind: "muda_waiting",
          label: "Costs coded weeks after they are spent",
          note: "Receipts and invoices wait for the project manager to assign cost codes, so overruns show up late.",
        },
      ],
    },
    {
      id: "proc-materials",
      name: "Materials, equipment & small tools",
      layer: "process",
      description: "Purchase orders, deliveries to jobs, yard stock, equipment and fuel cards.",
      dependencies: ["proc-jobcost"],
      controlIds: ["c-materials"],
      stage: 1,
      ownerPersonIds: ["p4", "p6"],
      inputs: ["Material takeoffs", "Purchase orders", "Delivery tickets"],
      outputs: ["Materials on site", "Equipment and tool log"],
      risks: [
        {
          id: "r-mat-1",
          title: "Same person orders and signs for materials",
          kind: "fraud",
          severity: 4,
          likelihood: 3,
          note: "Material charged to one job can be delivered to a side job or resold with no one else seeing the ticket.",
          linkedControlId: "c-materials",
          linkedScenarioId: "sc-material-theft",
        },
        {
          id: "r-mat-2",
          title: "Tools and equipment not tracked by job",
          kind: "control",
          severity: 3,
          likelihood: 4,
          note: "Small tools and rented equipment go missing between jobs, and rentals run on after the work ends.",
          linkedKnowledgeId: "k7",
        },
      ],
      ideas: [
        {
          id: "i-mat-1",
          title: "Foreman signs delivery tickets; office matches them to the purchase order",
          category: "control",
          effort: "low",
          impact: "high",
          note: "The superintendent orders, the foreman receives, and the office pays only matched invoices.",
          status: "planned",
        },
        {
          id: "i-mat-2",
          title: "Tool and equipment check-out log",
          category: "tech",
          effort: "low",
          impact: "medium",
          note: "Scan or sign out each tool to a job and a person; the log is reviewed at month end.",
          status: "backlog",
        },
      ],
      wastes: [
        {
          id: "w-mat-1",
          kind: "muda_motion",
          label: "Trips to the supply house for missing items",
          note: "Material lists are short on small items, so crews stop and drive for parts.",
        },
      ],
    },
    {
      id: "proc-claims",
      name: "Progress billing & retainage",
      layer: "process",
      description:
        "Monthly pay applications against the schedule of values; retainage held and billed.",
      dependencies: ["proc-jobcost"],
      controlIds: ["c-sod-billing"],
      stage: 2,
      ownerPersonIds: ["p7"],
      inputs: ["Schedule of values", "Percent complete from the field", "Approved change orders"],
      outputs: ["Pay applications", "Retainage schedule"],
      risks: [
        {
          id: "r-bill-1",
          title: "Pay applications built by one person",
          kind: "continuity",
          severity: 4,
          likelihood: 3,
          note: "Only the project accountant knows how each client wants the pay application and backup.",
          linkedKnowledgeId: "k3",
          linkedScenarioId: "sc-key-person-leaves",
        },
        {
          id: "r-bill-2",
          title: "Billing ahead of the work in place",
          kind: "compliance",
          severity: 4,
          likelihood: 3,
          note: "Front-loaded schedules of values overstate progress; lenders and sureties rely on those figures.",
        },
      ],
      ideas: [
        {
          id: "i-bill-1",
          title: "Project manager confirms percent complete before billing",
          category: "control",
          effort: "low",
          impact: "high",
          note: "Field progress, not the budget, drives each line of the pay application.",
          status: "planned",
        },
        {
          id: "i-bill-2",
          title: "Retainage schedule reviewed monthly",
          category: "control",
          effort: "low",
          impact: "medium",
          note: "Retainage receivable and payable by job, with the date each can be billed or released.",
          status: "exploring",
        },
      ],
      wastes: [
        {
          id: "w-bill-1",
          kind: "muda_rework",
          label: "Pay applications returned for missing backup",
          note: "Clients send them back for lien waivers or change-order signatures, which delays payment a month.",
        },
      ],
    },
    {
      id: "proc-ar",
      name: "Collections & retainage release",
      layer: "process",
      description: "Client payments, joint checks, retainage release at closeout.",
      dependencies: ["proc-claims"],
      controlIds: ["c-ar", "c-sod-ar"],
      stage: 3,
      ownerPersonIds: ["p7", "p1"],
      inputs: ["Open pay applications", "Closeout documents", "Aging report"],
      outputs: ["Collected payments", "Released retainage"],
      risks: [
        {
          id: "r-ar-1",
          title: "Client balances written off without owner approval",
          kind: "fraud",
          severity: 4,
          likelihood: 2,
          note: "A payment kept by an insider can be hidden by writing off the balance as disputed.",
          linkedScenarioId: "sc-writeoff-abuse",
        },
        {
          id: "r-ar-2",
          title: "Retainage never billed at closeout",
          kind: "revenue",
          severity: 3,
          likelihood: 4,
          note: "Punch lists and closeout documents drag on and retainage sits unbilled.",
          linkedKnowledgeId: "k3",
        },
      ],
      ideas: [
        {
          id: "i-ar-1",
          title: "Owner reads the aging and retainage report monthly",
          category: "control",
          effort: "low",
          impact: "high",
          note: "Every write-off or credit carries a reason and the owner's initials.",
          status: "planned",
        },
        {
          id: "i-ar-2",
          title: "Closeout checklist started at 90 percent complete",
          category: "policy",
          effort: "low",
          impact: "medium",
          note: "Warranties, as-builts and final waivers are gathered before the last crew leaves.",
          status: "backlog",
        },
      ],
      wastes: [
        {
          id: "w-ar-1",
          kind: "muda_waiting",
          label: "Waiting on final lien waivers to release retainage",
          note: "Subcontractor waivers are chased one at a time at the end of the job.",
        },
      ],
    },
    {
      id: "proc-cash",
      name: "Deposits & bank reconciliation",
      layer: "process",
      description: "Client checks and ACH receipts, deposits, monthly bank reconciliation.",
      dependencies: [],
      controlIds: ["c-cash", "c-sod-cash"],
      stage: 3,
      ownerPersonIds: ["p2"],
      inputs: ["Client checks and ACH", "Bank statements", "Job receipts"],
      outputs: ["Deposits", "Reconciled bank accounts"],
      risks: [
        {
          id: "r-cash-1",
          title: "Office manager deposits, posts and reconciles",
          kind: "fraud",
          severity: 5,
          likelihood: 3,
          note: "Client payments redirected or checks written to oneself are reconciled away by the same person.",
          linkedControlId: "c-sod-cash",
          linkedScenarioId: "sc-cash-sod-failure",
        },
        {
          id: "r-cash-2",
          title: "Owner sees only the balance, not the statement",
          kind: "control",
          severity: 4,
          likelihood: 4,
          note: "A healthy balance during a busy season hides checks and transfers nobody reads.",
        },
      ],
      ideas: [
        {
          id: "i-cash-1",
          title: "Bank statements go to the owner first",
          category: "control",
          effort: "low",
          impact: "high",
          note: "The owner reads cleared checks and transfers before the office reconciles.",
          status: "planned",
        },
        {
          id: "i-cash-2",
          title: "Remote deposit with read-only access for the owner",
          category: "tech",
          effort: "low",
          impact: "medium",
          note: "Deposits are scanned the day they arrive and the owner can see them without asking.",
          status: "backlog",
        },
      ],
      wastes: [
        {
          id: "w-cash-1",
          kind: "muda_waiting",
          label: "Checks held in the office until someone goes to the bank",
          note: "Client checks sit for days, which delays both cash and the record of payment.",
        },
      ],
    },
    {
      id: "proc-ap",
      name: "Subcontractor & supplier payments",
      layer: "process",
      description:
        "Subcontractor pay applications, supplier invoices, lien waivers, insurance certificates.",
      dependencies: ["proc-jobcost", "proc-materials"],
      controlIds: ["c-ap", "c-sod-ap", "c-sub-verify", "c-lien-waivers"],
      stage: 3,
      ownerPersonIds: ["p2", "p3"],
      inputs: ["Subcontractor pay applications", "Supplier invoices", "Lien waivers"],
      outputs: ["Approved payments", "Waiver log"],
      risks: [
        {
          id: "r-ap-1",
          title: "Office manager sets up vendors and releases payments",
          kind: "fraud",
          severity: 5,
          likelihood: 3,
          note: "A subcontractor that does not exist can be added and paid, and its invoices coded to an open job.",
          linkedControlId: "c-sod-ap",
          linkedScenarioId: "sc-fictitious-sub",
        },
        {
          id: "r-ap-2",
          title: "Payments released without lien waivers",
          kind: "compliance",
          severity: 4,
          likelihood: 3,
          note: "In many states an unpaid sub-tier supplier can lien the client's property even after the subcontractor was paid.",
          linkedControlId: "c-lien-waivers",
          linkedKnowledgeId: "k4",
        },
      ],
      ideas: [
        {
          id: "i-ap-1",
          title: "Project manager approves each pay application; office pays only approved ones",
          category: "control",
          effort: "low",
          impact: "high",
          note: "Approval checks the billed percent against the work in place and the subcontract.",
          status: "planned",
        },
        {
          id: "i-ap-2",
          title: "No waiver, no check",
          category: "policy",
          effort: "low",
          impact: "high",
          note: "Payment is held until this payment's conditional waiver and last payment's unconditional waiver are on file.",
          status: "planned",
        },
      ],
      wastes: [
        {
          id: "w-ap-1",
          kind: "muda_overprocessing",
          label: "Insurance certificates checked by hand each payment",
          note: "Expiry dates are looked up in email instead of a tracked list.",
        },
      ],
    },
    {
      id: "proc-payroll",
      name: "Payroll, field time & certified payroll",
      layer: "process",
      description:
        "Crew timesheets, job cost allocation, prevailing wage and certified payroll reports.",
      dependencies: [],
      controlIds: ["c-payroll", "c-field-time"],
      stage: 4,
      ownerPersonIds: ["p8", "p4", "p1"],
      inputs: ["Crew timesheets", "Daily reports", "Wage determinations"],
      outputs: ["Payroll", "Labor cost by job", "Certified payroll reports"],
      risks: [
        {
          id: "r-pay-1",
          title: "Timesheets paid without a check against daily reports",
          kind: "fraud",
          severity: 4,
          likelihood: 3,
          note: "Padded hours and people who were never on site are paid with the rest of the crew.",
          linkedControlId: "c-field-time",
          linkedScenarioId: "sc-field-time-padding",
        },
        {
          id: "r-pay-2",
          title: "Wrong wage rate or classification on a public job",
          kind: "compliance",
          severity: 4,
          likelihood: 3,
          note: "Prevailing-wage underpayment means back wages and can bar the company from public work.",
          linkedKnowledgeId: "k5",
        },
      ],
      ideas: [
        {
          id: "i-pay-1",
          title: "Superintendent approves crew hours by job each week",
          category: "control",
          effort: "low",
          impact: "high",
          note: "Hours are matched to daily reports before they reach the payroll administrator.",
          status: "planned",
        },
        {
          id: "i-pay-2",
          title: "Owner reads the payroll change report every run",
          category: "control",
          effort: "low",
          impact: "high",
          note: "New hires, rate changes and bank account changes, compared with who is on the jobs.",
          status: "exploring",
        },
      ],
      wastes: [
        {
          id: "w-pay-1",
          kind: "muda_rework",
          label: "Paper timesheets re-keyed and re-coded",
          note: "Hours are typed from paper and cost codes corrected after payroll has run.",
        },
      ],
    },
  ],
  controls: [...baseFinancialControls(), ...constructionControls],
  staffComposition: {
    ...DEFAULT_STAFF,
    teamSize: 8,
    soleOwnerKnowledgeCount: 3,
    avgTenureYears: 7.9,
    segregationScore: 36,
  },
  crimeFraudStats: DEFAULT_FRAUD_STATS,
  scenarios: [
    ...baseFraudScenarios({
      keyPersonTitle: "Project accountant leaves with sole pay-application knowledge",
      keyPersonDesc:
        "The project accountant (sole expert on pay applications and retainage) resigns in the middle of several jobs. Billing slips a month and retainage goes unbilled.",
      knowledgeId: "k3",
      billingLabel: "Client balances written off without owner approval",
    }),
    ...constructionScenarios,
  ],
  roleTemplates: {
    "Owner / President": [
      "approve_vendor",
      "approve_payroll",
      "approve_writeoffs",
      "approve_expenses",
      "sign_checks",
      "view_reports_only",
    ],
    "Office Manager": [
      "post_payments",
      "prepare_deposit",
      "enter_invoices",
      "create_vendor",
      "release_payment",
      "bank_reconcile",
      "hold_company_card",
      "review_card_statement",
      "view_reports_only",
    ],
    "Project Manager": ["approve_invoices", "order_supplies", "view_reports_only"],
    Superintendent: ["order_supplies", "receive_goods", "view_reports_only"],
    Estimator: ["change_fee_schedule", "view_reports_only"],
    Foreman: ["receive_goods", "view_reports_only"],
    "Project Accountant": [
      "submit_claims",
      "post_adjustments",
      "post_journal_entries",
      "view_reports_only",
    ],
    "Payroll Administrator": ["enter_payroll", "edit_payroll_master", "view_reports_only"],
  },
};
