import type { IndustrySample } from "./types";
import {
  baseFinancialControls,
  SAMPLE_SAFEGUARDS,
  SCENARIO_FIGURES,
  sharedFraudScenarios,
} from "./shared-controls";

/**
 * A dental, medical or veterinary office of about six people: the owner who
 * treats patients, an office manager who runs the money and the payroll, a
 * front desk lead who takes payments and knows the insurance appeals, a
 * billing specialist, and clinical staff. The shared controls and scenarios
 * are reworded only where the office differs (claims instead of invoices, a
 * packing slip instead of a receipt); the office adds claims, scheduling,
 * clinical and controlled-drug controls of its own.
 */
export const dentalTemplate: IndustrySample = {
  id: "dental",
  people: [
    { id: "p1", name: "Dr. Elena Vargas", role: "Owner / Dentist", active: true, tenureYears: 12 },
    { id: "p2", name: "Maya Chen", role: "Office Manager", active: true, tenureYears: 7 },
    { id: "p3", name: "Jordan Blake", role: "Front Desk Lead", active: true, tenureYears: 5 },
    { id: "p4", name: "Sam Ortiz", role: "Hygienist", active: true, tenureYears: 4 },
    { id: "p5", name: "Riley Kim", role: "Dental Assistant", active: true, tenureYears: 2 },
    { id: "p6", name: "Chris Patel", role: "Billing Specialist", active: true, tenureYears: 3 },
  ],
  roleTemplates: {
    "Owner / Dentist": [
      "approve_writeoffs",
      "approve_vendor",
      "approve_payroll",
      "approve_expenses",
      "bank_reconcile",
      "view_reports_only",
      "pms_admin_roles",
    ],
    "Office Manager": [
      "post_payments",
      "prepare_deposit",
      "post_adjustments",
      "create_vendor",
      "release_payment",
      "enter_payroll",
      "approve_writeoffs",
      "pms_admin_roles",
      "submit_claims",
      "hold_company_card",
      "review_card_statement",
      "view_reports_only",
    ],
    "Front Desk Lead": [
      "collect_cash",
      "post_payments",
      "prepare_deposit",
      "submit_claims",
      "post_adjustments",
    ],
    Hygienist: ["view_reports_only"],
    "Dental Assistant": ["view_reports_only"],
    "Billing Specialist": [
      "submit_claims",
      "post_adjustments",
      "post_payments",
      "approve_writeoffs",
      "bank_reconcile",
      "view_reports_only",
    ],
  },
  knowledge: [
    {
      id: "k1",
      name: "Insurance denial appeals",
      description: "Full denial workflow, payer quirks, appeal letter patterns.",
      criticality: "critical",
      category: "process",
      linkedProcessIds: ["proc-claims"],
    },
    {
      id: "k2",
      name: "Daily deposit & reconciliation",
      description: "Cash drawer, electronic payment matching, practice software vs bank deposit.",
      criticality: "critical",
      category: "process",
      linkedProcessIds: ["proc-cash"],
    },
    {
      id: "k3",
      name: "Practice software administration",
      description: "User roles, fee schedules, claim templates, report setup.",
      criticality: "critical",
      category: "system",
      linkedProcessIds: ["proc-claims", "proc-schedule"],
    },
    {
      id: "k4",
      name: "Vendor invoice approval",
      description: "Lab bills, supply orders, approval thresholds.",
      criticality: "important",
      category: "vendor",
      linkedProcessIds: ["proc-ap"],
    },
    {
      id: "k5",
      name: "Sterilization protocol",
      description: "Instrument flow, spore testing, documentation.",
      criticality: "critical",
      category: "clinical",
      linkedProcessIds: ["proc-clinical"],
    },
    {
      id: "k6",
      name: "Payroll exception handling",
      description: "Overtime, bonus and paid-time-off edge cases in the payroll export.",
      criticality: "important",
      category: "process",
      linkedProcessIds: ["proc-payroll"],
    },
    {
      id: "k7",
      name: "Write-off & adjustment authority",
      description: "Who may adjust balances and how they document each adjustment.",
      criticality: "critical",
      category: "compliance",
      linkedProcessIds: ["proc-ar"],
    },
    {
      id: "k8",
      name: "Controlled-substance records",
      description:
        "DEA registration, order forms, the administration and dispensing log, biennial inventory, theft and loss reports. Dental, medical and veterinary offices alike.",
      criticality: "critical",
      category: "compliance",
      linkedProcessIds: ["proc-controlled"],
    },
  ],
  relations: [
    { personId: "p3", knowledgeId: "k1", level: "expert" },
    { personId: "p3", knowledgeId: "k2", level: "expert" },
    { personId: "p6", knowledgeId: "k1", level: "basic" },
    { personId: "p2", knowledgeId: "k2", level: "proficient" },
    { personId: "p2", knowledgeId: "k3", level: "expert" },
    { personId: "p6", knowledgeId: "k3", level: "basic" },
    { personId: "p2", knowledgeId: "k4", level: "expert" },
    { personId: "p1", knowledgeId: "k4", level: "aware" },
    { personId: "p4", knowledgeId: "k5", level: "expert" },
    { personId: "p5", knowledgeId: "k5", level: "proficient" },
    { personId: "p2", knowledgeId: "k6", level: "expert" },
    { personId: "p6", knowledgeId: "k7", level: "expert" },
    { personId: "p2", knowledgeId: "k7", level: "proficient" },
    { personId: "p1", knowledgeId: "k8", level: "expert" },
    { personId: "p5", knowledgeId: "k8", level: "basic" },
  ],
  processes: [
    {
      id: "proc-schedule",
      name: "Scheduling & chair utilization",
      layer: "process",
      description: "Booking, confirmations, same-day openings.",
      dependencies: [],
      controlIds: ["c-schedule"],
      stage: 0,
      ownerPersonIds: ["p3", "p2"],
      inputs: ["Patient demand", "Provider templates"],
      outputs: ["Confirmed chair schedule"],
      risks: [
        {
          id: "r-sched-1",
          title: "No-show cascade",
          kind: "revenue",
          severity: 3,
          likelihood: 4,
          note: "Gaps open late; hygiene production drops without recovery protocol.",
        },
        {
          id: "r-sched-2",
          title: "Only one person can rebuild schedule templates",
          kind: "continuity",
          severity: 4,
          likelihood: 2,
          note: "Only the office manager can rebuild the schedule templates after a staff change.",
          linkedKnowledgeId: "k3",
        },
      ],
      ideas: [
        {
          id: "i-sched-1",
          title: "Same-day fill list automation",
          category: "tech",
          effort: "medium",
          impact: "high",
          note: "Text the waitlist when a cancellation comes in more than 90 minutes out.",
          status: "exploring",
        },
        {
          id: "i-sched-2",
          title: "Write down how to rebuild the templates",
          category: "training",
          effort: "low",
          impact: "medium",
          note: "Screen-record the practice software steps so the billing specialist can cover.",
          status: "planned",
        },
      ],
      wastes: [],
    },
    {
      id: "proc-clinical",
      name: "Clinical delivery",
      layer: "process",
      description: "Hygiene and restorative chairside flow.",
      dependencies: ["proc-schedule"],
      controlIds: ["c-clinical"],
      stage: 1,
      ownerPersonIds: ["p1", "p4"],
      inputs: ["Schedule", "Sterile instruments", "Chart history"],
      outputs: ["Completed procedures", "Clinical notes"],
      risks: [
        {
          id: "r-clin-1",
          title: "Incomplete same-day notes",
          kind: "compliance",
          severity: 3,
          likelihood: 3,
          note: "Claims delayed when notes lag; audit exposure.",
        },
      ],
      ideas: [
        {
          id: "i-clin-1",
          title: "Note close checklist at checkout",
          category: "policy",
          effort: "low",
          impact: "medium",
          note: "Block next appointment book until note status green.",
          status: "backlog",
        },
      ],
      wastes: [],
    },
    {
      // DEA registrants keep records of every controlled substance received,
      // administered, dispensed and destroyed (21 CFR 1304), take an inventory
      // at least every two years (21 CFR 1304.11), store the drugs locked
      // (21 CFR 1301.75), and report theft or significant loss within one
      // business day of discovery (21 CFR 1301.76(b)). The same rules apply to
      // a veterinary practice's anesthetics and analgesics.
      id: "proc-controlled",
      name: "Controlled drugs: log, counts & dispensing",
      layer: "process",
      description:
        "If the office keeps controlled substances: DEA ordering, locked storage, the administration and dispensing log, inventory counts.",
      dependencies: ["proc-clinical"],
      controlIds: ["c-controlled"],
      stage: 1,
      ownerPersonIds: ["p1", "p5"],
      inputs: ["DEA order forms and supplier invoices", "Administration and dispensing records"],
      outputs: ["Controlled-substance log", "Inventory counts", "Theft or loss reports"],
      risks: [
        {
          id: "r-cs-1",
          title: "One person orders, stores, logs and counts",
          kind: "fraud",
          severity: 5,
          likelihood: 2,
          note: "Someone can take drugs and alter the log or the vials to hide it, as in the oral surgery fentanyl case in the library; nobody else compares stock with the records.",
          linkedControlId: "c-controlled",
          linkedScenarioId: "sc-drug-diversion",
          linkedKnowledgeId: "k8",
        },
        {
          id: "r-cs-2",
          title: "Inventory or loss report missed",
          kind: "compliance",
          severity: 4,
          likelihood: 2,
          note: "A registrant inventories every controlled substance at least every two years and reports theft or significant loss to DEA within one business day of discovery.",
          linkedKnowledgeId: "k8",
        },
      ],
      ideas: [
        {
          id: "i-cs-1",
          title: "Two people count Schedule II drugs and both sign the log",
          category: "control",
          effort: "low",
          impact: "high",
          note: "Counts at a set time each week, and whenever the person holding the key changes.",
          status: "planned",
        },
        {
          id: "i-cs-2",
          title: "Monthly log reconciliation to purchases and patient records",
          category: "control",
          effort: "medium",
          impact: "high",
          note: "Someone who does not administer the drugs matches doses logged to procedures charted.",
          status: "exploring",
        },
      ],
      wastes: [],
    },
    {
      id: "proc-claims",
      name: "Claims & denials",
      layer: "process",
      description: "Submit, track, appeal insurance claims.",
      dependencies: ["proc-clinical"],
      controlIds: ["c-claims", "c-sod-billing"],
      stage: 2,
      ownerPersonIds: ["p6", "p3"],
      inputs: ["Clinical notes", "Fee schedule", "Eligibility"],
      outputs: ["Paid claims", "Denial queue"],
      risks: [
        {
          id: "r-claims-1",
          title: "Sole denial expert leaves",
          kind: "continuity",
          severity: 5,
          likelihood: 3,
          note: "Often only the front desk lead knows appeals — revenue lag multiplies.",
          linkedKnowledgeId: "k1",
          linkedScenarioId: "sc-front-desk-leaves",
        },
        {
          id: "r-claims-2",
          title: "Billing posts write-offs alone",
          kind: "fraud",
          severity: 4,
          likelihood: 3,
          note: "One person submits claims and posts adjustments with no second approval.",
          linkedControlId: "c-sod-billing",
          linkedScenarioId: "sc-writeoff-abuse",
        },
      ],
      ideas: [
        {
          id: "i-claims-1",
          title: "Cross-train the billing specialist on appeals",
          category: "training",
          effort: "medium",
          impact: "high",
          note: "Shadow 10 denials; document payer quirks wiki.",
          status: "planned",
        },
        {
          id: "i-claims-2",
          title: "Owner approves write-offs above the amount you set",
          category: "control",
          effort: "low",
          impact: "high",
          note: "Set the limit in the practice software and read a weekly exception report.",
          status: "exploring",
        },
      ],
      wastes: [],
    },
    {
      id: "proc-cash",
      name: "Cash handling & deposits",
      layer: "process",
      description: "Patient payments, drawer, bank deposit.",
      dependencies: [],
      controlIds: ["c-cash", "c-sod-cash"],
      stage: 2,
      ownerPersonIds: ["p3"],
      inputs: ["Patient payments", "Drawer float"],
      outputs: ["Bank deposit", "Payments posted in the practice software"],
      risks: [
        {
          id: "r-cash-1",
          title: "One person posts payments and reconciles the bank",
          kind: "fraud",
          severity: 5,
          likelihood: 4,
          note: "The classic path to embezzlement.",
          linkedControlId: "c-sod-cash",
          linkedScenarioId: "sc-cash-sod-failure",
        },
        {
          id: "r-cash-2",
          title: "Only one person can run the daily deposit",
          kind: "continuity",
          severity: 4,
          likelihood: 3,
          note: "Often only the front desk lead can run the daily deposit and reconciliation.",
          linkedKnowledgeId: "k2",
        },
      ],
      ideas: [
        {
          id: "i-cash-1",
          title: "Owner reconciles the bank independently each week",
          category: "control",
          effort: "low",
          impact: "high",
          note: "Owner sees bank activity without going through the person who posts payments, so nobody can hide a diverted payment by adjusting the books. About twenty minutes a week.",
          status: "planned",
        },
        {
          id: "i-cash-2",
          title: "Two-person count and a camera at drawer close",
          category: "control",
          effort: "medium",
          impact: "medium",
          note: "May unlock insurance premium credit.",
          status: "backlog",
        },
      ],
      wastes: [],
    },
    {
      id: "proc-ar",
      name: "Receivables & adjustments",
      layer: "process",
      description: "Patient balances, write-offs, collections.",
      dependencies: ["proc-claims"],
      controlIds: ["c-ar", "c-sod-ar"],
      stage: 3,
      ownerPersonIds: ["p6", "p2"],
      inputs: ["Open claims", "Patient balances"],
      outputs: ["Collections", "Adjustments"],
      risks: [
        {
          id: "r-ar-1",
          title: "Undocumented write-offs",
          kind: "fraud",
          severity: 4,
          likelihood: 3,
          note: "Adjustments without reason codes hide leakage.",
          linkedKnowledgeId: "k7",
          linkedScenarioId: "sc-writeoff-abuse",
        },
      ],
      ideas: [
        {
          id: "i-ar-1",
          title: "Monthly adjustment aging report",
          category: "control",
          effort: "low",
          impact: "high",
          note: "Owner signs exception report.",
          status: "planned",
        },
        {
          id: "i-ar-2",
          title: "Reason code required in the practice software",
          category: "tech",
          effort: "low",
          impact: "medium",
          note: "The software will not save an adjustment without a code and a note.",
          status: "exploring",
        },
      ],
      wastes: [],
    },
    {
      id: "proc-ap",
      name: "Accounts payable",
      layer: "process",
      description: "Vendor invoices, labs, supplies.",
      dependencies: [],
      controlIds: ["c-ap", "c-sod-ap"],
      stage: 3,
      ownerPersonIds: ["p2"],
      inputs: ["Vendor invoices", "Lab slips"],
      outputs: ["Paid vendors"],
      risks: [
        {
          id: "r-ap-1",
          title: "One person sets up vendors and pays them",
          kind: "fraud",
          severity: 5,
          likelihood: 3,
          note: "An insider can set up and pay a fake vendor, because no second person releases payments.",
          linkedControlId: "c-sod-ap",
          linkedScenarioId: "sc-vendor-fraud",
        },
      ],
      ideas: [
        {
          id: "i-ap-1",
          title: "Require dual ACH release above a set amount",
          category: "control",
          effort: "medium",
          impact: "high",
          note: "Bank dual approval above the amount you set; owner is second signer.",
          status: "planned",
        },
        {
          id: "i-ap-2",
          title: "New-vendor monthly review",
          category: "policy",
          effort: "low",
          impact: "medium",
          note: "Print vendor master changes; owner initials.",
          status: "backlog",
        },
      ],
      wastes: [],
    },
    {
      id: "proc-payroll",
      name: "Payroll",
      layer: "process",
      description: "Time, exceptions, payroll export.",
      dependencies: [],
      controlIds: ["c-payroll"],
      stage: 4,
      ownerPersonIds: ["p2", "p1"],
      inputs: ["Time punches", "Overtime exceptions"],
      outputs: ["Payroll file", "Pay stubs"],
      risks: [
        {
          id: "r-pay-1",
          title: "Nobody writes down payroll exceptions",
          kind: "continuity",
          severity: 3,
          likelihood: 3,
          note: "Often only the office manager knows the overtime and bonus edge cases.",
          linkedKnowledgeId: "k6",
        },
      ],
      ideas: [
        {
          id: "i-pay-1",
          title: "Exception playbook one-pager",
          category: "training",
          effort: "low",
          impact: "medium",
          note: "Owner can run one cycle without the office manager.",
          status: "exploring",
        },
      ],
      wastes: [],
    },
  ],
  controls: [
    ...baseFinancialControls({
      "c-sod-cash": {
        compensatingControls: ["Owner compares the deposit slip to the day sheet weekly"],
      },
      "c-sod-billing": {
        name: "Split duties: claims adjustments",
        description: "Billing can submit claims and post write-offs.",
      },
      "c-ap": { description: "Match packing slip to invoice before payment." },
    }),
    {
      id: "c-claims",
      name: "Denial aging review",
      description: "Weekly review of denials open more than 30 days.",
      duties: ["review"],
      segregated: true,
      compensatingControls: [],
      residualRiskAccepted: false,
    },
    {
      id: "c-schedule",
      name: "Schedule change audit",
      description: "Daily confirmation of schedule changes.",
      duties: ["review"],
      segregated: true,
      compensatingControls: [],
      residualRiskAccepted: false,
    },
    {
      id: "c-clinical",
      name: "Clinical documentation check",
      description: "Charts closed same day with required elements.",
      duties: ["review"],
      segregated: true,
      compensatingControls: [],
      residualRiskAccepted: false,
    },
    {
      id: "c-controlled",
      name: "Controlled-substance log and counts",
      description:
        "Someone who does not administer the drugs counts stock against the log and purchase records; the practice investigates any difference and reports theft or significant loss to DEA.",
      duties: ["custody", "recording", "reconciliation"],
      segregated: false,
      compensatingControls: ["Owner reads the log at month end"],
      residualRiskAccepted: false,
    },
  ],
  staffComposition: SAMPLE_SAFEGUARDS,
  scenarios: [
    {
      id: "sc-front-desk-leaves",
      title: "Front desk lead leaves with sole denial knowledge",
      description:
        "The front desk lead (sole expert on insurance denial appeals) resigns with two weeks' notice. Nobody else has trained for the work.",
      knowledgeId: "k1",
      controlId: "c-claims",
      ...SCENARIO_FIGURES.frontDesk,
      cascadeLayers: ["knowledge", "process", "surface", "continuity"],
      mitigations: [
        {
          id: "m1",
          label: "Cross-train billing on denial appeals with a written procedure",
          effort: "medium",
          riskReduction: 0.55,
          costAnnual: 2400,
        },
        {
          id: "m2",
          label: "Hire temporary billing help for 90 days",
          effort: "high",
          riskReduction: 0.65,
          costAnnual: 12000,
        },
        {
          id: "m3",
          label: "Record the front desk lead's denial playbook before they leave",
          effort: "low",
          riskReduction: 0.35,
          costAnnual: 400,
        },
      ],
    },
    ...sharedFraudScenarios({
      "sc-cash-sod-failure": {
        extraMitigations: [
          {
            id: "m6",
            label: "Camera and a two-person count at cash drawer close",
            effort: "medium",
            riskReduction: 0.4,
            costAnnual: 800,
          },
        ],
      },
      "sc-writeoff-abuse": {
        knowledgeId: "k7",
        extraMitigations: [
          {
            id: "m8",
            label: "Monthly adjustment exception report",
            effort: "low",
            riskReduction: 0.45,
            costAnnual: 0,
          },
        ],
      },
      "sc-vendor-fraud": {
        extraMitigations: [
          {
            id: "m10",
            label: "Someone independent reviews new vendors each month",
            effort: "low",
            riskReduction: 0.5,
            costAnnual: 0,
          },
        ],
      },
    }),
    {
      // The write-off scenario's figures (see SCENARIO_FIGURES); the larger harm
      // here is to patients and to the practice's DEA registration.
      id: "sc-drug-diversion",
      title: "Controlled drugs diverted and the log altered",
      description:
        "The person who handles controlled drugs also keeps the log and does the counts. Someone removes drugs and changes the log or the vials so the count still matches; the office learns of it from a patient harmed, a DEA inspection, or a colleague who speaks up.",
      controlId: "c-controlled",
      knowledgeId: "k8",
      caseIds: ["case-littleton-oral-surgery-fentanyl"],
      ...SCENARIO_FIGURES.writeoff,
      cascadeLayers: ["control", "process", "surface", "continuity"],
      mitigations: [
        {
          id: "m11",
          label: "Two people count and sign for every Schedule II drug",
          effort: "low",
          riskReduction: 0.5,
          costAnnual: 0,
        },
        {
          id: "m12",
          label: "Monthly log reconciliation by someone who does not administer",
          effort: "medium",
          riskReduction: 0.45,
          costAnnual: 0,
        },
      ],
    },
  ],
};
