import type { IndustryTemplate } from "./types";
import {
  baseFinancialControls,
  baseFraudScenarios,
  DEFAULT_FRAUD_STATS,
  DEFAULT_STAFF,
} from "./shared-controls";

export const generalTemplate: IndustryTemplate = {
  id: "general",
  businessName: "Main Street Business Co.",
  people: [
    { id: "p1", name: "Alex Owner", role: "Owner", active: true, tenureYears: 10 },
    { id: "p2", name: "Maya Chen", role: "Operations Manager", active: true, tenureYears: 6 },
    { id: "p3", name: "Jordan Blake", role: "Sales Lead", active: true, tenureYears: 4 },
    { id: "p4", name: "Sam Ortiz", role: "Admin / AR", active: true, tenureYears: 3 },
    { id: "p5", name: "Riley Kim", role: "AP Clerk", active: true, tenureYears: 2 },
    { id: "p6", name: "Chris Patel", role: "Bookkeeper", active: true, tenureYears: 3 },
  ],
  knowledge: [
    {
      id: "k1",
      name: "Customer billing workflow",
      description: "Invoicing, payment terms, dunning process.",
      criticality: "critical",
      category: "process",
      linkedProcessIds: ["proc-billing"],
    },
    {
      id: "k2",
      name: "Daily deposit & reconciliation",
      description: "Cash/check deposits, bank rec, merchant batches.",
      criticality: "critical",
      category: "process",
      linkedProcessIds: ["proc-cash"],
    },
    {
      id: "k3",
      name: "ERP / accounting admin",
      description: "Chart of accounts, user roles, report setup.",
      criticality: "critical",
      category: "system",
      linkedProcessIds: ["proc-billing", "proc-ap"],
    },
    {
      id: "k4",
      name: "Vendor master & onboarding",
      description: "New vendor approval, payment methods.",
      criticality: "important",
      category: "vendor",
      linkedProcessIds: ["proc-ap"],
    },
    {
      id: "k5",
      name: "Sales pipeline & quoting",
      description: "Quote approval, discount authority.",
      criticality: "important",
      category: "process",
      linkedProcessIds: ["proc-sales"],
    },
    {
      id: "k6",
      name: "Adjustment / credit authority",
      description: "Who can issue credits and write off balances.",
      criticality: "critical",
      category: "compliance",
      linkedProcessIds: ["proc-ar"],
    },
  ],
  relations: [
    { personId: "p4", knowledgeId: "k1", level: "expert" },
    { personId: "p6", knowledgeId: "k1", level: "basic" },
    { personId: "p4", knowledgeId: "k2", level: "expert" },
    { personId: "p2", knowledgeId: "k2", level: "proficient" },
    { personId: "p2", knowledgeId: "k3", level: "expert" },
    { personId: "p5", knowledgeId: "k4", level: "expert" },
    { personId: "p3", knowledgeId: "k5", level: "expert" },
    { personId: "p6", knowledgeId: "k6", level: "expert" },
    { personId: "p2", knowledgeId: "k6", level: "proficient" },
  ],
  processes: [
    {
      id: "proc-sales",
      name: "Sales & quoting",
      layer: "process",
      description: "Leads, quotes, order intake.",
      dependencies: [],
      controlIds: [],
      stage: 0,
      ownerPersonIds: ["p3"],
      inputs: ["Inbound leads", "Price list", "Discount rules"],
      outputs: ["Approved quotes", "Confirmed orders"],
      risks: [
        {
          id: "r-sales-1",
          title: "Discounts given outside approved limits",
          kind: "revenue",
          severity: 3,
          likelihood: 4,
          note: "Sales lead sets pricing with no second look; margin erodes one deal at a time.",
          linkedKnowledgeId: "k5",
        },
        {
          id: "r-sales-2",
          title: "Quotes and pipeline live only with the sales lead",
          kind: "continuity",
          severity: 3,
          likelihood: 3,
          note: "Open deals and customer promises are in Jordan's inbox, not the shared system.",
          linkedKnowledgeId: "k5",
        },
      ],
      ideas: [
        {
          id: "i-sales-1",
          title: "Owner approval required for discounts over 10%",
          category: "policy",
          effort: "low",
          impact: "medium",
          note: "Quote tool blocks send until the owner approves anything past the threshold.",
          status: "planned",
        },
        {
          id: "i-sales-2",
          title: "Log every quote in the shared CRM",
          category: "tech",
          effort: "medium",
          impact: "medium",
          note: "Pipeline visible to the owner and ops so orders can be fulfilled without asking sales.",
          status: "exploring",
        },
      ],
      wastes: [
        {
          id: "w-sales-1",
          kind: "muda_rework",
          label: "Quotes re-done after order intake",
          note: "Handwritten or emailed quotes are re-keyed into the order system and often corrected.",
        },
      ],
    },
    {
      id: "proc-billing",
      name: "Billing & invoicing",
      layer: "process",
      description: "Invoice generation, delivery, revenue recognition.",
      dependencies: ["proc-sales"],
      controlIds: ["c-sod-billing"],
      stage: 1,
      ownerPersonIds: ["p4"],
      inputs: ["Confirmed orders", "Delivery confirmations", "Customer payment terms"],
      outputs: ["Customer invoices", "Revenue posted"],
      risks: [
        {
          id: "r-bill-1",
          title: "Billing SPOF",
          kind: "continuity",
          severity: 4,
          likelihood: 3,
          note: "Admin/AR sole billing expert.",
          linkedKnowledgeId: "k1",
          linkedScenarioId: "sc-key-person-leaves",
        },
        {
          id: "r-bill-2",
          title: "Delivered work never invoiced",
          kind: "revenue",
          severity: 3,
          likelihood: 3,
          note: "No check that every completed order has a matching invoice; missed billings go unnoticed.",
        },
      ],
      ideas: [
        {
          id: "i-bill-1",
          title: "Weekly unbilled-orders report to the owner",
          category: "control",
          effort: "low",
          impact: "high",
          note: "Compare shipped or completed orders to invoices; anything over 7 days is flagged.",
          status: "planned",
        },
        {
          id: "i-bill-2",
          title: "Cross-train bookkeeper on invoicing",
          category: "training",
          effort: "medium",
          impact: "high",
          note: "Chris runs one billing cycle a month with Sam reviewing; steps written into a checklist.",
          status: "exploring",
        },
      ],
      wastes: [
        {
          id: "w-bill-1",
          kind: "muda_waiting",
          label: "Invoices batched at month end",
          note: "Cash arrives weeks later than it would with invoicing at delivery.",
        },
      ],
    },
    {
      id: "proc-cash",
      name: "Cash handling & deposits",
      layer: "process",
      description: "Customer payments, deposits, reconciliation.",
      dependencies: [],
      controlIds: ["c-cash", "c-sod-cash"],
      stage: 2,
      ownerPersonIds: ["p4"],
      inputs: ["Customer checks and cash", "Card batches", "Bank statements"],
      outputs: ["Bank deposits", "Reconciled bank account"],
      risks: [
        {
          id: "r-cash-1",
          title: "Posting + recon not segregated",
          kind: "fraud",
          severity: 5,
          likelihood: 4,
          note: "Classic SMB embezzlement path.",
          linkedControlId: "c-sod-cash",
          linkedScenarioId: "sc-cash-sod-failure",
        },
        {
          id: "r-cash-2",
          title: "Deposits held for days before banking",
          kind: "control",
          severity: 3,
          likelihood: 3,
          note: "Checks sit in a drawer; lapping and lost items are hard to spot.",
          linkedKnowledgeId: "k2",
        },
      ],
      ideas: [
        {
          id: "i-cash-1",
          title: "Owner reviews bank statement and reconciliation monthly",
          category: "control",
          effort: "low",
          impact: "high",
          note: "Statement goes to the owner first; owner initials the rec and questions any unmatched items.",
          status: "planned",
        },
        {
          id: "i-cash-2",
          title: "Remote check deposit same day",
          category: "tech",
          effort: "low",
          impact: "medium",
          note: "Bank scanner or mobile deposit removes the drawer step and creates a daily audit trail.",
          status: "backlog",
        },
      ],
      wastes: [
        {
          id: "w-cash-1",
          kind: "muda_overprocessing",
          label: "Payments logged in three places",
          note: "Deposit slip, spreadsheet, and accounting system all keyed by hand for the same check.",
        },
      ],
    },
    {
      id: "proc-ap",
      name: "Accounts payable",
      layer: "process",
      description: "Vendor invoices and payments.",
      dependencies: [],
      controlIds: ["c-ap", "c-sod-ap"],
      stage: 3,
      ownerPersonIds: ["p5", "p2"],
      inputs: ["Vendor invoices", "Purchase orders", "Receiving confirmations"],
      outputs: ["Approved payments", "Vendor statements reconciled"],
      risks: [
        {
          id: "r-ap-1",
          title: "Vendor setup + payment same person",
          kind: "fraud",
          severity: 5,
          likelihood: 3,
          note: "Fictitious vendor path.",
          linkedControlId: "c-sod-ap",
          linkedScenarioId: "sc-vendor-fraud",
        },
        {
          id: "r-ap-2",
          title: "Vendor bank-change requests taken by email",
          kind: "fraud",
          severity: 4,
          likelihood: 3,
          note: "Business email compromise; a spoofed vendor asks to update banking and the next payment is gone.",
          linkedKnowledgeId: "k4",
        },
      ],
      ideas: [
        {
          id: "i-ap-1",
          title: "Positive-pay file to bank for all checks",
          category: "control",
          effort: "low",
          impact: "high",
          note: "Bank clears only checks on the issued file, which catches counterfeit serials and altered amounts. A forged signature on a check that is on the file still clears.",
          status: "planned",
        },
        {
          id: "i-ap-2",
          title: "Call-back verification for any vendor banking change",
          category: "policy",
          effort: "low",
          impact: "high",
          note: "Phone the vendor at a number already on file before updating payment details.",
          status: "exploring",
        },
      ],
      wastes: [
        {
          id: "w-ap-1",
          kind: "muri",
          label: "AP clerk carries every vendor payment alone",
          note: "No backup when Riley is out; payments pile up and late fees follow.",
        },
      ],
    },
    {
      id: "proc-ar",
      name: "Collections & credits",
      layer: "process",
      description: "A/R, credits, write-offs.",
      dependencies: ["proc-billing"],
      controlIds: ["c-ar", "c-sod-ar"],
      stage: 3,
      ownerPersonIds: ["p4", "p6"],
      inputs: ["Open invoices", "Aging report", "Customer disputes"],
      outputs: ["Collected payments", "Approved credits"],
      risks: [
        {
          id: "r-ar-1",
          title: "Undocumented credits",
          kind: "fraud",
          severity: 4,
          likelihood: 3,
          note: "Bookkeeper posts credits without approval.",
          linkedKnowledgeId: "k6",
          linkedScenarioId: "sc-writeoff-abuse",
        },
        {
          id: "r-ar-2",
          title: "No one owns follow-up past 60 days",
          kind: "revenue",
          severity: 3,
          likelihood: 4,
          note: "Old balances drift into bad debt because collection calls are nobody's job.",
        },
      ],
      ideas: [
        {
          id: "i-ar-1",
          title: "Owner signs monthly credit and write-off report",
          category: "control",
          effort: "low",
          impact: "high",
          note: "Every credit needs a reason code; owner reviews the list against customer complaints.",
          status: "planned",
        },
        {
          id: "i-ar-2",
          title: "Automated payment reminders at 30 and 45 days",
          category: "tech",
          effort: "low",
          impact: "medium",
          note: "Accounting system emails statements so staff only call true exceptions.",
          status: "backlog",
        },
      ],
      wastes: [
        {
          id: "w-ar-1",
          kind: "mura",
          label: "Collections only happen when cash is tight",
          note: "Effort spikes at quarter end and then stops; customers learn to pay late.",
        },
      ],
    },
    {
      id: "proc-payroll",
      name: "Payroll",
      layer: "process",
      description: "Payroll processing and approval.",
      dependencies: [],
      controlIds: ["c-payroll"],
      stage: 4,
      ownerPersonIds: ["p2", "p1"],
      inputs: ["Approved time records", "Pay rate changes", "New hire and termination forms"],
      outputs: ["Payroll file", "Pay stubs and tax filings"],
      risks: [
        {
          id: "r-pay-1",
          title: "Rate changes entered and approved by the same person",
          kind: "fraud",
          severity: 4,
          likelihood: 2,
          note: "Ops manager can add an employee or raise a rate with no second review.",
          linkedControlId: "c-payroll",
        },
        {
          id: "r-pay-2",
          title: "Payroll runs late when the ops manager is out",
          kind: "continuity",
          severity: 3,
          likelihood: 3,
          note: "Nobody else knows the payroll portal steps or the overtime rules.",
        },
      ],
      ideas: [
        {
          id: "i-pay-1",
          title: "Owner approves payroll register before each run",
          category: "control",
          effort: "low",
          impact: "high",
          note: "Compare headcount and total gross to last period; approve in the payroll portal.",
          status: "planned",
        },
        {
          id: "i-pay-2",
          title: "Payroll checklist and backup processor",
          category: "training",
          effort: "low",
          impact: "medium",
          note: "Bookkeeper trained to run one cycle; steps documented so the owner can step in.",
          status: "exploring",
        },
      ],
      wastes: [
        {
          id: "w-pay-1",
          kind: "muda_rework",
          label: "Timesheets corrected after submission",
          note: "Missing punches fixed by hand every pay period instead of caught at the source.",
        },
      ],
    },
  ],
  controls: baseFinancialControls(),
  staffComposition: { ...DEFAULT_STAFF },
  crimeFraudStats: DEFAULT_FRAUD_STATS,
  scenarios: baseFraudScenarios(DEFAULT_FRAUD_STATS.source, {
    keyPersonTitle: "AR lead leaves with sole billing knowledge",
    keyPersonDesc:
      "Sam (sole expert on customer billing) resigns with 2 weeks notice. Invoicing stalls.",
    knowledgeId: "k1",
  }),
  roleTemplates: {
    Owner: [
      "approve_writeoffs",
      "approve_vendor",
      "approve_payroll",
      "bank_reconcile",
      "view_reports_only",
    ],
    "Operations Manager": [
      "post_payments",
      "prepare_deposit",
      "create_vendor",
      "release_payment",
      "enter_payroll",
      "approve_vendor",
      "view_reports_only",
    ],
    "Sales Lead": ["view_reports_only"],
    "Admin / AR": [
      "collect_cash",
      "post_payments",
      "prepare_deposit",
      "post_adjustments",
      "view_reports_only",
    ],
    "AP Clerk": ["create_vendor", "release_payment", "view_reports_only"],
    Bookkeeper: [
      "post_payments",
      "bank_reconcile",
      "post_adjustments",
      "approve_writeoffs",
      "view_reports_only",
    ],
  },
};
