import type { IndustryTemplate } from "./types";
import {
  baseFinancialControls,
  baseFraudScenarios,
  DEFAULT_FRAUD_STATS,
  DEFAULT_STAFF,
} from "./shared-controls";

export const generalTemplate: IndustryTemplate = {
  id: "general",
  businessName: "Main Street Business Co.",
  people: [
    { id: "p1", name: "Alex Owner", role: "Owner", active: true, tenureYears: 10 },
    { id: "p2", name: "Maya Chen", role: "Operations Manager", active: true, tenureYears: 6 },
    { id: "p3", name: "Jordan Blake", role: "Sales Lead", active: true, tenureYears: 4 },
    { id: "p4", name: "Sam Ortiz", role: "Admin / AR", active: true, tenureYears: 3 },
    { id: "p5", name: "Riley Kim", role: "AP Clerk", active: true, tenureYears: 2 },
    { id: "p6", name: "Chris Patel", role: "Bookkeeper", active: true, tenureYears: 3 },
  ],
  knowledge: [
    {
      id: "k1",
      name: "Customer billing workflow",
      description: "Invoicing, payment terms, dunning process.",
      criticality: "critical",
      category: "process",
      linkedProcessIds: ["proc-billing"],
    },
    {
      id: "k2",
      name: "Daily deposit & reconciliation",
      description: "Cash/check deposits, bank rec, merchant batches.",
      criticality: "critical",
      category: "process",
      linkedProcessIds: ["proc-cash"],
    },
    {
      id: "k3",
      name: "ERP / accounting admin",
      description: "Chart of accounts, user roles, report setup.",
      criticality: "critical",
      category: "system",
      linkedProcessIds: ["proc-billing", "proc-ap"],
    },
    {
      id: "k4",
      name: "Vendor master & onboarding",
      description: "New vendor approval, payment methods.",
      criticality: "important",
      category: "vendor",
      linkedProcessIds: ["proc-ap"],
    },
    {
      id: "k5",
      name: "Sales pipeline & quoting",
      description: "Quote approval, discount authority.",
      criticality: "important",
      category: "process",
      linkedProcessIds: ["proc-sales"],
    },
    {
      id: "k6",
      name: "Adjustment / credit authority",
      description: "Who can issue credits and write off balances.",
      criticality: "critical",
      category: "compliance",
      linkedProcessIds: ["proc-ar"],
    },
  ],
  relations: [
    { personId: "p4", knowledgeId: "k1", level: "expert" },
    { personId: "p6", knowledgeId: "k1", level: "basic" },
    { personId: "p4", knowledgeId: "k2", level: "expert" },
    { personId: "p2", knowledgeId: "k2", level: "proficient" },
    { personId: "p2", knowledgeId: "k3", level: "expert" },
    { personId: "p5", knowledgeId: "k4", level: "expert" },
    { personId: "p3", knowledgeId: "k5", level: "expert" },
    { personId: "p6", knowledgeId: "k6", level: "expert" },
    { personId: "p2", knowledgeId: "k6", level: "proficient" },
  ],
  processes: [
    {
      id: "proc-sales",
      name: "Sales & quoting",
      layer: "process",
      description: "Leads, quotes, order intake.",
      dependencies: [],
      controlIds: [],
      stage: 0,
      ownerPersonIds: ["p3"],
    },
    {
      id: "proc-billing",
      name: "Billing & invoicing",
      layer: "process",
      description: "Invoice generation, delivery, revenue recognition.",
      dependencies: ["proc-sales"],
      controlIds: ["c-sod-billing"],
      stage: 1,
      ownerPersonIds: ["p4"],
      risks: [
        {
          id: "r-bill-1",
          title: "Billing SPOF",
          kind: "continuity",
          severity: 4,
          likelihood: 3,
          note: "Admin/AR sole billing expert.",
          linkedKnowledgeId: "k1",
          linkedScenarioId: "sc-key-person-leaves",
        },
      ],
    },
    {
      id: "proc-cash",
      name: "Cash handling & deposits",
      layer: "process",
      description: "Customer payments, deposits, reconciliation.",
      dependencies: [],
      controlIds: ["c-cash", "c-sod-cash"],
      stage: 2,
      ownerPersonIds: ["p4"],
      risks: [
        {
          id: "r-cash-1",
          title: "Posting + recon not segregated",
          kind: "fraud",
          severity: 5,
          likelihood: 4,
          note: "Classic SMB embezzlement path.",
          linkedControlId: "c-sod-cash",
          linkedScenarioId: "sc-cash-sod-failure",
        },
      ],
    },
    {
      id: "proc-ap",
      name: "Accounts payable",
      layer: "process",
      description: "Vendor invoices and payments.",
      dependencies: [],
      controlIds: ["c-ap", "c-sod-ap"],
      stage: 3,
      ownerPersonIds: ["p5", "p2"],
      risks: [
        {
          id: "r-ap-1",
          title: "Vendor setup + payment same person",
          kind: "fraud",
          severity: 5,
          likelihood: 3,
          note: "Fictitious vendor path.",
          linkedControlId: "c-sod-ap",
          linkedScenarioId: "sc-vendor-fraud",
        },
      ],
    },
    {
      id: "proc-ar",
      name: "Collections & credits",
      layer: "process",
      description: "A/R, credits, write-offs.",
      dependencies: ["proc-billing"],
      controlIds: ["c-ar", "c-sod-ar"],
      stage: 3,
      ownerPersonIds: ["p4", "p6"],
      risks: [
        {
          id: "r-ar-1",
          title: "Undocumented credits",
          kind: "fraud",
          severity: 4,
          likelihood: 3,
          note: "Bookkeeper posts credits without approval.",
          linkedKnowledgeId: "k6",
          linkedScenarioId: "sc-writeoff-abuse",
        },
      ],
    },
    {
      id: "proc-payroll",
      name: "Payroll",
      layer: "process",
      description: "Payroll processing and approval.",
      dependencies: [],
      controlIds: ["c-payroll"],
      stage: 4,
      ownerPersonIds: ["p2", "p1"],
    },
  ],
  controls: baseFinancialControls(),
  staffComposition: { ...DEFAULT_STAFF },
  crimeFraudStats: DEFAULT_FRAUD_STATS,
  scenarios: baseFraudScenarios(DEFAULT_FRAUD_STATS.source, {
    keyPersonTitle: "AR lead leaves with sole billing knowledge",
    keyPersonDesc:
      "Sam (sole expert on customer billing) resigns with 2 weeks notice. Invoicing stalls.",
    knowledgeId: "k1",
  }),
  roleTemplates: {
    Owner: [
      "approve_writeoffs",
      "approve_vendor",
      "approve_payroll",
      "bank_reconcile",
      "view_reports_only",
    ],
    "Operations Manager": [
      "post_payments",
      "prepare_deposit",
      "create_vendor",
      "release_payment",
      "enter_payroll",
      "approve_vendor",
      "view_reports_only",
    ],
    "Sales Lead": ["view_reports_only"],
    "Admin / AR": [
      "collect_cash",
      "post_payments",
      "prepare_deposit",
      "post_adjustments",
      "submit_claims",
      "view_reports_only",
    ],
    "AP Clerk": ["create_vendor", "release_payment", "view_reports_only"],
    Bookkeeper: [
      "post_payments",
      "bank_reconcile",
      "post_adjustments",
      "approve_writeoffs",
      "view_reports_only",
    ],
  },
};
