import type { ControlItem, ScenarioTemplate } from "../types";
import type { IndustryTemplate } from "./types";
import { DEFAULT_FRAUD_STATS, DEFAULT_STAFF } from "./shared-controls";

/**
 * A nonprofit of 5 to 40 people: an executive director who reports to a
 * volunteer board, a finance and operations manager who keeps the books,
 * development, grants and program staff.
 *
 * A nonprofit has no owner. Nobody here is the person who "cannot steal from
 * themselves": the executive director's own conflicts count, and the check on
 * the executive director is the board, usually through its treasurer. The
 * controls are therefore worded for the executive director and the treasurer,
 * not an owner, while keeping the ids the conflict rules link to.
 *
 * The schemes follow those in the case library's nonprofit cases (see
 * evidence/cases.ts): a bookkeeper writing checks to herself, a finance
 * director moving money to himself labelled as a vendor, organization cards
 * run up at casinos, invented invoices from a company the fiscal officer
 * owned, and an executive director spending agency money on herself. Skimmed
 * donations and restricted gifts spent on something else are named as the
 * documented patterns they are; no figure below is a measured rate.
 */
const nonprofitControls: ControlItem[] = [
  {
    id: "c-cash",
    name: "Donation handling control",
    description:
      "Separate who opens the mail and handles event cash from who records gifts and who reconciles the bank.",
    duties: ["custody", "recording", "reconciliation"],
    segregated: false,
    compensatingControls: ["Treasurer reads the bank statement monthly"],
    residualRiskAccepted: false,
  },
  {
    id: "c-sod-cash",
    name: "SoD: gift posting vs reconciliation",
    description: "The finance manager posts receipts and reconciles the bank.",
    duties: ["recording", "reconciliation"],
    segregated: false,
    compensatingControls: ["Treasurer reviews the reconciliation quarterly"],
    residualRiskAccepted: true,
  },
  {
    id: "c-sod-billing",
    name: "SoD: pledge and receivable write-offs",
    description: "Pledges and grant receivables can be written off without a second approval.",
    duties: ["authorization", "recording"],
    segregated: false,
    compensatingControls: ["Write-off list to the executive director monthly"],
    residualRiskAccepted: false,
  },
  {
    id: "c-sod-ap",
    name: "SoD: vendor setup vs payment",
    description: "The finance manager can add vendors and release payments.",
    duties: ["authorization", "custody"],
    segregated: false,
    compensatingControls: ["Two signatures on payments above the amount the board set"],
    residualRiskAccepted: false,
  },
  {
    id: "c-sod-ar",
    name: "SoD: pledge write-offs",
    description: "Pledge write-offs approved by the executive director, entered by finance.",
    duties: ["authorization", "recording"],
    segregated: true,
    compensatingControls: [],
    residualRiskAccepted: false,
  },
  {
    id: "c-ap",
    name: "Bill approval",
    description:
      "The program or department head approves each bill against the budget before it is paid.",
    duties: ["review", "authorization"],
    segregated: true,
    compensatingControls: [],
    residualRiskAccepted: false,
  },
  {
    id: "c-ar",
    name: "Pledge and grant receivable review",
    description: "Development and finance review open pledges and grant draws monthly.",
    duties: ["review"],
    segregated: true,
    compensatingControls: [],
    residualRiskAccepted: false,
  },
  {
    id: "c-payroll",
    name: "Payroll approval",
    description:
      "The executive director approves each payroll; the board approves the executive director's pay.",
    duties: ["authorization"],
    segregated: true,
    compensatingControls: [],
    residualRiskAccepted: false,
  },
  {
    id: "c-gift-log",
    name: "Two-person mail opening and gift log",
    description:
      "Two people open the mail and count event cash, log every check and cash gift, and hand the log to someone who does not record gifts.",
    duties: ["custody", "recording"],
    segregated: false,
    compensatingControls: ["Finance compares the gift log with the deposit each week"],
    residualRiskAccepted: false,
  },
  {
    id: "c-restricted",
    name: "Restricted-fund tracking",
    description:
      "Every restricted gift and grant has its own fund code, and spending against each restriction is reviewed quarterly by someone who does not code the expenses.",
    duties: ["recording", "review"],
    segregated: false,
    compensatingControls: ["Treasurer reads the restricted-fund balances each quarter"],
    residualRiskAccepted: false,
  },
  {
    id: "c-cards",
    name: "Card statement review",
    description:
      "Someone other than the cardholder matches every charge to a receipt and a program or grant; the treasurer reviews the executive director's card.",
    duties: ["review"],
    segregated: false,
    compensatingControls: ["Card statements go to the executive director monthly"],
    residualRiskAccepted: false,
  },
  {
    id: "c-board-review",
    name: "Treasurer bank statement review",
    description:
      "The treasurer receives bank statements directly and reads the reconciliation, cleared checks and transfers every month.",
    duties: ["reconciliation", "review"],
    segregated: false,
    compensatingControls: ["Finance report to the board each quarter"],
    residualRiskAccepted: false,
  },
];

/*
 * Timelines and loss figures reuse the shared scenarios' illustrative model
 * inputs for the closest scheme (the cash scenario for skimming and card
 * abuse, the write-off scenario for restricted funds, vendor fraud for
 * invented vendors). They are assumptions for the model, not measurements.
 */
const nonprofitScenarios: ScenarioTemplate[] = [
  {
    id: "sc-key-person-leaves",
    title: "Grants manager leaves with sole restricted-fund knowledge",
    description:
      "The grants manager (sole expert on grant budgets and restricted funds) resigns mid-year. Funder reports and reimbursement requests fall behind and restricted balances are unclear.",
    knowledgeId: "k2",
    baseTimelineDays: { p50: 45, p95Low: 28, p95High: 75 },
    baseFinancialImpact: { expected: 16500, low: 7000, high: 38000 },
    cascadeLayers: ["knowledge", "process", "surface", "continuity"],
    mitigations: [
      {
        id: "m1",
        label: "Cross-train finance on grant reporting with a written procedure",
        effort: "medium",
        riskReduction: 0.55,
        costAnnual: 2400,
      },
      {
        id: "m2",
        label: "Record each grant's budget, restrictions and deadlines before exit",
        effort: "low",
        riskReduction: 0.35,
        costAnnual: 400,
      },
    ],
  },
  {
    id: "sc-cash-sod-failure",
    title: "Finance manager posts, pays and reconciles alone",
    description:
      "The finance manager records receipts, releases payments and reconciles the bank, and the treasurer sees summaries, not the statement.",
    controlId: "c-sod-cash",
    baseTimelineDays: { p50: 90, p95Low: 45, p95High: 210 },
    baseFinancialImpact: { expected: 28000, low: 5000, high: 95000 },
    cascadeLayers: ["control", "process", "surface", "continuity"],
    mitigations: [
      {
        id: "m4",
        label: "Treasurer reads the bank statement and reconciliation monthly",
        effort: "low",
        riskReduction: 0.5,
        costAnnual: 0,
      },
      {
        id: "m5",
        label: "Someone who releases no payments reconciles the bank",
        effort: "medium",
        riskReduction: 0.7,
        costAnnual: 0,
      },
    ],
  },
  {
    id: "sc-writeoff-abuse",
    title: "Pledges written off without a second approval",
    description:
      "A pledge paid by the donor can be written off as uncollectible and the payment kept, because nobody else approves write-offs.",
    controlId: "c-sod-billing",
    baseTimelineDays: { p50: 120, p95Low: 60, p95High: 240 },
    baseFinancialImpact: { expected: 22000, low: 4000, high: 70000 },
    cascadeLayers: ["control", "knowledge", "process", "continuity"],
    mitigations: [
      {
        id: "m7",
        label: "Executive director approves pledge write-offs above a set amount",
        effort: "low",
        riskReduction: 0.6,
        costAnnual: 0,
      },
    ],
  },
  {
    id: "sc-vendor-fraud",
    title: "Invented vendor paid on invented invoices",
    description:
      "The person who adds vendors also releases payments, so a company they control can be paid for services nobody received.",
    controlId: "c-sod-ap",
    baseTimelineDays: { p50: 100, p95Low: 50, p95High: 200 },
    baseFinancialImpact: { expected: 40000, low: 8000, high: 125000 },
    cascadeLayers: ["control", "source", "process", "continuity"],
    mitigations: [
      {
        id: "m9",
        label: "Second signer on payments above the amount the board set",
        effort: "medium",
        riskReduction: 0.75,
        costAnnual: 0,
      },
      {
        id: "m10",
        label: "Executive director approves every new vendor",
        effort: "low",
        riskReduction: 0.5,
        costAnnual: 0,
      },
    ],
  },
  {
    id: "sc-skimmed-donations",
    title: "Donation checks and event cash kept before they are logged",
    description:
      "One person opens the mail or counts event cash and also records the gifts, so a gift that never reaches the log never reaches the bank, and the donor still gets a thank-you.",
    controlId: "c-gift-log",
    knowledgeId: "k1",
    baseTimelineDays: { p50: 90, p95Low: 45, p95High: 210 },
    baseFinancialImpact: { expected: 28000, low: 5000, high: 95000 },
    cascadeLayers: ["control", "process", "surface", "continuity"],
    mitigations: [
      {
        id: "m-np-1",
        label: "Two people open the mail and count event cash, and both sign the log",
        effort: "low",
        riskReduction: 0.5,
        costAnnual: 0,
      },
      {
        id: "m-np-2",
        label: "Finance matches the donor database to deposits monthly",
        effort: "low",
        riskReduction: 0.45,
        costAnnual: 0,
      },
    ],
  },
  {
    id: "sc-restricted-diverted",
    title: "Restricted grant money spent on general operations",
    description:
      "Restricted gifts and grant funds sit in the operating account with no fund code, so they pay rent, payroll or a shortfall elsewhere, and the organization owes the funder money it no longer has.",
    controlId: "c-restricted",
    knowledgeId: "k2",
    baseTimelineDays: { p50: 120, p95Low: 60, p95High: 240 },
    baseFinancialImpact: { expected: 22000, low: 4000, high: 70000 },
    cascadeLayers: ["control", "knowledge", "process", "continuity"],
    mitigations: [
      {
        id: "m-np-3",
        label: "A fund code for every restricted gift and grant",
        effort: "low",
        riskReduction: 0.5,
        costAnnual: 0,
      },
      {
        id: "m-np-4",
        label: "Treasurer reviews restricted balances against cash each quarter",
        effort: "low",
        riskReduction: 0.45,
        costAnnual: 0,
      },
    ],
  },
  {
    id: "sc-card-abuse",
    title: "Organization cards used for personal spending",
    description:
      "Cardholders approve their own statements, and the executive director's card is reviewed by nobody, so personal travel, cash advances and purchases are booked as program costs.",
    controlId: "c-cards",
    baseTimelineDays: { p50: 90, p95Low: 45, p95High: 210 },
    baseFinancialImpact: { expected: 28000, low: 5000, high: 95000 },
    cascadeLayers: ["control", "process", "surface", "continuity"],
    mitigations: [
      {
        id: "m-np-5",
        label: "Someone other than the cardholder matches every charge to a receipt",
        effort: "low",
        riskReduction: 0.5,
        costAnnual: 0,
      },
      {
        id: "m-np-6",
        label: "Treasurer reviews the executive director's card monthly; cash advances blocked",
        effort: "low",
        riskReduction: 0.45,
        costAnnual: 0,
      },
    ],
  },
];

export const nonprofitTemplate: IndustryTemplate = {
  id: "nonprofit",
  businessName: "Riverbend Community Alliance",
  people: [
    { id: "p1", name: "Grace Okafor", role: "Executive Director", active: true, tenureYears: 12 },
    {
      id: "p2",
      name: "Martin Alvarez",
      role: "Finance & Operations Manager",
      active: true,
      tenureYears: 8,
    },
    { id: "p3", name: "Hannah Lee", role: "Development Director", active: true, tenureYears: 5 },
    { id: "p4", name: "Aisha Rahman", role: "Grants Manager", active: true, tenureYears: 4 },
    { id: "p5", name: "David Kim", role: "Program Director", active: true, tenureYears: 6 },
    { id: "p6", name: "Rosa Jimenez", role: "Office Coordinator", active: true, tenureYears: 3 },
    { id: "p7", name: "Thomas Brennan", role: "Board Treasurer", active: true, tenureYears: 2 },
    {
      id: "p8",
      name: "Lena Fischer",
      role: "Volunteer Coordinator",
      active: true,
      tenureYears: 2,
    },
  ],
  knowledge: [
    {
      id: "k1",
      name: "Gift processing & donor database",
      description:
        "Gift entry, online giving payouts, event revenue, and written acknowledgments donors need for gifts of $250 or more.",
      criticality: "critical",
      category: "process",
      linkedProcessIds: ["proc-cash"],
    },
    {
      id: "k2",
      name: "Grant budgets & restricted funds",
      description: "What each grant and restricted gift may pay for, by when, and what is left.",
      criticality: "critical",
      category: "compliance",
      linkedProcessIds: ["proc-grants"],
    },
    {
      id: "k3",
      name: "Month-end close & bank reconciliation",
      description: "Close checklist, bank and card reconciliations, fund balances.",
      criticality: "critical",
      category: "process",
      linkedProcessIds: ["proc-board", "proc-ap"],
    },
    {
      id: "k4",
      name: "Form 990 & audit preparation",
      description: "Schedules the auditor and the Form 990 need, and where the support is kept.",
      criticality: "important",
      category: "compliance",
      linkedProcessIds: ["proc-board"],
    },
    {
      id: "k5",
      name: "Payroll & time allocation",
      description: "Payroll runs, benefits, and time charged to each grant.",
      criticality: "important",
      category: "process",
      linkedProcessIds: ["proc-payroll"],
    },
    {
      id: "k6",
      name: "Program purchasing & participant assistance",
      description: "Supply orders, gift cards and direct assistance given to participants.",
      criticality: "important",
      category: "process",
      linkedProcessIds: ["proc-programs"],
    },
    {
      id: "k7",
      name: "Funder relationships & reimbursement requests",
      description: "Program officers, reporting calendars, and how each funder wants a draw.",
      criticality: "important",
      category: "tribal",
      linkedProcessIds: ["proc-grants", "proc-ar"],
    },
  ],
  relations: [
    { personId: "p3", knowledgeId: "k1", level: "expert" },
    { personId: "p6", knowledgeId: "k1", level: "proficient" },
    { personId: "p4", knowledgeId: "k2", level: "expert" },
    { personId: "p2", knowledgeId: "k2", level: "basic" },
    { personId: "p2", knowledgeId: "k3", level: "expert" },
    { personId: "p7", knowledgeId: "k3", level: "aware" },
    { personId: "p2", knowledgeId: "k4", level: "expert" },
    { personId: "p1", knowledgeId: "k4", level: "proficient" },
    { personId: "p2", knowledgeId: "k5", level: "expert" },
    { personId: "p5", knowledgeId: "k6", level: "expert" },
    { personId: "p4", knowledgeId: "k7", level: "expert" },
    { personId: "p1", knowledgeId: "k7", level: "proficient" },
  ],
  processes: [
    {
      id: "proc-cash",
      name: "Donations & gift processing",
      layer: "process",
      description: "Mail and event cash, online gifts, deposits, donor acknowledgments.",
      dependencies: [],
      controlIds: ["c-cash", "c-gift-log"],
      stage: 0,
      ownerPersonIds: ["p6", "p3"],
      inputs: ["Checks and cash in the mail", "Event receipts", "Online giving payouts"],
      outputs: ["Deposits", "Gifts in the donor database", "Acknowledgment letters"],
      risks: [
        {
          id: "r-gift-1",
          title: "Checks and event cash handled and recorded by one person",
          kind: "fraud",
          severity: 5,
          likelihood: 3,
          note: "A gift kept before it is logged leaves no record; the donor sees a thank-you and nobody else sees a gap.",
          linkedControlId: "c-gift-log",
          linkedScenarioId: "sc-skimmed-donations",
          linkedKnowledgeId: "k1",
        },
        {
          id: "r-gift-2",
          title: "Acknowledgments late or missing",
          kind: "compliance",
          severity: 3,
          likelihood: 3,
          note: "A donor cannot deduct a single gift of $250 or more without the organization's written acknowledgment.",
        },
      ],
      ideas: [
        {
          id: "i-gift-1",
          title: "Two people open the mail and sign the gift log",
          category: "control",
          effort: "low",
          impact: "high",
          note: "Checks are endorsed for deposit at opening; the log goes to finance, not development.",
          status: "planned",
        },
        {
          id: "i-gift-2",
          title: "Donor database reconciled to deposits monthly",
          category: "control",
          effort: "low",
          impact: "high",
          note: "Someone who neither opens mail nor enters gifts matches the two totals.",
          status: "exploring",
        },
      ],
      wastes: [
        {
          id: "w-gift-1",
          kind: "muda_overprocessing",
          label: "Gifts keyed twice",
          note: "Every gift is typed into the donor database and again into the accounting system.",
        },
      ],
    },
    {
      id: "proc-grants",
      name: "Grants & restricted funds",
      layer: "process",
      description: "Grant budgets, restricted gifts, expense coding, funder reports and draws.",
      dependencies: ["proc-cash"],
      controlIds: ["c-restricted"],
      stage: 1,
      ownerPersonIds: ["p4", "p2"],
      inputs: ["Grant agreements", "Restricted gift letters", "Expense detail"],
      outputs: ["Funder reports", "Reimbursement requests", "Restricted fund balances"],
      risks: [
        {
          id: "r-grant-1",
          title: "Restricted money spent on something else",
          kind: "compliance",
          severity: 5,
          likelihood: 3,
          note: "Without a fund code, restricted cash pays general bills and the organization owes the funder what it spent.",
          linkedControlId: "c-restricted",
          linkedScenarioId: "sc-restricted-diverted",
          linkedKnowledgeId: "k2",
        },
        {
          id: "r-grant-2",
          title: "Costs charged to a grant that it does not allow",
          kind: "compliance",
          severity: 4,
          likelihood: 3,
          note: "Federal awards follow cost principles; a disallowed cost is repaid, and a reimbursement request for costs not incurred is a false claim.",
        },
      ],
      ideas: [
        {
          id: "i-grant-1",
          title: "A fund code for every restricted gift and grant",
          category: "control",
          effort: "low",
          impact: "high",
          note: "Expenses are coded when the bill is approved, not reallocated at year end.",
          status: "planned",
        },
        {
          id: "i-grant-2",
          title: "Grant calendar shared with finance",
          category: "training",
          effort: "low",
          impact: "medium",
          note: "Budgets, deadlines and allowed costs for each grant in one place a backup can read.",
          status: "exploring",
        },
      ],
      wastes: [
        {
          id: "w-grant-1",
          kind: "muda_rework",
          label: "Time sheets reallocated to grants after the fact",
          note: "Staff time is moved between grants at report time instead of recorded when worked.",
        },
      ],
    },
    {
      id: "proc-programs",
      name: "Program delivery & expenses",
      layer: "process",
      description: "Program supplies, participant assistance, gift cards, vehicle and site costs.",
      dependencies: ["proc-grants"],
      controlIds: [],
      stage: 1,
      ownerPersonIds: ["p5"],
      inputs: ["Program budget", "Participant needs", "Supply orders"],
      outputs: ["Services delivered", "Assistance log"],
      risks: [
        {
          id: "r-prog-1",
          title: "Program director orders and receives alone",
          kind: "fraud",
          severity: 3,
          likelihood: 3,
          note: "Supplies and gift cards bought for participants can go elsewhere with nobody else confirming receipt.",
        },
        {
          id: "r-prog-2",
          title: "Gift cards and direct assistance not logged",
          kind: "control",
          severity: 4,
          likelihood: 3,
          note: "Cards bought in bulk and handed out without a signed log cannot be traced to a participant.",
          linkedKnowledgeId: "k6",
        },
      ],
      ideas: [
        {
          id: "i-prog-1",
          title: "Gift-card log with participant signatures",
          category: "control",
          effort: "low",
          impact: "high",
          note: "Cards kept locked, numbered, and counted against the log monthly by someone else.",
          status: "planned",
        },
        {
          id: "i-prog-2",
          title: "Office coordinator receives program deliveries",
          category: "policy",
          effort: "low",
          impact: "medium",
          note: "The person who orders does not sign for the delivery.",
          status: "backlog",
        },
      ],
      wastes: [
        {
          id: "w-prog-1",
          kind: "muda_motion",
          label: "Store runs for single items",
          note: "Program staff buy supplies one trip at a time on a card instead of from a standing order.",
        },
      ],
    },
    {
      id: "proc-ar",
      name: "Pledges & grant receivables",
      layer: "process",
      description: "Multi-year pledges, grant draws, write-offs of uncollectible pledges.",
      dependencies: ["proc-cash", "proc-grants"],
      controlIds: ["c-ar", "c-sod-ar"],
      stage: 2,
      ownerPersonIds: ["p3", "p4"],
      inputs: ["Pledge agreements", "Grant payment schedules", "Aging report"],
      outputs: ["Collected pledges", "Approved write-offs"],
      risks: [
        {
          id: "r-ar-1",
          title: "Pledges written off without a second approval",
          kind: "fraud",
          severity: 4,
          likelihood: 2,
          note: "A paid pledge written off as uncollectible hides a payment kept.",
          linkedScenarioId: "sc-writeoff-abuse",
        },
        {
          id: "r-ar-2",
          title: "Grant draws requested late",
          kind: "revenue",
          severity: 3,
          likelihood: 4,
          note: "Reimbursement grants pay after the money is spent; late draws leave the organization short of cash.",
          linkedKnowledgeId: "k7",
        },
      ],
      ideas: [
        {
          id: "i-ar-1",
          title: "Executive director approves pledge write-offs",
          category: "control",
          effort: "low",
          impact: "high",
          note: "Each write-off carries the donor's reason and the executive director's approval.",
          status: "planned",
        },
        {
          id: "i-ar-2",
          title: "Monthly draw schedule for reimbursement grants",
          category: "policy",
          effort: "low",
          impact: "medium",
          note: "Draws requested on a fixed day each month from the coded expenses.",
          status: "backlog",
        },
      ],
      wastes: [
        {
          id: "w-ar-1",
          kind: "mura",
          label: "Pledge reminders sent in a year-end rush",
          note: "Reminders go out once in December instead of on each pledge's schedule.",
        },
      ],
    },
    {
      id: "proc-ap",
      name: "Vendor payments & organization cards",
      layer: "process",
      description: "Vendor bills, check signing, ACH, organization credit cards, reimbursements.",
      dependencies: ["proc-programs"],
      controlIds: ["c-ap", "c-sod-ap", "c-cards"],
      stage: 2,
      ownerPersonIds: ["p2", "p1"],
      inputs: ["Approved bills", "Card statements", "Reimbursement requests"],
      outputs: ["Payments", "Coded card charges"],
      risks: [
        {
          id: "r-ap-1",
          title: "Finance manager adds vendors and releases payments",
          kind: "fraud",
          severity: 5,
          likelihood: 3,
          note: "Invented invoices from a company the insider controls are paid like any other bill.",
          linkedControlId: "c-sod-ap",
          linkedScenarioId: "sc-vendor-fraud",
        },
        {
          id: "r-ap-2",
          title: "Cardholders approve their own statements",
          kind: "fraud",
          severity: 4,
          likelihood: 4,
          note: "Personal spending coded as program cost; the executive director's card has no reviewer at all.",
          linkedControlId: "c-cards",
          linkedScenarioId: "sc-card-abuse",
        },
      ],
      ideas: [
        {
          id: "i-ap-1",
          title: "Two signers above the amount the board set",
          category: "control",
          effort: "low",
          impact: "high",
          note: "Bank-enforced second approval by the executive director or treasurer on larger payments.",
          status: "planned",
        },
        {
          id: "i-ap-2",
          title: "Card program with receipt capture and cash advances off",
          category: "tech",
          effort: "low",
          impact: "medium",
          note: "Each charge needs a receipt photo and a program code before the statement closes.",
          status: "exploring",
        },
      ],
      wastes: [
        {
          id: "w-ap-1",
          kind: "muda_waiting",
          label: "Checks wait for a board signer",
          note: "Payments sit until a volunteer signer comes in, and vendors call about late payments.",
        },
      ],
    },
    {
      id: "proc-payroll",
      name: "Payroll & time",
      layer: "process",
      description: "Payroll, benefits, time charged to grants, executive pay.",
      dependencies: [],
      controlIds: ["c-payroll"],
      stage: 3,
      ownerPersonIds: ["p2", "p1"],
      inputs: ["Time sheets", "Grant time allocations", "Board-approved salaries"],
      outputs: ["Payroll", "Labor cost by grant"],
      risks: [
        {
          id: "r-pay-1",
          title: "Finance manager enters payroll and pays it",
          kind: "fraud",
          severity: 4,
          likelihood: 2,
          note: "A raise, extra check or former employee added by the person running payroll reaches the bank unseen.",
          linkedControlId: "c-payroll",
        },
        {
          id: "r-pay-2",
          title: "Executive pay set without board review",
          kind: "compliance",
          severity: 4,
          likelihood: 2,
          note: "Form 990 asks whether independent persons reviewed and documented top management pay.",
        },
      ],
      ideas: [
        {
          id: "i-pay-1",
          title: "Executive director reads the payroll register each run",
          category: "control",
          effort: "low",
          impact: "high",
          note: "Headcount, rates and bank changes compared with the prior run before release.",
          status: "planned",
        },
        {
          id: "i-pay-2",
          title: "Board compensation committee approves executive pay yearly",
          category: "policy",
          effort: "low",
          impact: "medium",
          note: "With comparable pay data and minutes recording the decision.",
          status: "exploring",
        },
      ],
      wastes: [
        {
          id: "w-pay-1",
          kind: "muda_rework",
          label: "Grant time allocations fixed after payroll",
          note: "Payroll is split across grants from memory, then corrected when funders ask.",
        },
      ],
    },
    {
      id: "proc-board",
      name: "Board & treasurer oversight",
      layer: "process",
      description: "Bank reconciliation review, finance committee, audit, Form 990.",
      dependencies: ["proc-ap", "proc-payroll"],
      controlIds: ["c-sod-cash", "c-board-review"],
      stage: 4,
      ownerPersonIds: ["p7", "p1"],
      inputs: ["Bank statements", "Reconciliations", "Financial statements"],
      outputs: ["Treasurer's review", "Board minutes", "Audit and Form 990"],
      risks: [
        {
          id: "r-board-1",
          title: "Board sees reports prepared by the person it should check",
          kind: "control",
          severity: 5,
          likelihood: 3,
          note: "Summaries from finance hide what the bank statement would show; the treasurer never sees the statement itself.",
          linkedControlId: "c-board-review",
          linkedScenarioId: "sc-cash-sod-failure",
        },
        {
          id: "r-board-2",
          title: "Close and audit support known by one person",
          kind: "continuity",
          severity: 4,
          likelihood: 3,
          note: "Only the finance manager knows the close; the audit and Form 990 slip when they are out.",
          linkedKnowledgeId: "k3",
        },
      ],
      ideas: [
        {
          id: "i-board-1",
          title: "Bank sends statements to the treasurer directly",
          category: "control",
          effort: "low",
          impact: "high",
          note: "Read-only online access for the treasurer, who initials the reconciliation monthly.",
          status: "planned",
        },
        {
          id: "i-board-2",
          title: "Written close checklist a backup can follow",
          category: "training",
          effort: "medium",
          impact: "high",
          note: "Each step, its report and where the support is filed.",
          status: "backlog",
        },
      ],
      wastes: [
        {
          id: "w-board-1",
          kind: "muda_waiting",
          label: "Board packet assembled the night before",
          note: "Financials arrive too late for the treasurer to ask questions before the meeting.",
        },
      ],
    },
  ],
  controls: nonprofitControls,
  staffComposition: { ...DEFAULT_STAFF, teamSize: 8, avgTenureYears: 5.3, segregationScore: 34 },
  crimeFraudStats: DEFAULT_FRAUD_STATS,
  scenarios: nonprofitScenarios,
  roleTemplates: {
    "Executive Director": [
      "approve_vendor",
      "approve_payroll",
      "approve_writeoffs",
      "sign_checks",
      "view_reports_only",
    ],
    "Finance & Operations Manager": [
      "post_payments",
      "prepare_deposit",
      "enter_invoices",
      "create_vendor",
      "release_payment",
      "enter_payroll",
      "bank_reconcile",
      "post_journal_entries",
      "view_reports_only",
    ],
    "Development Director": [
      "collect_cash",
      "post_payments",
      "edit_patient_master",
      "view_reports_only",
    ],
    "Grants Manager": ["submit_claims", "post_journal_entries", "view_reports_only"],
    "Program Director": [
      "order_supplies",
      "receive_goods",
      "approve_invoices",
      "view_reports_only",
    ],
    "Office Coordinator": ["collect_cash", "prepare_deposit", "view_reports_only"],
    "Board Treasurer": ["sign_checks", "approve_payroll", "view_reports_only"],
    "Volunteer Coordinator": ["view_reports_only"],
  },
};
