import type { IndustryTemplate } from "./types";
import {
  baseFinancialControls,
  baseFraudScenarios,
  DEFAULT_FRAUD_STATS,
  DEFAULT_STAFF,
} from "./shared-controls";

const fraudStats = {
  ...DEFAULT_FRAUD_STATS,
  industryEmbezzlementRate: 0.16,
  source:
    "Illustrative professional services firm fraud patterns (billing, trust/IOLTA, expense abuse). Educational demo only.",
};

export const professionalServicesTemplate: IndustryTemplate = {
  id: "professional_services",
  businessName: "Northgate Advisory Group",
  people: [
    { id: "p1", name: "Dr. Elena Vargas", role: "Managing Partner", active: true, tenureYears: 14 },
    { id: "p2", name: "Maya Chen", role: "Office Manager", active: true, tenureYears: 8 },
    { id: "p3", name: "Jordan Blake", role: "Senior Consultant", active: true, tenureYears: 6 },
    { id: "p4", name: "Sam Ortiz", role: "Billing Coordinator", active: true, tenureYears: 4 },
    { id: "p5", name: "Riley Kim", role: "Admin Assistant", active: true, tenureYears: 2 },
    { id: "p6", name: "Chris Patel", role: "Bookkeeper", active: true, tenureYears: 3 },
  ],
  knowledge: [
    {
      id: "k1",
      name: "Client billing & WIP rules",
      description: "Time entry, billing rates, write-down policies.",
      criticality: "critical",
      category: "process",
      linkedProcessIds: ["proc-billing"],
    },
    {
      id: "k2",
      name: "Trust / retainer account handling",
      description: "Client fund segregation, disbursement rules.",
      criticality: "critical",
      category: "compliance",
      linkedProcessIds: ["proc-trust"],
    },
    {
      id: "k3",
      name: "Engagement letter workflow",
      description: "Scope, fee caps, change-order approvals.",
      criticality: "important",
      category: "compliance",
      linkedProcessIds: ["proc-engagement"],
    },
    {
      id: "k4",
      name: "Expense report approval",
      description: "Receipt policy, partner pre-approval thresholds.",
      criticality: "important",
      category: "process",
      linkedProcessIds: ["proc-ap"],
    },
    {
      id: "k5",
      name: "Collections & dunning",
      description: "A/R follow-up, payment plans, write-off rules.",
      criticality: "critical",
      category: "process",
      linkedProcessIds: ["proc-ar"],
    },
    {
      id: "k6",
      name: "Payroll & bonus exceptions",
      description: "Partner draws, bonus calculations, OT edge cases.",
      criticality: "important",
      category: "process",
      linkedProcessIds: ["proc-payroll"],
    },
  ],
  relations: [
    { personId: "p4", knowledgeId: "k1", level: "expert" },
    { personId: "p6", knowledgeId: "k1", level: "basic" },
    { personId: "p2", knowledgeId: "k2", level: "expert" },
    { personId: "p6", knowledgeId: "k2", level: "aware" },
    { personId: "p2", knowledgeId: "k3", level: "expert" },
    { personId: "p2", knowledgeId: "k4", level: "proficient" },
    { personId: "p4", knowledgeId: "k5", level: "expert" },
    { personId: "p2", knowledgeId: "k6", level: "expert" },
    { personId: "p6", knowledgeId: "k5", level: "proficient" },
  ],
  processes: [
    {
      id: "proc-engagement",
      name: "Client engagement & delivery",
      layer: "process",
      description: "SOW, staffing, deliverable sign-off.",
      dependencies: [],
      controlIds: [],
      stage: 0,
      ownerPersonIds: ["p1", "p3"],
      risks: [
        {
          id: "r-eng-1",
          title: "Scope creep without change order",
          kind: "revenue",
          severity: 3,
          likelihood: 4,
          note: "Margin leakage when engagement letters lag delivery.",
        },
      ],
    },
    {
      id: "proc-billing",
      name: "Time, billing & invoicing",
      layer: "process",
      description: "WIP, invoice generation, client billing.",
      dependencies: ["proc-engagement"],
      controlIds: ["c-sod-billing"],
      stage: 1,
      ownerPersonIds: ["p4"],
      risks: [
        {
          id: "r-bill-1",
          title: "Billing specialist sole expert",
          kind: "continuity",
          severity: 5,
          likelihood: 3,
          note: "Sam sole expert on WIP and billing rules.",
          linkedKnowledgeId: "k1",
          linkedScenarioId: "sc-key-person-leaves",
        },
      ],
    },
    {
      id: "proc-trust",
      name: "Client trust / retainer funds",
      layer: "process",
      description: "Segregated client funds, disbursements.",
      dependencies: [],
      controlIds: ["c-cash"],
      stage: 1,
      ownerPersonIds: ["p2"],
      risks: [
        {
          id: "r-trust-1",
          title: "Trust handling tribal knowledge",
          kind: "compliance",
          severity: 5,
          likelihood: 2,
          note: "Office manager sole expert on trust rules.",
          linkedKnowledgeId: "k2",
        },
      ],
    },
    {
      id: "proc-cash",
      name: "Operating cash & bank rec",
      layer: "process",
      description: "Operating account, deposits, reconciliation.",
      dependencies: [],
      controlIds: ["c-cash", "c-sod-cash"],
      stage: 2,
      ownerPersonIds: ["p6"],
      risks: [
        {
          id: "r-cash-1",
          title: "Bookkeeper posts and reconciles alone",
          kind: "fraud",
          severity: 5,
          likelihood: 4,
          note: "Classic small-firm embezzlement path.",
          linkedControlId: "c-sod-cash",
          linkedScenarioId: "sc-cash-sod-failure",
        },
      ],
    },
    {
      id: "proc-ap",
      name: "Vendor & expense AP",
      layer: "process",
      description: "Vendor bills, expense reports, reimbursements.",
      dependencies: [],
      controlIds: ["c-ap", "c-sod-ap"],
      stage: 3,
      ownerPersonIds: ["p2", "p6"],
      risks: [
        {
          id: "r-ap-1",
          title: "Vendor setup + payment concentrated",
          kind: "fraud",
          severity: 5,
          likelihood: 3,
          note: "Fictitious vendor risk.",
          linkedControlId: "c-sod-ap",
          linkedScenarioId: "sc-vendor-fraud",
        },
      ],
    },
    {
      id: "proc-ar",
      name: "Collections & write-offs",
      layer: "process",
      description: "Client A/R, payment plans, write-offs.",
      dependencies: ["proc-billing"],
      controlIds: ["c-ar", "c-sod-ar"],
      stage: 3,
      ownerPersonIds: ["p4", "p6"],
      risks: [
        {
          id: "r-ar-1",
          title: "Write-offs without partner approval",
          kind: "fraud",
          severity: 4,
          likelihood: 3,
          note: "Billing can write off client balances.",
          linkedScenarioId: "sc-writeoff-abuse",
        },
      ],
    },
    {
      id: "proc-payroll",
      name: "Payroll & partner draws",
      layer: "process",
      description: "Staff payroll, partner distributions.",
      dependencies: [],
      controlIds: ["c-payroll"],
      stage: 4,
      ownerPersonIds: ["p2", "p1"],
    },
  ],
  controls: baseFinancialControls(),
  staffComposition: { ...DEFAULT_STAFF, segregationScore: 38 },
  crimeFraudStats: fraudStats,
  scenarios: baseFraudScenarios(fraudStats.source, {
    keyPersonTitle: "Billing coordinator leaves with sole WIP knowledge",
    keyPersonDesc:
      "Sam (sole expert on client billing and WIP rules) resigns. Invoices stall and write-offs pile up.",
    knowledgeId: "k1",
    billingLabel: "Client write-offs without partner approval",
  }),
  roleTemplates: {
    "Managing Partner": [
      "approve_writeoffs",
      "approve_vendor",
      "approve_payroll",
      "bank_reconcile",
      "view_reports_only",
    ],
    "Office Manager": [
      "post_payments",
      "prepare_deposit",
      "create_vendor",
      "release_payment",
      "enter_payroll",
      "approve_vendor",
      "view_reports_only",
    ],
    "Senior Consultant": ["view_reports_only"],
    "Billing Coordinator": [
      "post_adjustments",
      "post_payments",
      "approve_writeoffs",
      "submit_claims",
      "view_reports_only",
    ],
    "Admin Assistant": ["view_reports_only"],
    Bookkeeper: [
      "post_payments",
      "prepare_deposit",
      "bank_reconcile",
      "post_adjustments",
      "create_vendor",
      "release_payment",
      "view_reports_only",
    ],
  },
};
