import type { IndustryTemplate } from "./types";
import {
  baseFinancialControls,
  baseFraudScenarios,
  DEFAULT_FRAUD_STATS,
  DEFAULT_STAFF,
} from "./shared-controls";

const fraudStats = {
  ...DEFAULT_FRAUD_STATS,
  industryEmbezzlementRate: 0.16,
  source:
    "Illustrative professional services firm fraud patterns (billing, trust/IOLTA, expense abuse). Educational demo only.",
};

export const professionalServicesTemplate: IndustryTemplate = {
  id: "professional_services",
  businessName: "Northgate Advisory Group",
  people: [
    { id: "p1", name: "Dr. Elena Vargas", role: "Managing Partner", active: true, tenureYears: 14 },
    { id: "p2", name: "Maya Chen", role: "Office Manager", active: true, tenureYears: 8 },
    { id: "p3", name: "Jordan Blake", role: "Senior Consultant", active: true, tenureYears: 6 },
    { id: "p4", name: "Sam Ortiz", role: "Billing Coordinator", active: true, tenureYears: 4 },
    { id: "p5", name: "Riley Kim", role: "Admin Assistant", active: true, tenureYears: 2 },
    { id: "p6", name: "Chris Patel", role: "Bookkeeper", active: true, tenureYears: 3 },
  ],
  knowledge: [
    {
      id: "k1",
      name: "Client billing & WIP rules",
      description: "Time entry, billing rates, write-down policies.",
      criticality: "critical",
      category: "process",
      linkedProcessIds: ["proc-billing"],
    },
    {
      id: "k2",
      name: "Trust / retainer account handling",
      description: "Client fund segregation, disbursement rules.",
      criticality: "critical",
      category: "compliance",
      linkedProcessIds: ["proc-trust"],
    },
    {
      id: "k3",
      name: "Engagement letter workflow",
      description: "Scope, fee caps, change-order approvals.",
      criticality: "important",
      category: "compliance",
      linkedProcessIds: ["proc-engagement"],
    },
    {
      id: "k4",
      name: "Expense report approval",
      description: "Receipt policy, partner pre-approval thresholds.",
      criticality: "important",
      category: "process",
      linkedProcessIds: ["proc-ap"],
    },
    {
      id: "k5",
      name: "Collections & dunning",
      description: "A/R follow-up, payment plans, write-off rules.",
      criticality: "critical",
      category: "process",
      linkedProcessIds: ["proc-ar"],
    },
    {
      id: "k6",
      name: "Payroll & bonus exceptions",
      description: "Partner draws, bonus calculations, OT edge cases.",
      criticality: "important",
      category: "process",
      linkedProcessIds: ["proc-payroll"],
    },
  ],
  relations: [
    { personId: "p4", knowledgeId: "k1", level: "expert" },
    { personId: "p6", knowledgeId: "k1", level: "basic" },
    { personId: "p2", knowledgeId: "k2", level: "expert" },
    { personId: "p6", knowledgeId: "k2", level: "aware" },
    { personId: "p2", knowledgeId: "k3", level: "expert" },
    { personId: "p2", knowledgeId: "k4", level: "proficient" },
    { personId: "p4", knowledgeId: "k5", level: "expert" },
    { personId: "p2", knowledgeId: "k6", level: "expert" },
    { personId: "p6", knowledgeId: "k5", level: "proficient" },
  ],
  processes: [
    {
      id: "proc-engagement",
      name: "Client engagement & delivery",
      layer: "process",
      description: "SOW, staffing, deliverable sign-off.",
      dependencies: [],
      controlIds: [],
      stage: 0,
      ownerPersonIds: ["p1", "p3"],
      inputs: ["Signed engagement letter", "Staffing plan", "Client kickoff notes"],
      outputs: ["Approved deliverables", "Client sign-off"],
      risks: [
        {
          id: "r-eng-1",
          title: "Scope creep without change order",
          kind: "revenue",
          severity: 3,
          likelihood: 4,
          note: "Margin leakage when engagement letters lag delivery.",
        },
        {
          id: "r-eng-2",
          title: "Work starts before letter is signed",
          kind: "compliance",
          severity: 4,
          likelihood: 3,
          note: "Unsigned scope leaves fee disputes and liability exposure if the client pushes back.",
          linkedKnowledgeId: "k3",
        },
      ],
      ideas: [
        {
          id: "i-eng-1",
          title: "No time entry until engagement letter is countersigned",
          category: "policy",
          effort: "low",
          impact: "high",
          note: "Practice management system blocks the matter code until the signed letter is attached.",
          status: "planned",
        },
        {
          id: "i-eng-2",
          title: "Change-order template with partner e-sign",
          category: "lean",
          effort: "low",
          impact: "medium",
          note: "One-page addendum sent from the project tool; keeps out-of-scope hours billable.",
          status: "exploring",
        },
      ],
      wastes: [
        {
          id: "w-eng-1",
          kind: "muda_waiting",
          label: "Consultants idle waiting on client data",
          note: "Kickoff checklists are not sent early enough, so billable weeks slip.",
        },
      ],
    },
    {
      id: "proc-billing",
      name: "Time, billing & invoicing",
      layer: "process",
      description: "WIP, invoice generation, client billing.",
      dependencies: ["proc-engagement"],
      controlIds: ["c-sod-billing"],
      stage: 1,
      ownerPersonIds: ["p4"],
      inputs: ["Approved timesheets", "Rate card", "Engagement terms"],
      outputs: ["Client invoices", "WIP report"],
      risks: [
        {
          id: "r-bill-1",
          title: "Billing specialist sole expert",
          kind: "continuity",
          severity: 5,
          likelihood: 3,
          note: "Sam sole expert on WIP and billing rules.",
          linkedKnowledgeId: "k1",
          linkedScenarioId: "sc-key-person-leaves",
        },
        {
          id: "r-bill-2",
          title: "Unreviewed write-downs before invoicing",
          kind: "revenue",
          severity: 3,
          likelihood: 4,
          note: "Hours trimmed off WIP at invoice time with no partner review; realization quietly drops.",
        },
      ],
      ideas: [
        {
          id: "i-bill-1",
          title: "Monthly WIP aging and realization report to partners",
          category: "control",
          effort: "low",
          impact: "high",
          note: "Shows unbilled hours over 60 days and write-down percentage by engagement.",
          status: "planned",
        },
        {
          id: "i-bill-2",
          title: "Cross-train bookkeeper on invoice run",
          category: "training",
          effort: "medium",
          impact: "high",
          note: "Chris shadows two billing cycles and documents the rate and write-down rules.",
          status: "exploring",
        },
      ],
      wastes: [
        {
          id: "w-bill-1",
          kind: "muda_rework",
          label: "Invoices re-issued after client pushback",
          note: "Late or vague time narratives cause edits and re-sends every month.",
        },
      ],
    },
    {
      id: "proc-trust",
      name: "Client trust / retainer funds",
      layer: "process",
      description: "Segregated client funds, disbursements.",
      dependencies: [],
      controlIds: ["c-cash"],
      stage: 1,
      ownerPersonIds: ["p2"],
      inputs: ["Client retainer payments", "Disbursement requests", "Engagement fee terms"],
      outputs: ["Client trust ledger", "Approved disbursements"],
      risks: [
        {
          id: "r-trust-1",
          title: "Trust handling tribal knowledge",
          kind: "compliance",
          severity: 5,
          likelihood: 2,
          note: "Office manager sole expert on trust rules.",
          linkedKnowledgeId: "k2",
        },
        {
          id: "r-trust-2",
          title: "Retainer applied to fees before earned",
          kind: "fraud",
          severity: 5,
          likelihood: 2,
          note: "One person can move client funds to operating without a matching invoice; commingling exposure.",
          linkedControlId: "c-cash",
        },
      ],
      ideas: [
        {
          id: "i-trust-1",
          title: "Monthly three-way trust reconciliation signed by partner",
          category: "control",
          effort: "low",
          impact: "high",
          note: "Bank balance, trust ledger, and client sub-ledgers must tie; managing partner signs the report.",
          status: "planned",
        },
        {
          id: "i-trust-2",
          title: "Written trust handling SOP with backup owner",
          category: "training",
          effort: "medium",
          impact: "high",
          note: "Bookkeeper trained to run one month of trust activity without Maya.",
          status: "exploring",
        },
      ],
      wastes: [
        {
          id: "w-trust-1",
          kind: "muda_overprocessing",
          label: "Trust ledger kept in spreadsheet and accounting system",
          note: "Every retainer movement is keyed twice and reconciled by hand.",
        },
      ],
    },
    {
      id: "proc-cash",
      name: "Operating cash & bank rec",
      layer: "process",
      description: "Operating account, deposits, reconciliation.",
      dependencies: [],
      controlIds: ["c-cash", "c-sod-cash"],
      stage: 2,
      ownerPersonIds: ["p6"],
      inputs: ["Client payments", "Bank statements", "Earned-fee transfers from trust"],
      outputs: ["Reconciled operating account", "Cash position report"],
      risks: [
        {
          id: "r-cash-1",
          title: "Bookkeeper posts and reconciles alone",
          kind: "fraud",
          severity: 5,
          likelihood: 4,
          note: "Classic small-firm embezzlement path.",
          linkedControlId: "c-sod-cash",
          linkedScenarioId: "sc-cash-sod-failure",
        },
        {
          id: "r-cash-2",
          title: "Bank rec finished weeks after month end",
          kind: "control",
          severity: 3,
          likelihood: 3,
          note: "Late reconciliations delay detection of missing deposits and duplicate payments.",
        },
      ],
      ideas: [
        {
          id: "i-cash-1",
          title: "Managing partner reviews bank statement and rec monthly",
          category: "control",
          effort: "low",
          impact: "high",
          note: "Statements go to the partner unopened; she initials the rec within 10 days of month end.",
          status: "planned",
        },
        {
          id: "i-cash-2",
          title: "Bank feed auto-match in accounting system",
          category: "tech",
          effort: "low",
          impact: "medium",
          note: "Cuts manual posting and flags unmatched items the same week.",
          status: "backlog",
        },
      ],
      wastes: [
        {
          id: "w-cash-1",
          kind: "muda_waiting",
          label: "Cash position unknown until rec is done",
          note: "Partners cannot plan draws or hiring until the bookkeeper closes the month.",
        },
      ],
    },
    {
      id: "proc-ap",
      name: "Vendor & expense AP",
      layer: "process",
      description: "Vendor bills, expense reports, reimbursements.",
      dependencies: [],
      controlIds: ["c-ap", "c-sod-ap"],
      stage: 3,
      ownerPersonIds: ["p2", "p6"],
      inputs: ["Vendor bills", "Staff expense reports", "Subcontractor invoices"],
      outputs: ["Approved payments", "Reimbursements"],
      risks: [
        {
          id: "r-ap-1",
          title: "Vendor setup + payment concentrated",
          kind: "fraud",
          severity: 5,
          likelihood: 3,
          note: "Fictitious vendor risk.",
          linkedControlId: "c-sod-ap",
          linkedScenarioId: "sc-vendor-fraud",
        },
        {
          id: "r-ap-2",
          title: "Expense reports approved without receipts",
          kind: "fraud",
          severity: 3,
          likelihood: 4,
          note: "Travel and client meals reimbursed on a summary line; personal spend slips through.",
          linkedKnowledgeId: "k4",
        },
      ],
      ideas: [
        {
          id: "i-ap-1",
          title: "Partner approval for new vendors and payments over $2,500",
          category: "control",
          effort: "low",
          impact: "high",
          note: "Bank dual release; office manager prepares, partner approves.",
          status: "planned",
        },
        {
          id: "i-ap-2",
          title: "Receipt-capture expense app tied to client codes",
          category: "tech",
          effort: "medium",
          impact: "medium",
          note: "Photo receipts, auto policy checks, and billable expenses flow straight to invoices.",
          status: "exploring",
        },
      ],
      wastes: [
        {
          id: "w-ap-1",
          kind: "muda_motion",
          label: "Chasing paper receipts across the office",
          note: "Office manager walks desks each month collecting receipts and signatures.",
        },
      ],
    },
    {
      id: "proc-ar",
      name: "Collections & write-offs",
      layer: "process",
      description: "Client A/R, payment plans, write-offs.",
      dependencies: ["proc-billing"],
      controlIds: ["c-ar", "c-sod-ar"],
      stage: 3,
      ownerPersonIds: ["p4", "p6"],
      inputs: ["Open invoices", "Client payment promises", "Aging report"],
      outputs: ["Collected fees", "Approved write-offs"],
      risks: [
        {
          id: "r-ar-1",
          title: "Write-offs without partner approval",
          kind: "fraud",
          severity: 4,
          likelihood: 3,
          note: "Billing can write off client balances.",
          linkedScenarioId: "sc-writeoff-abuse",
        },
        {
          id: "r-ar-2",
          title: "Partners avoid collection calls on their own clients",
          kind: "revenue",
          severity: 3,
          likelihood: 4,
          note: "Relationship worries stall follow-up; balances age past 90 days and become uncollectible.",
          linkedKnowledgeId: "k5",
        },
      ],
      ideas: [
        {
          id: "i-ar-1",
          title: "Monthly write-off report signed by managing partner",
          category: "control",
          effort: "low",
          impact: "high",
          note: "Every adjustment carries a reason code; partner initials the exception list.",
          status: "planned",
        },
        {
          id: "i-ar-2",
          title: "Automated reminders at 30, 45, and 60 days",
          category: "tech",
          effort: "low",
          impact: "medium",
          note: "Practice management system sends friendly reminders so staff only call on true exceptions.",
          status: "backlog",
        },
      ],
      wastes: [
        {
          id: "w-ar-1",
          kind: "mura",
          label: "Collections done in a quarter-end scramble",
          note: "No weekly cadence; effort spikes when cash is short and then drops to zero.",
        },
      ],
    },
    {
      id: "proc-payroll",
      name: "Payroll & partner draws",
      layer: "process",
      description: "Staff payroll, partner distributions.",
      dependencies: [],
      controlIds: ["c-payroll"],
      stage: 4,
      ownerPersonIds: ["p2", "p1"],
      inputs: ["Approved timesheets", "Bonus and draw schedule", "Benefit changes"],
      outputs: ["Payroll file", "Partner distribution statements"],
      risks: [
        {
          id: "r-pay-1",
          title: "Bonus and draw exceptions live in one head",
          kind: "continuity",
          severity: 3,
          likelihood: 3,
          note: "Maya is the only person who knows how partner draws and bonus true-ups are calculated.",
          linkedKnowledgeId: "k6",
        },
        {
          id: "r-pay-2",
          title: "Payroll changes entered and approved by same person",
          kind: "fraud",
          severity: 4,
          likelihood: 2,
          note: "Rate changes or ghost employees could be added without a second review.",
          linkedControlId: "c-payroll",
        },
      ],
      ideas: [
        {
          id: "i-pay-1",
          title: "Partner reviews payroll register before submission",
          category: "control",
          effort: "low",
          impact: "high",
          note: "Compare headcount and gross pay to prior period; sign off in the payroll portal.",
          status: "planned",
        },
        {
          id: "i-pay-2",
          title: "Document the bonus and draw calculation",
          category: "training",
          effort: "low",
          impact: "medium",
          note: "One-page worksheet so the bookkeeper can run a cycle when Maya is out.",
          status: "exploring",
        },
      ],
      wastes: [
        {
          id: "w-pay-1",
          kind: "muda_rework",
          label: "Manual bonus recalculation each cycle",
          note: "Spreadsheet rebuilt from scratch every quarter instead of a saved template.",
        },
      ],
    },
  ],
  controls: baseFinancialControls(),
  staffComposition: { ...DEFAULT_STAFF, segregationScore: 38 },
  crimeFraudStats: fraudStats,
  scenarios: baseFraudScenarios(fraudStats.source, {
    keyPersonTitle: "Billing coordinator leaves with sole WIP knowledge",
    keyPersonDesc:
      "Sam (sole expert on client billing and WIP rules) resigns. Invoices stall and write-offs pile up.",
    knowledgeId: "k1",
    billingLabel: "Client write-offs without partner approval",
  }),
  roleTemplates: {
    "Managing Partner": [
      "approve_writeoffs",
      "approve_vendor",
      "approve_payroll",
      "bank_reconcile",
      "view_reports_only",
    ],
    "Office Manager": [
      "post_payments",
      "prepare_deposit",
      "create_vendor",
      "release_payment",
      "enter_payroll",
      "approve_vendor",
      "view_reports_only",
    ],
    "Senior Consultant": ["view_reports_only"],
    "Billing Coordinator": [
      "post_adjustments",
      "post_payments",
      "approve_writeoffs",
      "view_reports_only",
    ],
    "Admin Assistant": ["view_reports_only"],
    Bookkeeper: [
      "post_payments",
      "prepare_deposit",
      "bank_reconcile",
      "post_adjustments",
      "create_vendor",
      "release_payment",
      "view_reports_only",
    ],
  },
};
