import type { IndustryTemplate } from "./types";
import {
  baseFinancialControls,
  baseFraudScenarios,
  DEFAULT_FRAUD_STATS,
  DEFAULT_STAFF,
} from "./shared-controls";

const fraudStats = {
  ...DEFAULT_FRAUD_STATS,
  industryEmbezzlementRate: 0.22,
  typicalLossMid: 28000,
  source:
    "Illustrative restaurant/hospitality cash and vendor fraud patterns. Educational demo only.",
};

export const restaurantTemplate: IndustryTemplate = {
  id: "restaurant",
  businessName: "Ember & Oak Kitchen",
  people: [
    { id: "p1", name: "Elena Vargas", role: "Owner / Executive Chef", active: true, tenureYears: 11 },
    { id: "p2", name: "Maya Chen", role: "General Manager", active: true, tenureYears: 6 },
    { id: "p3", name: "Jordan Blake", role: "Head Server", active: true, tenureYears: 5 },
    { id: "p4", name: "Sam Ortiz", role: "Line Cook Lead", active: true, tenureYears: 4 },
    { id: "p5", name: "Riley Kim", role: "Bar Manager", active: true, tenureYears: 3 },
    { id: "p6", name: "Chris Patel", role: "Bookkeeper", active: true, tenureYears: 2 },
  ],
  knowledge: [
    {
      id: "k1",
      name: "Tip pooling & cash-out",
      description: "Tip distribution, paid vs reported tips, shift closeout.",
      criticality: "critical",
      category: "process",
      linkedProcessIds: ["proc-cash"],
    },
    {
      id: "k2",
      name: "Daily sales deposit",
      description: "POS Z-report, cash vs card, safe drops.",
      criticality: "critical",
      category: "process",
      linkedProcessIds: ["proc-cash"],
    },
    {
      id: "k3",
      name: "Food vendor ordering",
      description: "Primary vendors, credit terms, standing orders.",
      criticality: "important",
      category: "vendor",
      linkedProcessIds: ["proc-ap"],
    },
    {
      id: "k4",
      name: "Inventory & waste logging",
      description: "Prep yields, spoilage tracking, comp policy.",
      criticality: "important",
      category: "process",
      linkedProcessIds: ["proc-inventory"],
    },
    {
      id: "k5",
      name: "Liquor inventory control",
      description: "Bar pars, pour standards, variance investigation.",
      criticality: "critical",
      category: "compliance",
      linkedProcessIds: ["proc-bar"],
    },
    {
      id: "k6",
      name: "Payroll tip credit rules",
      description: "Tip credit, reported tips, state compliance.",
      criticality: "important",
      category: "compliance",
      linkedProcessIds: ["proc-payroll"],
    },
  ],
  relations: [
    { personId: "p3", knowledgeId: "k1", level: "expert" },
    { personId: "p2", knowledgeId: "k1", level: "proficient" },
    { personId: "p3", knowledgeId: "k2", level: "expert" },
    { personId: "p2", knowledgeId: "k2", level: "proficient" },
    { personId: "p2", knowledgeId: "k3", level: "expert" },
    { personId: "p4", knowledgeId: "k4", level: "proficient" },
    { personId: "p5", knowledgeId: "k5", level: "expert" },
    { personId: "p2", knowledgeId: "k6", level: "expert" },
    { personId: "p6", knowledgeId: "k2", level: "basic" },
  ],
  processes: [
    {
      id: "proc-service",
      name: "Service & floor ops",
      layer: "process",
      description: "Dining room flow, comps, guest recovery.",
      dependencies: [],
      controlIds: [],
      stage: 0,
      ownerPersonIds: ["p2", "p3"],
      risks: [
        {
          id: "r-svc-1",
          title: "Unauthorized comps",
          kind: "fraud",
          severity: 3,
          likelihood: 4,
          note: "Comps without manager log erode margin.",
        },
      ],
    },
    {
      id: "proc-bar",
      name: "Bar service & liquor",
      layer: "process",
      description: "Bar sales, pours, liquor inventory.",
      dependencies: ["proc-service"],
      controlIds: [],
      stage: 1,
      ownerPersonIds: ["p5"],
      risks: [
        {
          id: "r-bar-1",
          title: "Liquor shrink without variance review",
          kind: "fraud",
          severity: 4,
          likelihood: 3,
          note: "Bar manager sole expert on pour standards.",
          linkedKnowledgeId: "k5",
        },
      ],
    },
    {
      id: "proc-inventory",
      name: "Food inventory & prep",
      layer: "process",
      description: "Receiving, prep, waste, food cost.",
      dependencies: [],
      controlIds: [],
      stage: 1,
      ownerPersonIds: ["p4"],
    },
    {
      id: "proc-cash",
      name: "Cash, tips & deposits",
      layer: "process",
      description: "Shift closeout, tip pool, bank deposits.",
      dependencies: [],
      controlIds: ["c-cash", "c-sod-cash"],
      stage: 2,
      ownerPersonIds: ["p3", "p2"],
      risks: [
        {
          id: "r-cash-1",
          title: "Tip skimming / deposit mismatch",
          kind: "fraud",
          severity: 5,
          likelihood: 4,
          note: "Head server closes and deposits without independent review.",
          linkedControlId: "c-sod-cash",
          linkedScenarioId: "sc-cash-sod-failure",
          linkedKnowledgeId: "k1",
        },
      ],
    },
    {
      id: "proc-ap",
      name: "Food & beverage AP",
      layer: "process",
      description: "Vendor invoices, liquor distributor, linen.",
      dependencies: [],
      controlIds: ["c-ap", "c-sod-ap"],
      stage: 3,
      ownerPersonIds: ["p2", "p6"],
      risks: [
        {
          id: "r-ap-1",
          title: "GM creates vendors and pays",
          kind: "fraud",
          severity: 5,
          likelihood: 3,
          note: "Fictitious food vendor path.",
          linkedControlId: "c-sod-ap",
          linkedScenarioId: "sc-vendor-fraud",
        },
      ],
    },
    {
      id: "proc-ar",
      name: "Comps & void adjustments",
      layer: "process",
      description: "Voids, discounts, event deposits.",
      dependencies: ["proc-service"],
      controlIds: ["c-sod-billing"],
      stage: 3,
      ownerPersonIds: ["p2"],
      risks: [
        {
          id: "r-ar-1",
          title: "Void/comp authority concentrated",
          kind: "fraud",
          severity: 4,
          likelihood: 4,
          note: "GM can void tickets without owner review.",
          linkedScenarioId: "sc-writeoff-abuse",
        },
      ],
    },
    {
      id: "proc-payroll",
      name: "Payroll & tips reporting",
      layer: "process",
      description: "Hourly payroll, tip reporting, tip credit.",
      dependencies: [],
      controlIds: ["c-payroll"],
      stage: 4,
      ownerPersonIds: ["p2", "p1"],
    },
  ],
  controls: baseFinancialControls(),
  staffComposition: { ...DEFAULT_STAFF, teamSize: 6, segregationScore: 35 },
  crimeFraudStats: fraudStats,
  scenarios: baseFraudScenarios(fraudStats.source, {
    keyPersonTitle: "Head server leaves with sole tip-pool knowledge",
    keyPersonDesc:
      "Jordan (sole expert on tip pooling and shift closeout) resigns mid-week. Deposits mismatch and tip disputes spike.",
    knowledgeId: "k1",
    billingLabel: "Void/comp authority without owner review",
  }),
  roleTemplates: {
    "Owner / Executive Chef": [
      "approve_writeoffs",
      "approve_vendor",
      "approve_payroll",
      "bank_reconcile",
      "view_reports_only",
    ],
    "General Manager": [
      "post_payments",
      "prepare_deposit",
      "post_adjustments",
      "create_vendor",
      "release_payment",
      "enter_payroll",
      "approve_writeoffs",
      "view_reports_only",
    ],
    "Head Server": ["collect_cash", "post_payments", "prepare_deposit", "post_adjustments"],
    "Line Cook Lead": ["view_reports_only"],
    "Bar Manager": ["collect_cash", "post_adjustments", "view_reports_only"],
    Bookkeeper: [
      "post_payments",
      "bank_reconcile",
      "post_adjustments",
      "view_reports_only",
    ],
  },
};
