import type { IndustrySample } from "./types";
import {
  baseFinancialControls,
  baseFraudScenarios,
  SAMPLE_SAFEGUARDS,
  SCENARIO_FIGURES,
} from "./shared-controls";

/**
 * A full-service restaurant with a bar and about six people: the owner, who
 * is also the chef, a general manager who handles vendors, deposits, voids
 * and payroll, a head server who closes out shifts and runs the tip pool, a
 * line cook lead, a bar manager and a bookkeeper. It uses the shared cash,
 * write-off and vendor controls and scenarios (a restaurant has no
 * receivables), and adds sales tax and the tip pool.
 *
 * Sales tax and tips. Sales tax a restaurant collects is the state's money
 * from the moment it is collected, and in many states the person responsible
 * for paying it over is personally liable when it is not. Tips belong to the
 * employees: under the Fair Labor Standards Act an employer, including its
 * managers and supervisors, may not keep any part of them, and tipped
 * employees report their tips to the employer for payroll taxes (IRS Form
 * 4070; large food or beverage establishments also file Form 8027). The two
 * schemes below, tax collected but not paid and a tip pool shifted or held
 * back, follow from those rules; no rate is given for either.
 */
export const restaurantTemplate: IndustrySample = {
  id: "restaurant",
  people: [
    {
      id: "p1",
      name: "Marco Bellini",
      role: "Owner / Executive Chef",
      active: true,
      tenureYears: 11,
    },
    { id: "p2", name: "Keisha Moore", role: "General Manager", active: true, tenureYears: 6 },
    { id: "p3", name: "Diego Ramirez", role: "Head Server", active: true, tenureYears: 5 },
    { id: "p4", name: "Tom Becker", role: "Line Cook Lead", active: true, tenureYears: 4 },
    { id: "p5", name: "Nina Petrova", role: "Bar Manager", active: true, tenureYears: 3 },
    { id: "p6", name: "Owen Clarke", role: "Bookkeeper", active: true, tenureYears: 2 },
  ],
  roleTemplates: {
    "Owner / Executive Chef": [
      "approve_writeoffs",
      "approve_vendor",
      "approve_payroll",
      "approve_expenses",
      "bank_reconcile",
      "view_reports_only",
    ],
    "General Manager": [
      "post_payments",
      "prepare_deposit",
      "post_adjustments",
      "create_vendor",
      "release_payment",
      "enter_payroll",
      "approve_writeoffs",
      "hold_company_card",
      "view_reports_only",
    ],
    "Head Server": ["collect_cash", "post_payments", "prepare_deposit", "post_adjustments"],
    "Line Cook Lead": ["view_reports_only"],
    "Bar Manager": ["collect_cash", "post_adjustments", "view_reports_only"],
    Bookkeeper: [
      "post_payments",
      "bank_reconcile",
      "post_adjustments",
      "review_card_statement",
      "view_reports_only",
    ],
  },
  knowledge: [
    {
      id: "k1",
      name: "Tip pooling & cash-out",
      description: "Tip distribution, paid vs reported tips, shift closeout.",
      criticality: "critical",
      category: "process",
      linkedProcessIds: ["proc-cash", "proc-tips"],
    },
    {
      id: "k2",
      name: "Daily sales deposit",
      description: "End-of-day POS report (the Z-report), cash vs card, safe drops.",
      criticality: "critical",
      category: "process",
      linkedProcessIds: ["proc-cash"],
    },
    {
      id: "k3",
      name: "Food vendor ordering",
      description: "Primary vendors, credit terms, standing orders.",
      criticality: "important",
      category: "vendor",
      linkedProcessIds: ["proc-ap"],
    },
    {
      id: "k4",
      name: "Inventory & waste logging",
      description: "Prep yields, spoilage tracking, comp policy.",
      criticality: "important",
      category: "process",
      linkedProcessIds: ["proc-inventory"],
    },
    {
      id: "k5",
      name: "Liquor inventory control",
      description: "Bar pars, pour standards, variance investigation.",
      criticality: "critical",
      category: "compliance",
      linkedProcessIds: ["proc-bar"],
    },
    {
      id: "k6",
      name: "Payroll tip credit rules",
      description:
        "The tip credit (tips counted toward the minimum wage), reported tips, state rules.",
      criticality: "important",
      category: "compliance",
      linkedProcessIds: ["proc-payroll", "proc-tips"],
    },
    {
      id: "k7",
      name: "Sales tax returns & remittance",
      description:
        "Filing frequency, taxable and exempt sales, and where the POS tax report lives.",
      criticality: "critical",
      category: "compliance",
      linkedProcessIds: ["proc-salestax"],
    },
  ],
  relations: [
    { personId: "p3", knowledgeId: "k1", level: "expert" },
    { personId: "p2", knowledgeId: "k1", level: "basic" },
    { personId: "p3", knowledgeId: "k2", level: "expert" },
    { personId: "p2", knowledgeId: "k2", level: "proficient" },
    { personId: "p2", knowledgeId: "k3", level: "expert" },
    { personId: "p4", knowledgeId: "k4", level: "proficient" },
    { personId: "p5", knowledgeId: "k5", level: "expert" },
    { personId: "p2", knowledgeId: "k6", level: "expert" },
    { personId: "p6", knowledgeId: "k2", level: "basic" },
    { personId: "p6", knowledgeId: "k7", level: "expert" },
    { personId: "p1", knowledgeId: "k7", level: "aware" },
  ],
  processes: [
    {
      id: "proc-service",
      name: "Service & floor ops",
      layer: "process",
      description: "Dining room flow, comps, guest recovery.",
      dependencies: [],
      controlIds: [],
      stage: 0,
      ownerPersonIds: ["p2", "p3"],
      inputs: ["Reservations & walk-ins", "Floor plan", "Menu & specials"],
      outputs: ["Closed checks", "Guest feedback"],
      risks: [
        {
          id: "r-svc-1",
          title: "Unauthorized comps",
          kind: "fraud",
          severity: 3,
          likelihood: 4,
          note: "Comps without manager log erode margin.",
        },
        {
          id: "r-svc-2",
          title: "Allergy order miscommunication",
          kind: "safety",
          severity: 5,
          likelihood: 2,
          note: "Allergy notes are verbal between server and line; one missed callout is a guest emergency.",
        },
      ],
      ideas: [
        {
          id: "i-svc-1",
          title: "Comp reason required on every ticket",
          category: "control",
          effort: "low",
          impact: "high",
          note: "The POS forces a reason code; the general manager reads the comp report nightly.",
          status: "planned",
        },
        {
          id: "i-svc-2",
          title: "Allergy flag printed on kitchen ticket",
          category: "policy",
          effort: "low",
          impact: "high",
          note: "Servers enter allergies as a POS modifier so the line sees it in writing.",
          status: "exploring",
        },
      ],
      wastes: [
        {
          id: "w-svc-1",
          kind: "muda_motion",
          label: "Servers run to the bar for every drink",
          note: "No runner or service well means long walks and slow table turns.",
        },
      ],
    },
    {
      id: "proc-bar",
      name: "Bar service & liquor",
      layer: "process",
      description: "Bar sales, pours, liquor inventory.",
      dependencies: ["proc-service"],
      controlIds: [],
      stage: 1,
      ownerPersonIds: ["p5"],
      inputs: ["Drink orders", "Liquor stock", "Pour standards"],
      outputs: ["Bar sales", "Weekly liquor variance"],
      risks: [
        {
          id: "r-bar-1",
          title: "Liquor shrink without variance review",
          kind: "fraud",
          severity: 4,
          likelihood: 3,
          note: "Bar manager sole expert on pour standards.",
          linkedKnowledgeId: "k5",
        },
        {
          id: "r-bar-2",
          title: "Over-serving and ID check lapses",
          kind: "compliance",
          severity: 5,
          likelihood: 2,
          note: "Liquor license and liability exposure if a busy bar skips ID checks or cutoffs.",
        },
      ],
      ideas: [
        {
          id: "i-bar-1",
          title: "Weekly pour-cost variance report to owner",
          category: "control",
          effort: "medium",
          impact: "high",
          note: "Compare bottles used to drinks rung; investigate anything over 3% variance.",
          status: "planned",
        },
        {
          id: "i-bar-2",
          title: "Cross-train the general manager on bar inventory counts",
          category: "training",
          effort: "low",
          impact: "medium",
          note: "The general manager runs one weekly count with the bar manager so pars and variance are not single-owner.",
          status: "backlog",
        },
      ],
      wastes: [
        {
          id: "w-bar-1",
          kind: "muda_overprocessing",
          label: "Free-pouring instead of jiggers",
          note: "Inconsistent pours mean the bar gives away over-pours and remakes drinks to taste.",
        },
      ],
    },
    {
      id: "proc-inventory",
      name: "Food inventory & prep",
      layer: "process",
      description: "Receiving, prep, waste, food cost.",
      dependencies: [],
      controlIds: [],
      stage: 1,
      ownerPersonIds: ["p4"],
      inputs: ["Vendor deliveries", "Prep lists", "Par levels"],
      outputs: ["Prepped mise en place", "Waste log", "Weekly food cost"],
      risks: [
        {
          id: "r-inv-1",
          title: "Deliveries accepted without checking against the order",
          kind: "control",
          severity: 3,
          likelihood: 4,
          note: "Short cases and weight shortages become food cost when nobody counts at the back door.",
        },
        {
          id: "r-inv-2",
          title: "Cold-chain and date-label gaps",
          kind: "safety",
          severity: 4,
          likelihood: 3,
          note: "Staff check walk-in temperatures and first-in, first-out date labels from memory, not a log; health inspection exposure.",
          linkedKnowledgeId: "k4",
        },
      ],
      ideas: [
        {
          id: "i-inv-1",
          title: "Back-door receiving checklist with scale",
          category: "control",
          effort: "low",
          impact: "high",
          note: "Count and weigh against the invoice before signing; note shorts so the bookkeeper claims the credit.",
          status: "planned",
        },
        {
          id: "i-inv-2",
          title: "Daily waste sheet by station",
          category: "lean",
          effort: "low",
          impact: "medium",
          note: "Log spoilage, over-prep, and remakes so the kitchen can tune prep pars weekly.",
          status: "exploring",
        },
      ],
      wastes: [
        {
          id: "w-inv-1",
          kind: "mura",
          label: "Over-prep on slow nights, short on busy ones",
          note: "Prep lists do not use the reservation forecast, so food spoils on slow nights and dishes run out on busy ones.",
        },
      ],
    },
    {
      id: "proc-cash",
      name: "Cash, tips & deposits",
      layer: "process",
      description: "Shift closeout, tip pool, bank deposits.",
      dependencies: [],
      controlIds: ["c-cash", "c-sod-cash"],
      stage: 2,
      ownerPersonIds: ["p3", "p2"],
      inputs: ["Server cash-outs", "End-of-day POS report", "Card tips"],
      outputs: ["Bank deposit", "Tip pool distribution"],
      risks: [
        {
          id: "r-cash-1",
          title: "Tip skimming / deposit mismatch",
          kind: "fraud",
          severity: 5,
          likelihood: 4,
          note: "Head server closes and deposits without independent review.",
          linkedControlId: "c-sod-cash",
          linkedScenarioId: "sc-cash-sod-failure",
          linkedKnowledgeId: "k1",
        },
        {
          id: "r-cash-2",
          title: "Tip pool math is one person's spreadsheet",
          kind: "continuity",
          severity: 4,
          likelihood: 3,
          note: "Often only the head server knows the split rules; disputes and wage claims spike when they are out.",
          linkedKnowledgeId: "k1",
          linkedScenarioId: "sc-key-person-leaves",
        },
      ],
      ideas: [
        {
          id: "i-cash-1",
          title: "Two-person drop with signed safe log",
          category: "control",
          effort: "low",
          impact: "high",
          note: "Closer counts, second person verifies and both initial the drop envelope.",
          status: "planned",
        },
        {
          id: "i-cash-2",
          title: "Owner matches deposits to the end-of-day POS reports weekly",
          category: "control",
          effort: "low",
          impact: "high",
          note: "The owner reads the bank statement against the nightly closeouts, which catches skimming fast.",
          status: "exploring",
        },
      ],
      wastes: [
        {
          id: "w-cash-1",
          kind: "muda_overprocessing",
          label: "Tip pool recalculated by hand nightly",
          note: "Hours and sales are re-keyed from POS into a spreadsheet after every shift.",
        },
      ],
    },
    {
      id: "proc-ap",
      name: "Food & beverage bills",
      layer: "process",
      description: "Vendor invoices, liquor distributor, linen.",
      dependencies: [],
      controlIds: ["c-ap", "c-sod-ap"],
      stage: 3,
      ownerPersonIds: ["p2", "p6"],
      inputs: ["Vendor invoices", "Receiving sheets", "Delivery credits"],
      outputs: ["Paid vendors", "Food & bev cost report"],
      risks: [
        {
          id: "r-ap-1",
          title: "General manager sets up vendors and pays them",
          kind: "fraud",
          severity: 5,
          likelihood: 3,
          note: "An insider can set up and pay a fake food vendor.",
          linkedControlId: "c-sod-ap",
          linkedScenarioId: "sc-vendor-fraud",
        },
        {
          id: "r-ap-2",
          title: "Delivery shortages never credited",
          kind: "revenue",
          severity: 3,
          likelihood: 4,
          note: "Nobody passes shorts noted at the back door to the bookkeeper, so the restaurant pays full invoices.",
        },
      ],
      ideas: [
        {
          id: "i-ap-1",
          title: "Owner approves new vendors and bank changes",
          category: "policy",
          effort: "low",
          impact: "high",
          note: "The owner signs off before anyone adds a vendor or changes ACH details.",
          status: "planned",
        },
        {
          id: "i-ap-2",
          title: "Match invoice to receiving sheet before paying",
          category: "control",
          effort: "medium",
          impact: "medium",
          note: "Bookkeeper pays only invoices with a signed receiving sheet attached.",
          status: "backlog",
        },
      ],
      wastes: [
        {
          id: "w-ap-1",
          kind: "muda_waiting",
          label: "Invoices pile up in the office drawer",
          note: "Paper invoices wait a week or more before entry; late fees and lost credits.",
        },
      ],
    },
    {
      id: "proc-ar",
      name: "Comps & void adjustments",
      layer: "process",
      description: "Voids, discounts, event deposits.",
      dependencies: ["proc-service"],
      controlIds: ["c-sod-billing"],
      stage: 3,
      ownerPersonIds: ["p2"],
      inputs: ["Void requests", "Comp tickets", "Event contracts"],
      outputs: ["Nightly void/comp report", "Event deposit ledger"],
      risks: [
        {
          id: "r-ar-1",
          title: "Void/comp authority concentrated",
          kind: "fraud",
          severity: 4,
          likelihood: 4,
          note: "The general manager can void tickets without owner review.",
          linkedScenarioId: "sc-writeoff-abuse",
        },
        {
          id: "r-ar-2",
          title: "Event deposits not tracked to the booking",
          kind: "revenue",
          severity: 3,
          likelihood: 3,
          note: "Private-event deposits land in general sales; refunds and balances due are guesswork.",
        },
      ],
      ideas: [
        {
          id: "i-ar-1",
          title: "Manager-only void code with nightly void report",
          category: "control",
          effort: "low",
          impact: "high",
          note: "Servers cannot void after send; owner gets the void report by email each night.",
          status: "planned",
        },
        {
          id: "i-ar-2",
          title: "Simple event deposit log",
          category: "policy",
          effort: "low",
          impact: "medium",
          note: "One sheet per event: deposit date, amount, balance due, who collected.",
          status: "backlog",
        },
      ],
      wastes: [
        {
          id: "w-ar-1",
          kind: "muda_rework",
          label: "Re-ringing tickets to fix mistakes",
          note: "Servers void and re-ring order errors instead of modifying them, which inflates void counts.",
        },
      ],
    },
    {
      id: "proc-tips",
      name: "Tip pool & tip reporting",
      layer: "process",
      description: "Card and cash tips, pool shares, tip-outs, employee tip reports.",
      dependencies: ["proc-cash"],
      controlIds: ["c-tip-pool"],
      stage: 3,
      ownerPersonIds: ["p3", "p2"],
      inputs: ["Card tips from the POS", "Declared cash tips", "Hours by position"],
      outputs: ["Tip pool distribution", "Tip records for payroll"],
      risks: [
        {
          id: "r-tip-1",
          title: "A manager or supervisor takes part of the pool",
          kind: "compliance",
          severity: 5,
          likelihood: 3,
          note: "Federal law bars employers, including managers and supervisors, from keeping any part of employees' tips; the employer owes the tips taken back to the staff.",
          linkedControlId: "c-tip-pool",
          linkedScenarioId: "sc-tip-pool-manipulation",
          linkedKnowledgeId: "k1",
        },
        {
          id: "r-tip-2",
          title: "Cash tips under-reported",
          kind: "compliance",
          severity: 3,
          likelihood: 4,
          note: "Tipped staff report tips to the employer each month, and the employer owes payroll taxes on them; unreported tips become back taxes at audit.",
          linkedKnowledgeId: "k6",
        },
      ],
      ideas: [
        {
          id: "i-tip-1",
          title: "Written tip pool policy with shares by position",
          category: "policy",
          effort: "low",
          impact: "high",
          note: "Every eligible position and its share on one page staff have signed.",
          status: "planned",
        },
        {
          id: "i-tip-2",
          title: "Bookkeeper checks each distribution against POS tips and hours",
          category: "control",
          effort: "low",
          impact: "high",
          note: "Someone outside the pool confirms the total paid out equals the tips collected.",
          status: "exploring",
        },
      ],
      wastes: [
        {
          id: "w-tip-1",
          kind: "muda_rework",
          label: "Shares recalculated after every dispute",
          note: "Without a written split, each complaint means rebuilding the week's pool by hand.",
        },
      ],
    },
    {
      id: "proc-salestax",
      name: "Sales tax collection & remittance",
      layer: "process",
      description: "POS tax settings, sales tax returns, payments to the state.",
      dependencies: ["proc-cash"],
      controlIds: ["c-salestax"],
      stage: 4,
      ownerPersonIds: ["p6", "p1"],
      inputs: ["POS sales and tax report", "Exempt and third-party sales", "State filing calendar"],
      outputs: ["Filed sales tax returns", "Tax payments"],
      risks: [
        {
          id: "r-tax-1",
          title: "Sales tax collected but not paid to the state",
          kind: "fraud",
          severity: 5,
          likelihood: 2,
          note: "The tax is the state's money once collected; in many states the person responsible for paying it is personally liable, and the gap surfaces only when the state writes.",
          linkedControlId: "c-salestax",
          linkedScenarioId: "sc-salestax-unremitted",
          linkedKnowledgeId: "k7",
        },
        {
          id: "r-tax-2",
          title: "Return prepared from bank deposits, not the POS report",
          kind: "compliance",
          severity: 4,
          likelihood: 3,
          note: "Taxable sales that do not match the POS report become an assessment with penalties and interest at audit.",
        },
      ],
      ideas: [
        {
          id: "i-tax-1",
          title:
            "Owner reads each return, the POS report behind it and the state's payment confirmation",
          category: "control",
          effort: "low",
          impact: "high",
          note: "The owner files the confirmation with the return and the POS report behind it.",
          status: "planned",
        },
        {
          id: "i-tax-2",
          title: "Check POS tax settings after every menu change",
          category: "policy",
          effort: "low",
          impact: "medium",
          note: "The manager sets new items to the right tax category before the restaurant sells them.",
          status: "backlog",
        },
      ],
      wastes: [
        {
          id: "w-tax-1",
          kind: "muda_overprocessing",
          label: "Taxable sales rebuilt from several reports",
          note: "The bookkeeper pulls delivery, catering and dine-in sales from separate systems and adds them by hand each period.",
        },
      ],
    },
    {
      id: "proc-payroll",
      name: "Payroll & tips reporting",
      layer: "process",
      description: "Hourly payroll, tip reporting, tip credit.",
      dependencies: [],
      controlIds: ["c-payroll"],
      stage: 4,
      ownerPersonIds: ["p2", "p1"],
      inputs: ["Time punches", "Declared tips", "Tip pool sheets"],
      outputs: ["Payroll file", "Tip reporting records"],
      risks: [
        {
          id: "r-pay-1",
          title: "Tip credit applied wrong",
          kind: "compliance",
          severity: 4,
          likelihood: 3,
          note: "Tipped staff paid below the minimum wage after the tip credit means back pay and penalties.",
          linkedKnowledgeId: "k6",
        },
        {
          id: "r-pay-2",
          title: "General manager edits punches and runs payroll alone",
          kind: "fraud",
          severity: 4,
          likelihood: 2,
          note: "No second review before export; ghost hours or buddy punches go unnoticed.",
        },
      ],
      ideas: [
        {
          id: "i-pay-1",
          title: "Owner reads the payroll summary before anyone sends it",
          category: "control",
          effort: "low",
          impact: "high",
          note: "The owner reads the hours, tips and any punch edits each period.",
          status: "planned",
        },
        {
          id: "i-pay-2",
          title: "Tip credit checklist per pay period",
          category: "training",
          effort: "low",
          impact: "medium",
          note: "One-page state rules so anyone can confirm every tipped employee clears minimum wage.",
          status: "exploring",
        },
      ],
      wastes: [
        {
          id: "w-pay-1",
          kind: "muda_rework",
          label: "Fixing missed punches after the fact",
          note: "Servers forget to clock out; the general manager rebuilds hours from the POS every period.",
        },
      ],
    },
  ],
  // A restaurant keeps no receivables, so the receivables controls stay out;
  // sales tax and the tip pool are its own.
  controls: [
    ...baseFinancialControls().filter((c) => c.id !== "c-ar" && c.id !== "c-sod-ar"),
    {
      id: "c-salestax",
      name: "Sales tax return review",
      description:
        "Each return's taxable sales tie to the POS sales report, and the owner, not the preparer, reads the state's confirmation that the payment arrived.",
      duties: ["review", "reconciliation"],
      segregated: false,
      compensatingControls: ["Owner reads the state tax account online each quarter"],
      residualRiskAccepted: false,
    },
    {
      id: "c-tip-pool",
      name: "Tip pool distribution review",
      description:
        "Pool shares follow a written policy; someone outside the pool checks each distribution against POS tips and hours, and no manager or supervisor draws from it.",
      duties: ["review", "authorization"],
      segregated: false,
      compensatingControls: ["Staff can see their own tip totals in the POS"],
      residualRiskAccepted: false,
    },
  ],
  staffComposition: SAMPLE_SAFEGUARDS,
  scenarios: [
    ...baseFraudScenarios({
      keyPersonTitle: "Head server leaves with sole tip-pool knowledge",
      keyPersonDesc:
        "The head server (sole expert on tip pooling and shift closeout) resigns mid-week. Deposits mismatch and tip disputes spike.",
      knowledgeId: "k1",
      billingLabel: "Void/comp authority without owner review",
    }),
    {
      id: "sc-salestax-unremitted",
      title: "Sales tax collected but not paid to the state",
      description:
        "The person who prepares the sales tax return also pays it and reconciles the bank. The return reports less than the POS collected, or the payment never goes out, and the gap surfaces when the state sends a notice with penalties and interest.",
      controlId: "c-salestax",
      sodRuleIds: ["rule-release-rec"],
      knowledgeId: "k7",
      ...SCENARIO_FIGURES.cash,
      cascadeLayers: ["control", "process", "surface", "continuity"],
      mitigations: [
        {
          id: "m-tax-1",
          label:
            "Owner reads each return, the POS report behind it and the state's payment confirmation",
          effort: "low",
          riskReduction: 0.5,
          costAnnual: 0,
        },
        {
          id: "m-tax-2",
          label: "Owner reads the state tax account online each quarter",
          effort: "low",
          riskReduction: 0.45,
          costAnnual: 0,
        },
      ],
    },
    {
      id: "sc-tip-pool-manipulation",
      title: "Tip pool shares shifted or paid to a manager",
      description:
        "The person who calculates the pool also pays it out. Shares move to a favored employee or a manager, or the manager holds back card tips, and staff learn of it only when someone compares their pay with the POS.",
      controlId: "c-tip-pool",
      sodRuleIds: ["rule-payroll"],
      knowledgeId: "k1",
      ...SCENARIO_FIGURES.writeoff,
      cascadeLayers: ["control", "knowledge", "process", "continuity"],
      mitigations: [
        {
          id: "m-tip-1",
          label: "Written pool policy, and each distribution checked by someone outside the pool",
          effort: "low",
          riskReduction: 0.5,
          costAnnual: 0,
        },
        {
          id: "m-tip-2",
          label: "Staff see their own POS tip totals each pay period",
          effort: "low",
          riskReduction: 0.35,
          costAnnual: 0,
        },
      ],
    },
  ],
};
