import type { IndustryTemplate } from "./types";
import {
  baseFinancialControls,
  baseFraudScenarios,
  DEFAULT_FRAUD_STATS,
  DEFAULT_STAFF,
} from "./shared-controls";

const fraudStats = {
  ...DEFAULT_FRAUD_STATS,
  industryEmbezzlementRate: 0.22,
  typicalLossMid: 28000,
  source:
    "Illustrative restaurant/hospitality cash and vendor fraud patterns. Educational demo only.",
};

export const restaurantTemplate: IndustryTemplate = {
  id: "restaurant",
  businessName: "Ember & Oak Kitchen",
  people: [
    { id: "p1", name: "Elena Vargas", role: "Owner / Executive Chef", active: true, tenureYears: 11 },
    { id: "p2", name: "Maya Chen", role: "General Manager", active: true, tenureYears: 6 },
    { id: "p3", name: "Jordan Blake", role: "Head Server", active: true, tenureYears: 5 },
    { id: "p4", name: "Sam Ortiz", role: "Line Cook Lead", active: true, tenureYears: 4 },
    { id: "p5", name: "Riley Kim", role: "Bar Manager", active: true, tenureYears: 3 },
    { id: "p6", name: "Chris Patel", role: "Bookkeeper", active: true, tenureYears: 2 },
  ],
  knowledge: [
    {
      id: "k1",
      name: "Tip pooling & cash-out",
      description: "Tip distribution, paid vs reported tips, shift closeout.",
      criticality: "critical",
      category: "process",
      linkedProcessIds: ["proc-cash"],
    },
    {
      id: "k2",
      name: "Daily sales deposit",
      description: "POS Z-report, cash vs card, safe drops.",
      criticality: "critical",
      category: "process",
      linkedProcessIds: ["proc-cash"],
    },
    {
      id: "k3",
      name: "Food vendor ordering",
      description: "Primary vendors, credit terms, standing orders.",
      criticality: "important",
      category: "vendor",
      linkedProcessIds: ["proc-ap"],
    },
    {
      id: "k4",
      name: "Inventory & waste logging",
      description: "Prep yields, spoilage tracking, comp policy.",
      criticality: "important",
      category: "process",
      linkedProcessIds: ["proc-inventory"],
    },
    {
      id: "k5",
      name: "Liquor inventory control",
      description: "Bar pars, pour standards, variance investigation.",
      criticality: "critical",
      category: "compliance",
      linkedProcessIds: ["proc-bar"],
    },
    {
      id: "k6",
      name: "Payroll tip credit rules",
      description: "Tip credit, reported tips, state compliance.",
      criticality: "important",
      category: "compliance",
      linkedProcessIds: ["proc-payroll"],
    },
  ],
  relations: [
    { personId: "p3", knowledgeId: "k1", level: "expert" },
    { personId: "p2", knowledgeId: "k1", level: "proficient" },
    { personId: "p3", knowledgeId: "k2", level: "expert" },
    { personId: "p2", knowledgeId: "k2", level: "proficient" },
    { personId: "p2", knowledgeId: "k3", level: "expert" },
    { personId: "p4", knowledgeId: "k4", level: "proficient" },
    { personId: "p5", knowledgeId: "k5", level: "expert" },
    { personId: "p2", knowledgeId: "k6", level: "expert" },
    { personId: "p6", knowledgeId: "k2", level: "basic" },
  ],
  processes: [
    {
      id: "proc-service",
      name: "Service & floor ops",
      layer: "process",
      description: "Dining room flow, comps, guest recovery.",
      dependencies: [],
      controlIds: [],
      stage: 0,
      ownerPersonIds: ["p2", "p3"],
      inputs: ["Reservations & walk-ins", "Floor plan", "Menu & specials"],
      outputs: ["Closed checks", "Guest feedback"],
      risks: [
        {
          id: "r-svc-1",
          title: "Unauthorized comps",
          kind: "fraud",
          severity: 3,
          likelihood: 4,
          note: "Comps without manager log erode margin.",
        },
        {
          id: "r-svc-2",
          title: "Allergy order miscommunication",
          kind: "safety",
          severity: 5,
          likelihood: 2,
          note: "Allergy notes are verbal between server and line; one missed callout is a guest emergency.",
        },
      ],
      ideas: [
        {
          id: "i-svc-1",
          title: "Comp reason required on every ticket",
          category: "control",
          effort: "low",
          impact: "high",
          note: "POS forces a reason code; GM reviews the comp report nightly.",
          status: "planned",
        },
        {
          id: "i-svc-2",
          title: "Allergy flag printed on kitchen ticket",
          category: "policy",
          effort: "low",
          impact: "high",
          note: "Servers enter allergies as a POS modifier so the line sees it in writing.",
          status: "exploring",
        },
      ],
      wastes: [
        {
          id: "w-svc-1",
          kind: "muda_motion",
          label: "Servers run to the bar for every drink",
          note: "No runner or service well means long walks and slow table turns.",
        },
      ],
    },
    {
      id: "proc-bar",
      name: "Bar service & liquor",
      layer: "process",
      description: "Bar sales, pours, liquor inventory.",
      dependencies: ["proc-service"],
      controlIds: [],
      stage: 1,
      ownerPersonIds: ["p5"],
      inputs: ["Drink orders", "Liquor stock", "Pour standards"],
      outputs: ["Bar sales", "Weekly liquor variance"],
      risks: [
        {
          id: "r-bar-1",
          title: "Liquor shrink without variance review",
          kind: "fraud",
          severity: 4,
          likelihood: 3,
          note: "Bar manager sole expert on pour standards.",
          linkedKnowledgeId: "k5",
        },
        {
          id: "r-bar-2",
          title: "Over-serving and ID check lapses",
          kind: "compliance",
          severity: 5,
          likelihood: 2,
          note: "Liquor license and liability exposure if a busy bar skips ID checks or cutoffs.",
        },
      ],
      ideas: [
        {
          id: "i-bar-1",
          title: "Weekly pour-cost variance report to owner",
          category: "control",
          effort: "medium",
          impact: "high",
          note: "Compare bottles used to drinks rung; investigate anything over 3% variance.",
          status: "planned",
        },
        {
          id: "i-bar-2",
          title: "Cross-train GM on bar inventory counts",
          category: "training",
          effort: "low",
          impact: "medium",
          note: "Maya runs one weekly count with Riley so pars and variance are not single-owner.",
          status: "backlog",
        },
      ],
      wastes: [
        {
          id: "w-bar-1",
          kind: "muda_overprocessing",
          label: "Free-pouring instead of jiggers",
          note: "Inconsistent pours mean over-pours are given away and drinks are remade to taste.",
        },
      ],
    },
    {
      id: "proc-inventory",
      name: "Food inventory & prep",
      layer: "process",
      description: "Receiving, prep, waste, food cost.",
      dependencies: [],
      controlIds: [],
      stage: 1,
      ownerPersonIds: ["p4"],
      inputs: ["Vendor deliveries", "Prep lists", "Par levels"],
      outputs: ["Prepped mise en place", "Waste log", "Weekly food cost"],
      risks: [
        {
          id: "r-inv-1",
          title: "Deliveries accepted without checking against the order",
          kind: "control",
          severity: 3,
          likelihood: 4,
          note: "Short cases and weight shortages become food cost when nobody counts at the back door.",
        },
        {
          id: "r-inv-2",
          title: "Cold-chain and date-label gaps",
          kind: "safety",
          severity: 4,
          likelihood: 3,
          note: "Walk-in temps and FIFO labels are checked by memory, not a log; health inspection exposure.",
          linkedKnowledgeId: "k4",
        },
      ],
      ideas: [
        {
          id: "i-inv-1",
          title: "Back-door receiving checklist with scale",
          category: "control",
          effort: "low",
          impact: "high",
          note: "Count and weigh against the invoice before signing; note shorts for AP credit.",
          status: "planned",
        },
        {
          id: "i-inv-2",
          title: "Daily waste sheet by station",
          category: "lean",
          effort: "low",
          impact: "medium",
          note: "Log spoilage, over-prep, and remakes so prep pars can be tuned weekly.",
          status: "exploring",
        },
      ],
      wastes: [
        {
          id: "w-inv-1",
          kind: "mura",
          label: "Over-prep on slow nights, short on busy ones",
          note: "Prep lists do not use the reservation forecast, so spoilage and 86'd items both happen.",
        },
      ],
    },
    {
      id: "proc-cash",
      name: "Cash, tips & deposits",
      layer: "process",
      description: "Shift closeout, tip pool, bank deposits.",
      dependencies: [],
      controlIds: ["c-cash", "c-sod-cash"],
      stage: 2,
      ownerPersonIds: ["p3", "p2"],
      inputs: ["Server cash-outs", "POS Z-report", "Card tips"],
      outputs: ["Bank deposit", "Tip pool distribution"],
      risks: [
        {
          id: "r-cash-1",
          title: "Tip skimming / deposit mismatch",
          kind: "fraud",
          severity: 5,
          likelihood: 4,
          note: "Head server closes and deposits without independent review.",
          linkedControlId: "c-sod-cash",
          linkedScenarioId: "sc-cash-sod-failure",
          linkedKnowledgeId: "k1",
        },
        {
          id: "r-cash-2",
          title: "Tip pool math is one person's spreadsheet",
          kind: "continuity",
          severity: 4,
          likelihood: 3,
          note: "Only Jordan knows the split rules; disputes and wage claims spike if Jordan is out.",
          linkedKnowledgeId: "k1",
        },
      ],
      ideas: [
        {
          id: "i-cash-1",
          title: "Two-person drop with signed safe log",
          category: "control",
          effort: "low",
          impact: "high",
          note: "Closer counts, second person verifies and both initial the drop envelope.",
          status: "planned",
        },
        {
          id: "i-cash-2",
          title: "Owner matches deposits to Z-reports weekly",
          category: "control",
          effort: "low",
          impact: "high",
          note: "Elena checks the bank statement against nightly closeouts; catches skimming fast.",
          status: "exploring",
        },
      ],
      wastes: [
        {
          id: "w-cash-1",
          kind: "muda_overprocessing",
          label: "Tip pool recalculated by hand nightly",
          note: "Hours and sales are re-keyed from POS into a spreadsheet after every shift.",
        },
      ],
    },
    {
      id: "proc-ap",
      name: "Food & beverage AP",
      layer: "process",
      description: "Vendor invoices, liquor distributor, linen.",
      dependencies: [],
      controlIds: ["c-ap", "c-sod-ap"],
      stage: 3,
      ownerPersonIds: ["p2", "p6"],
      inputs: ["Vendor invoices", "Receiving sheets", "Delivery credits"],
      outputs: ["Paid vendors", "Food & bev cost report"],
      risks: [
        {
          id: "r-ap-1",
          title: "GM creates vendors and pays",
          kind: "fraud",
          severity: 5,
          likelihood: 3,
          note: "Fictitious food vendor path.",
          linkedControlId: "c-sod-ap",
          linkedScenarioId: "sc-vendor-fraud",
        },
        {
          id: "r-ap-2",
          title: "Delivery shortages never credited",
          kind: "revenue",
          severity: 3,
          likelihood: 4,
          note: "Shorts noted at the back door are not passed to the bookkeeper, so full invoices get paid.",
        },
      ],
      ideas: [
        {
          id: "i-ap-1",
          title: "Owner approves new vendors and bank changes",
          category: "policy",
          effort: "low",
          impact: "high",
          note: "Elena signs off before any vendor is added or ACH details change.",
          status: "planned",
        },
        {
          id: "i-ap-2",
          title: "Match invoice to receiving sheet before paying",
          category: "control",
          effort: "medium",
          impact: "medium",
          note: "Bookkeeper pays only invoices with a signed receiving sheet attached.",
          status: "backlog",
        },
      ],
      wastes: [
        {
          id: "w-ap-1",
          kind: "muda_waiting",
          label: "Invoices pile up in the office drawer",
          note: "Paper invoices wait a week or more before entry; late fees and lost credits.",
        },
      ],
    },
    {
      id: "proc-ar",
      name: "Comps & void adjustments",
      layer: "process",
      description: "Voids, discounts, event deposits.",
      dependencies: ["proc-service"],
      controlIds: ["c-sod-billing"],
      stage: 3,
      ownerPersonIds: ["p2"],
      inputs: ["Void requests", "Comp tickets", "Event contracts"],
      outputs: ["Nightly void/comp report", "Event deposit ledger"],
      risks: [
        {
          id: "r-ar-1",
          title: "Void/comp authority concentrated",
          kind: "fraud",
          severity: 4,
          likelihood: 4,
          note: "GM can void tickets without owner review.",
          linkedScenarioId: "sc-writeoff-abuse",
        },
        {
          id: "r-ar-2",
          title: "Event deposits not tracked to the booking",
          kind: "revenue",
          severity: 3,
          likelihood: 3,
          note: "Private-event deposits land in general sales; refunds and balances due are guesswork.",
        },
      ],
      ideas: [
        {
          id: "i-ar-1",
          title: "Manager-only void code with nightly void report",
          category: "control",
          effort: "low",
          impact: "high",
          note: "Servers cannot void after send; owner gets the void report by email each night.",
          status: "planned",
        },
        {
          id: "i-ar-2",
          title: "Simple event deposit log",
          category: "policy",
          effort: "low",
          impact: "medium",
          note: "One sheet per event: deposit date, amount, balance due, who collected.",
          status: "backlog",
        },
      ],
      wastes: [
        {
          id: "w-ar-1",
          kind: "muda_rework",
          label: "Re-ringing tickets to fix mistakes",
          note: "Order errors are voided and re-rung instead of modified, inflating void counts.",
        },
      ],
    },
    {
      id: "proc-payroll",
      name: "Payroll & tips reporting",
      layer: "process",
      description: "Hourly payroll, tip reporting, tip credit.",
      dependencies: [],
      controlIds: ["c-payroll"],
      stage: 4,
      ownerPersonIds: ["p2", "p1"],
      inputs: ["Time punches", "Declared tips", "Tip pool sheets"],
      outputs: ["Payroll file", "Tip reporting records"],
      risks: [
        {
          id: "r-pay-1",
          title: "Tip credit applied wrong",
          kind: "compliance",
          severity: 4,
          likelihood: 3,
          note: "Tipped staff below minimum wage after tip credit means back-pay and penalties.",
          linkedKnowledgeId: "k6",
        },
        {
          id: "r-pay-2",
          title: "GM edits punches and runs payroll alone",
          kind: "fraud",
          severity: 4,
          likelihood: 2,
          note: "No second review before export; ghost hours or buddy punches go unnoticed.",
        },
      ],
      ideas: [
        {
          id: "i-pay-1",
          title: "Owner reviews payroll summary before submit",
          category: "control",
          effort: "low",
          impact: "high",
          note: "Elena checks hours, tips, and any punch edits each period.",
          status: "planned",
        },
        {
          id: "i-pay-2",
          title: "Tip credit checklist per pay period",
          category: "training",
          effort: "low",
          impact: "medium",
          note: "One-page state rules so anyone can confirm every tipped employee clears minimum wage.",
          status: "exploring",
        },
      ],
      wastes: [
        {
          id: "w-pay-1",
          kind: "muda_rework",
          label: "Fixing missed punches after the fact",
          note: "Servers forget to clock out; GM reconstructs hours from the POS every period.",
        },
      ],
    },
  ],
  controls: baseFinancialControls(),
  staffComposition: { ...DEFAULT_STAFF, teamSize: 6, segregationScore: 35 },
  crimeFraudStats: fraudStats,
  scenarios: baseFraudScenarios(fraudStats.source, {
    keyPersonTitle: "Head server leaves with sole tip-pool knowledge",
    keyPersonDesc:
      "Jordan (sole expert on tip pooling and shift closeout) resigns mid-week. Deposits mismatch and tip disputes spike.",
    knowledgeId: "k1",
    billingLabel: "Void/comp authority without owner review",
  }),
  roleTemplates: {
    "Owner / Executive Chef": [
      "approve_writeoffs",
      "approve_vendor",
      "approve_payroll",
      "bank_reconcile",
      "view_reports_only",
    ],
    "General Manager": [
      "post_payments",
      "prepare_deposit",
      "post_adjustments",
      "create_vendor",
      "release_payment",
      "enter_payroll",
      "approve_writeoffs",
      "view_reports_only",
    ],
    "Head Server": ["collect_cash", "post_payments", "prepare_deposit", "post_adjustments"],
    "Line Cook Lead": ["view_reports_only"],
    "Bar Manager": ["collect_cash", "post_adjustments", "view_reports_only"],
    Bookkeeper: [
      "post_payments",
      "bank_reconcile",
      "post_adjustments",
      "view_reports_only",
    ],
  },
};
