import type { IndustryTemplate } from "./types";
import {
  baseFinancialControls,
  baseFraudScenarios,
  DEFAULT_FRAUD_STATS,
  DEFAULT_STAFF,
} from "./shared-controls";

const fraudStats = {
  ...DEFAULT_FRAUD_STATS,
  source:
    "Illustrative retail shrinkage and employee theft patterns (NRF, ACFE small retail orgs). Educational demo only.",
};

export const retailTemplate: IndustryTemplate = {
  id: "retail",
  businessName: "Harbor Lane Boutique",
  people: [
    { id: "p1", name: "Alex Rivera", role: "Owner", active: true, tenureYears: 9 },
    { id: "p2", name: "Sam Nguyen", role: "Store Manager", active: true, tenureYears: 5 },
    { id: "p3", name: "Jordan Lee", role: "Lead Cashier", active: true, tenureYears: 4 },
    { id: "p4", name: "Morgan Ellis", role: "Inventory Lead", active: true, tenureYears: 3 },
    { id: "p5", name: "Riley Park", role: "E-commerce Fulfillment", active: true, tenureYears: 2 },
    { id: "p6", name: "Chris Patel", role: "Bookkeeper", active: true, tenureYears: 3 },
  ],
  knowledge: [
    {
      id: "k1",
      name: "POS admin & returns policy",
      description: "Override codes, return fraud flags, end-of-day closeout.",
      criticality: "critical",
      category: "system",
      linkedProcessIds: ["proc-pos"],
    },
    {
      id: "k2",
      name: "Daily deposit & reconciliation",
      description: "Cash drawer, card batch matching, bank deposit process.",
      criticality: "critical",
      category: "process",
      linkedProcessIds: ["proc-cash"],
    },
    {
      id: "k3",
      name: "Inventory cycle counts",
      description: "Shrink tracking, receiving discrepancies, SKU adjustments.",
      criticality: "critical",
      category: "process",
      linkedProcessIds: ["proc-inventory"],
    },
    {
      id: "k4",
      name: "Vendor onboarding",
      description: "New supplier setup, payment terms, ACH details.",
      criticality: "important",
      category: "vendor",
      linkedProcessIds: ["proc-ap"],
    },
    {
      id: "k5",
      name: "E-commerce platform ops",
      description: "Shopify admin, refunds, inventory sync rules.",
      criticality: "important",
      category: "system",
      linkedProcessIds: ["proc-ecom"],
    },
    {
      id: "k6",
      name: "Markdown / discount authority",
      description: "Who can approve large discounts and price overrides.",
      criticality: "critical",
      category: "compliance",
      linkedProcessIds: ["proc-ar"],
    },
  ],
  relations: [
    { personId: "p3", knowledgeId: "k1", level: "expert" },
    { personId: "p3", knowledgeId: "k2", level: "expert" },
    { personId: "p2", knowledgeId: "k2", level: "proficient" },
    { personId: "p2", knowledgeId: "k1", level: "proficient" },
    { personId: "p4", knowledgeId: "k3", level: "expert" },
    { personId: "p5", knowledgeId: "k5", level: "expert" },
    { personId: "p2", knowledgeId: "k4", level: "expert" },
    { personId: "p6", knowledgeId: "k6", level: "expert" },
    { personId: "p6", knowledgeId: "k4", level: "basic" },
  ],
  processes: [
    {
      id: "proc-pos",
      name: "POS sales & returns",
      layer: "process",
      description: "In-store sales, returns, and drawer management.",
      dependencies: [],
      controlIds: ["c-cash"],
      stage: 0,
      ownerPersonIds: ["p3", "p2"],
      risks: [
        {
          id: "r-pos-1",
          title: "Return fraud / sweethearting",
          kind: "fraud",
          severity: 4,
          likelihood: 3,
          note: "Lead cashier sole expert on override codes.",
          linkedKnowledgeId: "k1",
        },
      ],
      ideas: [
        {
          id: "i-pos-1",
          title: "Camera at POS + manager override log",
          category: "control",
          effort: "low",
          impact: "high",
          note: "Daily review of overrides > $50.",
          status: "planned",
        },
      ],
    },
    {
      id: "proc-inventory",
      name: "Receiving & inventory",
      layer: "process",
      description: "Stock receiving, counts, and shrink tracking.",
      dependencies: ["proc-pos"],
      controlIds: ["c-ar"],
      stage: 1,
      ownerPersonIds: ["p4"],
      risks: [
        {
          id: "r-inv-1",
          title: "Receiving without PO match",
          kind: "fraud",
          severity: 4,
          likelihood: 3,
          note: "Inventory lead can receive and adjust without second count.",
        },
      ],
    },
    {
      id: "proc-ecom",
      name: "E-commerce fulfillment",
      layer: "process",
      description: "Online orders, refunds, and inventory sync.",
      dependencies: ["proc-inventory"],
      controlIds: [],
      stage: 2,
      ownerPersonIds: ["p5"],
      risks: [
        {
          id: "r-ecom-1",
          title: "Refund abuse path",
          kind: "fraud",
          severity: 3,
          likelihood: 3,
          note: "Single person can refund and adjust inventory.",
          linkedKnowledgeId: "k5",
        },
      ],
    },
    {
      id: "proc-cash",
      name: "Cash handling & deposits",
      layer: "process",
      description: "Drawer counts, card batches, bank deposits.",
      dependencies: [],
      controlIds: ["c-cash", "c-sod-cash"],
      stage: 2,
      ownerPersonIds: ["p3"],
      risks: [
        {
          id: "r-cash-1",
          title: "Posting + recon not segregated",
          kind: "fraud",
          severity: 5,
          likelihood: 4,
          note: "Classic retail skimming opportunity.",
          linkedControlId: "c-sod-cash",
          linkedScenarioId: "sc-cash-sod-failure",
        },
      ],
    },
    {
      id: "proc-ap",
      name: "Accounts payable",
      layer: "process",
      description: "Vendor invoices, freight, supplier payments.",
      dependencies: [],
      controlIds: ["c-ap", "c-sod-ap"],
      stage: 3,
      ownerPersonIds: ["p2", "p6"],
      risks: [
        {
          id: "r-ap-1",
          title: "Vendor setup + payment same person",
          kind: "fraud",
          severity: 5,
          likelihood: 3,
          note: "Fictitious vendor path.",
          linkedControlId: "c-sod-ap",
          linkedScenarioId: "sc-vendor-fraud",
        },
      ],
    },
    {
      id: "proc-ar",
      name: "Adjustments & markdowns",
      layer: "process",
      description: "Price overrides, markdowns, shrink write-offs.",
      dependencies: ["proc-pos"],
      controlIds: ["c-sod-billing", "c-sod-ar"],
      stage: 3,
      ownerPersonIds: ["p6"],
      risks: [
        {
          id: "r-ar-1",
          title: "Undocumented markdowns",
          kind: "fraud",
          severity: 4,
          likelihood: 3,
          note: "Bookkeeper posts adjustments without owner review.",
          linkedKnowledgeId: "k6",
          linkedScenarioId: "sc-writeoff-abuse",
        },
      ],
    },
    {
      id: "proc-payroll",
      name: "Payroll",
      layer: "process",
      description: "Hourly staff, commissions, payroll export.",
      dependencies: [],
      controlIds: ["c-payroll"],
      stage: 4,
      ownerPersonIds: ["p2", "p1"],
    },
  ],
  controls: baseFinancialControls(),
  staffComposition: { ...DEFAULT_STAFF },
  crimeFraudStats: fraudStats,
  scenarios: baseFraudScenarios(fraudStats.source, {
    keyPersonTitle: "Lead cashier leaves with sole POS/returns knowledge",
    keyPersonDesc:
      "Jordan (sole expert on POS overrides and return policy) resigns with 2 weeks notice. No cross-training documented.",
    knowledgeId: "k1",
    billingLabel: "Markdown / adjustment authority without dual control",
  }),
  roleTemplates: {
    Owner: [
      "approve_writeoffs",
      "approve_vendor",
      "approve_payroll",
      "bank_reconcile",
      "view_reports_only",
    ],
    "Store Manager": [
      "post_payments",
      "prepare_deposit",
      "post_adjustments",
      "create_vendor",
      "release_payment",
      "enter_payroll",
      "approve_writeoffs",
      "view_reports_only",
    ],
    "Lead Cashier": [
      "collect_cash",
      "post_payments",
      "prepare_deposit",
      "post_adjustments",
    ],
    "Inventory Lead": ["view_reports_only"],
    "E-commerce Fulfillment": ["post_adjustments", "view_reports_only"],
    Bookkeeper: [
      "post_adjustments",
      "post_payments",
      "approve_writeoffs",
      "create_vendor",
      "release_payment",
      "view_reports_only",
    ],
  },
};
