import type { IndustrySample } from "./types";
import { baseFinancialControls, baseFraudScenarios, SAMPLE_SAFEGUARDS } from "./shared-controls";

/**
 * A clothing boutique of about six people: the owner, a store manager who
 * handles vendors, deposits and payroll, a lead cashier who knows the
 * register overrides, an inventory lead, web-store fulfillment and a
 * bookkeeper. It uses the shared controls and scenarios, and adds a receiving
 * and count check of its own.
 */
export const retailTemplate: IndustrySample = {
  id: "retail",
  people: [
    { id: "p1", name: "Alex Rivera", role: "Owner", active: true, tenureYears: 9 },
    { id: "p2", name: "Sam Nguyen", role: "Store Manager", active: true, tenureYears: 5 },
    { id: "p3", name: "Jordan Lee", role: "Lead Cashier", active: true, tenureYears: 4 },
    { id: "p4", name: "Morgan Ellis", role: "Inventory Lead", active: true, tenureYears: 3 },
    { id: "p5", name: "Riley Park", role: "E-commerce Fulfillment", active: true, tenureYears: 2 },
    { id: "p6", name: "Chris Patel", role: "Bookkeeper", active: true, tenureYears: 3 },
  ],
  roleTemplates: {
    Owner: [
      "approve_writeoffs",
      "approve_vendor",
      "approve_payroll",
      "approve_expenses",
      "bank_reconcile",
      "view_reports_only",
    ],
    "Store Manager": [
      "post_payments",
      "prepare_deposit",
      "post_adjustments",
      "create_vendor",
      "release_payment",
      "enter_payroll",
      "approve_writeoffs",
      "hold_company_card",
      "view_reports_only",
    ],
    "Lead Cashier": ["collect_cash", "post_payments", "prepare_deposit", "post_adjustments"],
    "Inventory Lead": ["view_reports_only"],
    "E-commerce Fulfillment": ["post_adjustments", "view_reports_only"],
    Bookkeeper: [
      "post_adjustments",
      "post_payments",
      "approve_writeoffs",
      "bank_reconcile",
      "create_vendor",
      "release_payment",
      "review_card_statement",
      "view_reports_only",
    ],
  },
  knowledge: [
    {
      id: "k1",
      name: "POS admin & returns policy",
      description: "Override codes, return fraud flags, end-of-day closeout.",
      criticality: "critical",
      category: "system",
      linkedProcessIds: ["proc-pos"],
    },
    {
      id: "k2",
      name: "Daily deposit & reconciliation",
      description: "Cash drawer, card batch matching, bank deposit process.",
      criticality: "critical",
      category: "process",
      linkedProcessIds: ["proc-cash"],
    },
    {
      id: "k3",
      name: "Inventory cycle counts",
      description: "Shrink tracking, receiving discrepancies, SKU adjustments.",
      criticality: "critical",
      category: "process",
      linkedProcessIds: ["proc-inventory"],
    },
    {
      id: "k4",
      name: "Vendor onboarding",
      description: "New supplier setup, payment terms, ACH details.",
      criticality: "important",
      category: "vendor",
      linkedProcessIds: ["proc-ap"],
    },
    {
      id: "k5",
      name: "E-commerce platform ops",
      description: "Web store admin, refunds, inventory sync rules.",
      criticality: "important",
      category: "system",
      linkedProcessIds: ["proc-ecom"],
    },
    {
      id: "k6",
      name: "Markdown / discount authority",
      description: "Who can approve large discounts and price overrides.",
      criticality: "critical",
      category: "compliance",
      linkedProcessIds: ["proc-ar"],
    },
  ],
  relations: [
    { personId: "p3", knowledgeId: "k1", level: "expert" },
    { personId: "p3", knowledgeId: "k2", level: "expert" },
    { personId: "p2", knowledgeId: "k2", level: "proficient" },
    { personId: "p2", knowledgeId: "k1", level: "basic" },
    { personId: "p4", knowledgeId: "k3", level: "expert" },
    { personId: "p5", knowledgeId: "k5", level: "expert" },
    { personId: "p2", knowledgeId: "k4", level: "expert" },
    { personId: "p6", knowledgeId: "k6", level: "expert" },
    { personId: "p6", knowledgeId: "k4", level: "basic" },
  ],
  processes: [
    {
      id: "proc-pos",
      name: "POS sales & returns",
      layer: "process",
      description: "In-store sales, returns, and drawer management.",
      dependencies: [],
      controlIds: ["c-cash"],
      stage: 0,
      ownerPersonIds: ["p3", "p2"],
      inputs: ["Customer purchases", "Drawer float", "Return receipts"],
      outputs: ["Tendered sales", "Return credits", "End-of-day register report"],
      risks: [
        {
          id: "r-pos-1",
          title: "Return fraud and discounts for friends",
          kind: "fraud",
          severity: 4,
          likelihood: 3,
          note: "The lead cashier is the sole expert on override codes.",
          linkedKnowledgeId: "k1",
          linkedScenarioId: "sc-key-person-leaves",
        },
        {
          id: "r-pos-2",
          title: "No-receipt returns to store credit",
          kind: "control",
          severity: 3,
          likelihood: 4,
          note: "Gift-card refunds on no-receipt returns are untraceable once issued; no cap or ID capture today.",
        },
      ],
      ideas: [
        {
          id: "i-pos-1",
          title: "Camera at POS + manager override log",
          category: "control",
          effort: "low",
          impact: "high",
          note: "Daily review of overrides above the amount you set.",
          status: "planned",
        },
        {
          id: "i-pos-2",
          title: "Cross-train second cashier on override codes",
          category: "training",
          effort: "low",
          impact: "medium",
          note: "The store manager shadows the lead cashier for two closes; write a one-page returns cheat sheet.",
          status: "backlog",
        },
      ],
      wastes: [
        {
          id: "w-pos-1",
          kind: "muda_waiting",
          label: "Line stalls waiting for manager override",
          note: "Customers wait while a manager is paged for any price change or return.",
        },
      ],
    },
    {
      id: "proc-inventory",
      name: "Receiving & inventory",
      layer: "process",
      description: "Stock receiving, counts, and shrink tracking.",
      dependencies: ["proc-pos"],
      controlIds: ["c-inventory"],
      stage: 1,
      ownerPersonIds: ["p4"],
      inputs: ["Purchase orders", "Vendor shipments", "Packing slips"],
      outputs: ["On-hand counts", "Shrink report"],
      risks: [
        {
          id: "r-inv-1",
          title: "Receiving without PO match",
          kind: "fraud",
          severity: 4,
          likelihood: 3,
          note: "Inventory lead can receive and adjust without second count.",
          linkedControlId: "c-inventory",
        },
        {
          id: "r-inv-2",
          title: "Inventory lead is sole counter",
          kind: "continuity",
          severity: 3,
          likelihood: 3,
          note: "Often only the inventory lead runs cycle counts; shrink goes unmeasured when they are out.",
          linkedKnowledgeId: "k3",
        },
      ],
      ideas: [
        {
          id: "i-inv-1",
          title: "Blind receiving against the PO",
          category: "control",
          effort: "low",
          impact: "high",
          note: "Receiver counts before seeing PO quantities; manager reconciles differences.",
          status: "exploring",
        },
        {
          id: "i-inv-2",
          title: "Weekly cycle counts on top 20 SKUs",
          category: "lean",
          effort: "medium",
          impact: "medium",
          note: "Replace the painful annual count with small rotating counts; flag shrink early.",
          status: "backlog",
        },
      ],
      wastes: [
        {
          id: "w-inv-1",
          kind: "muda_motion",
          label: "Backroom hunt for stock",
          note: "Unlabeled bins mean staff walk the back twice to find sizes for the floor.",
        },
      ],
    },
    {
      id: "proc-ecom",
      name: "E-commerce fulfillment",
      layer: "process",
      description: "Online orders, refunds, and inventory sync.",
      dependencies: ["proc-inventory"],
      controlIds: [],
      stage: 2,
      ownerPersonIds: ["p5"],
      inputs: ["Online orders", "Shared inventory", "Shipping supplies"],
      outputs: ["Shipped orders", "Refunds issued"],
      risks: [
        {
          id: "r-ecom-1",
          title: "Refund abuse path",
          kind: "fraud",
          severity: 3,
          likelihood: 3,
          note: "Single person can refund and adjust inventory.",
          linkedKnowledgeId: "k5",
        },
        {
          id: "r-ecom-2",
          title: "Oversell from stale inventory sync",
          kind: "quality",
          severity: 3,
          likelihood: 3,
          note: "Floor sales and web sales race for the last unit; cancellations and bad reviews follow.",
        },
      ],
      ideas: [
        {
          id: "i-ecom-1",
          title: "Refunds above the amount you set need the store manager's approval",
          category: "control",
          effort: "low",
          impact: "medium",
          note: "Use the web store's staff permissions so fulfillment can request and the store manager approves.",
          status: "planned",
        },
        {
          id: "i-ecom-2",
          title: "Batch-pick orders twice a day",
          category: "lean",
          effort: "low",
          impact: "medium",
          note: "One pick list at 11am and 3pm instead of one-at-a-time trips to the floor.",
          status: "backlog",
        },
      ],
      wastes: [
        {
          id: "w-ecom-1",
          kind: "muda_rework",
          label: "Cancel-and-refund on oversells",
          note: "Each oversell means an apology email, a refund, and an inventory fix.",
        },
      ],
    },
    {
      id: "proc-cash",
      name: "Cash handling & deposits",
      layer: "process",
      description: "Drawer counts, card batches, bank deposits.",
      dependencies: [],
      controlIds: ["c-cash", "c-sod-cash"],
      stage: 2,
      ownerPersonIds: ["p3"],
      inputs: ["Drawer cash", "Card batch totals", "End-of-day register report"],
      outputs: ["Bank deposit", "Over/short log"],
      risks: [
        {
          id: "r-cash-1",
          title: "One person posts payments and reconciles the bank",
          kind: "fraud",
          severity: 5,
          likelihood: 4,
          note: "The classic path to skimming in a store.",
          linkedControlId: "c-sod-cash",
          linkedScenarioId: "sc-cash-sod-failure",
        },
        {
          id: "r-cash-2",
          title: "Deposits sit in the safe for days",
          kind: "control",
          severity: 3,
          likelihood: 3,
          note: "No fixed deposit cadence; theft or loss is hard to pin to a shift.",
          linkedKnowledgeId: "k2",
        },
      ],
      ideas: [
        {
          id: "i-cash-1",
          title: "Blind drawer counts at shift change",
          category: "control",
          effort: "low",
          impact: "high",
          note: "Cashier counts without seeing the POS expected total; manager compares.",
          status: "planned",
        },
        {
          id: "i-cash-2",
          title: "Owner reviews bank statement weekly",
          category: "control",
          effort: "low",
          impact: "high",
          note: "The owner compares each deposit to the end-of-day register report before the bookkeeper posts it, so a short deposit surfaces the same day.",
          status: "exploring",
        },
      ],
      wastes: [
        {
          id: "w-cash-1",
          kind: "muda_overprocessing",
          label: "Recount the same drawer three times",
          note: "Cashier, manager, and bookkeeper each recount from scratch with no shared tally sheet.",
        },
      ],
    },
    {
      id: "proc-ap",
      name: "Accounts payable",
      layer: "process",
      description: "Vendor invoices, freight, supplier payments.",
      dependencies: [],
      controlIds: ["c-ap", "c-sod-ap"],
      stage: 3,
      ownerPersonIds: ["p2", "p6"],
      inputs: ["Vendor invoices", "Receiving records", "Freight bills"],
      outputs: ["Paid vendors", "Unpaid bills by age"],
      risks: [
        {
          id: "r-ap-1",
          title: "One person sets up vendors and pays them",
          kind: "fraud",
          severity: 5,
          likelihood: 3,
          note: "A fake vendor can be set up and paid.",
          linkedControlId: "c-sod-ap",
          linkedScenarioId: "sc-vendor-fraud",
        },
        {
          id: "r-ap-2",
          title: "Paying invoices that were short-shipped",
          kind: "control",
          severity: 3,
          likelihood: 3,
          note: "Invoices are approved without checking the receiving count; vendor shortages become our cost.",
        },
      ],
      ideas: [
        {
          id: "i-ap-1",
          title: "Three-way match: PO, receipt, invoice",
          category: "control",
          effort: "medium",
          impact: "high",
          note: "Bookkeeper pays only when all three agree; exceptions go to owner.",
          status: "planned",
        },
        {
          id: "i-ap-2",
          title: "Owner approves any new vendor bank details",
          category: "policy",
          effort: "low",
          impact: "high",
          note: "Callback to a known vendor phone number before ACH changes.",
          status: "backlog",
        },
      ],
      wastes: [
        {
          id: "w-ap-1",
          kind: "muri",
          label: "Store manager owns vendors and payments alone",
          note: "Often only the store manager knows vendor terms; bills go unpaid when they are off.",
        },
      ],
    },
    {
      id: "proc-ar",
      name: "Adjustments & markdowns",
      layer: "process",
      description: "Price overrides, markdowns, shrink write-offs.",
      dependencies: ["proc-pos"],
      controlIds: ["c-sod-billing", "c-sod-ar"],
      stage: 3,
      ownerPersonIds: ["p6"],
      inputs: ["Markdown requests", "Shrink counts", "Price override log"],
      outputs: ["Posted adjustments", "Markdown report"],
      risks: [
        {
          id: "r-ar-1",
          title: "Undocumented markdowns",
          kind: "fraud",
          severity: 4,
          likelihood: 3,
          note: "Bookkeeper posts adjustments without owner review.",
          linkedKnowledgeId: "k6",
          linkedScenarioId: "sc-writeoff-abuse",
        },
        {
          id: "r-ar-2",
          title: "Shrink written off without a count",
          kind: "control",
          severity: 3,
          likelihood: 3,
          note: "Write-offs hide theft when nobody verifies the missing units on the shelf.",
        },
      ],
      ideas: [
        {
          id: "i-ar-1",
          title: "Reason codes on every markdown",
          category: "control",
          effort: "low",
          impact: "high",
          note: "Damaged, seasonal, price-match, or other; owner reviews the monthly report by code.",
          status: "planned",
        },
        {
          id: "i-ar-2",
          title: "Owner signs off on write-offs above the amount you set",
          category: "policy",
          effort: "low",
          impact: "high",
          note: "Simple threshold; anything above it needs the owner's initials.",
          status: "exploring",
        },
      ],
      wastes: [
        {
          id: "w-ar-1",
          kind: "mura",
          label: "Month-end markdown pile-up",
          note: "The bookkeeper batches adjustments at month end instead of posting them as they happen.",
        },
      ],
    },
    {
      id: "proc-payroll",
      name: "Payroll",
      layer: "process",
      description: "Hourly staff, commissions, payroll export.",
      dependencies: [],
      controlIds: ["c-payroll"],
      stage: 4,
      ownerPersonIds: ["p2", "p1"],
      inputs: ["Time punches", "Commission sales data", "Schedule changes"],
      outputs: ["Payroll file", "Pay stubs"],
      risks: [
        {
          id: "r-pay-1",
          title: "Manager edits own hours and commissions",
          kind: "fraud",
          severity: 4,
          likelihood: 2,
          note: "The store manager enters payroll and can adjust punches with no second look before export.",
        },
        {
          id: "r-pay-2",
          title: "Commission rules live in one head",
          kind: "continuity",
          severity: 3,
          likelihood: 3,
          note: "Split-sale and return-clawback rules are not written down.",
        },
      ],
      ideas: [
        {
          id: "i-pay-1",
          title: "Owner approves payroll before export",
          category: "control",
          effort: "low",
          impact: "high",
          note: "The owner reviews the hours and commission summary each period.",
          status: "planned",
        },
        {
          id: "i-pay-2",
          title: "Write down commission rules",
          category: "training",
          effort: "low",
          impact: "medium",
          note: "One-page rulebook so anyone can run a cycle.",
          status: "backlog",
        },
      ],
      wastes: [
        {
          id: "w-pay-1",
          kind: "muda_rework",
          label: "Manual commission spreadsheet",
          note: "Someone re-keys sales from the register into a spreadsheet every pay period.",
        },
      ],
    },
  ],
  controls: [
    // Invoices are paid without the receiving count today (r-ap-2); the
    // three-way match that would do it is still planned (i-ap-1).
    ...baseFinancialControls({ "c-ap": { segregated: false } }),
    {
      id: "c-inventory",
      name: "Receiving and count check",
      description:
        "Someone other than the receiver counts each delivery against the purchase order, and someone who does not adjust stock checks the cycle counts.",
      duties: ["review", "reconciliation"],
      segregated: false,
      compensatingControls: [],
      residualRiskAccepted: false,
    },
  ],
  staffComposition: SAMPLE_SAFEGUARDS,
  scenarios: baseFraudScenarios({
    keyPersonTitle: "Lead cashier leaves with sole register and returns knowledge",
    keyPersonDesc:
      "The lead cashier (sole expert on POS overrides and return policy) resigns with two weeks' notice. Nobody else has been trained.",
    knowledgeId: "k1",
    billingLabel: "Markdowns and adjustments posted without a second approval",
  }),
};
