import { chromium } from "playwright";
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1366, height: 900 } });
const errors = [];
page.on("pageerror", (e) => errors.push("page: " + String(e)));
page.on("console", (m) => { if (m.type() === "error") errors.push("console: " + m.text().slice(0, 200)); });
await page.goto("http://127.0.0.1:8080/", { waitUntil: "networkidle" });
await page.evaluate(() => localStorage.clear());
await page.reload({ waitUntil: "networkidle" });
const pick = page.getByRole("button", { name: /^Auto dealership/ }).first();
console.log("industry card present:", await pick.count());
const cardText = (await pick.innerText()).replace(/\s+/g, " ");
console.log("card:", cardText);
await pick.click();
await page.getByRole("button", { name: /^Load .* demo$/ }).click();
await page.locator("nav button").first().waitFor();
await page.waitForTimeout(1200);
await page.screenshot({ path: "/workspace/screenshots/auto-start-here.png" });
const body = (await page.locator("body").innerText()).replace(/\s+/g, " ");
const i = body.indexOf("Where one person controls too much");
console.log("START HERE gaps:", body.slice(i, i + 700));
await page.goto("http://127.0.0.1:8080/?tab=sod", { waitUntil: "networkidle" });
await page.waitForTimeout(800);
const sod = (await page.locator("body").innerText()).replace(/\s+/g, " ");
for (const t of ["Repair-order", "Linda Marsh", "Keisha Bell", "Marco Bianchi", "Dealership $", "Auto dealership"]) console.log(t, "=>", sod.includes(t));
const j = sod.indexOf("in your line of business");
console.log("own-sector heading:", j >= 0, sod.slice(Math.max(0, j - 200), j + 120));
await page.screenshot({ path: "/workspace/screenshots/auto-sod.png" });
await page.goto("http://127.0.0.1:8080/?tab=map", { waitUntil: "networkidle" });
await page.waitForTimeout(1500);
const map = (await page.locator("body").innerText()).replace(/\s+/g, " ");
for (const t of ["Service write-up & repair orders", "Parts ordering, receiving & counter sales", "Vehicle sales, deposits & F&I", "Title, registration & fee remittance"]) console.log("map has", t, "=>", map.includes(t));
await page.screenshot({ path: "/workspace/screenshots/auto-map.png" });
console.log("ERRORS:", JSON.stringify(errors));
await browser.close();
