import type { EntitlementId } from "../sod/conflict-rules";
import { ENTITLEMENTS } from "../sod/conflict-rules";

/**
 * Common job titles and the money duties each one typically holds in a
 * business of two to fifty people, so an owner can set up the whole team
 * from a roster instead of ticking duties one person at a time.
 *
 * What stands behind it. Workday, SAP SuccessFactors, and Oracle HCM Cloud
 * ship no public list of job descriptions: every customer builds its own job
 * catalog. What those systems do share is the shape of a worker export (a
 * name, a job title or job profile, a department, a status, a hire date),
 * and the titles that fill them come from the same small pool in a small
 * business. This catalog takes that pool and, where a title corresponds to
 * an occupation in the U.S. Bureau of Labor Statistics Standard Occupational
 * Classification (SOC 2018, the taxonomy O*NET uses), records the code so
 * the mapping can be checked against a public reference.
 *
 * The duties are this app's reading of what such a title usually carries,
 * not a rule. They are a starting point the owner corrects in the grid; a
 * title never grants a duty the owner has unticked.
 */
export type JobFamily =
  | "leadership"
  | "finance"
  | "office"
  | "sales"
  | "clinical"
  | "food"
  | "retail"
  | "trades"
  | "it"
  | "people"
  | "legal"
  | "professional"
  | "hospitality"
  | "automotive"
  | "property"
  | "nonprofit"
  | "marketing"
  | "education";

export interface JobCatalogEntry {
  id: string;
  title: string;
  family: JobFamily;
  /** Other names the same job goes by on rosters and HR exports (lower case). */
  aliases: readonly string[];
  /**
   * SOC 2018 code where the title corresponds to one occupation; for a title
   * that names several, the code of the one named first.
   */
  soc?: string;
  /** Duties this title typically holds in a small business. */
  entitlements: readonly EntitlementId[];
  /** One sentence on why, so the owner can disagree with a reason in front of them. */
  note: string;
  /**
   * What the job does, in one plain sentence: the standard description an HR
   * system's job profile would carry, shown with the note. It may paraphrase
   * the Bureau of Labor Statistics definition of the job's SOC occupation.
   */
  description: string;
}

export const JOB_FAMILY_LABEL: Record<JobFamily, string> = {
  leadership: "Owners and managers",
  finance: "Finance and accounting",
  office: "Front office and administration",
  sales: "Sales and customer service",
  clinical: "Clinical and patient care",
  food: "Restaurant and food service",
  retail: "Retail",
  trades: "Trades, field, and construction",
  it: "IT and systems",
  people: "Human resources",
  legal: "Legal",
  professional: "Professional and project staff",
  hospitality: "Hotels and hospitality",
  automotive: "Auto dealership and service",
  property: "Property and real estate",
  nonprofit: "Nonprofit and association",
  marketing: "Marketing and communications",
  education: "Education and childcare",
};

/** The catalog entry with this id. */
export function jobCatalogEntry(id: string): JobCatalogEntry | undefined {
  return BY_ID.get(id);
}

/** Every entitlement id the catalog cites exists in the rulebook; checked by the tests. */
export function jobCatalogUnknownEntitlements(): string[] {
  const known = new Set<string>(ENTITLEMENTS.map((e) => e.id));
  return JOB_CATALOG.flatMap((e) => e.entitlements.filter((id) => !known.has(id)));
}

/**
 * The catalog, one section per job family in the order the dropdowns show
 * them. The description says what the job does; the note says why the duties
 * are ticked and when to tick more, so the owner can disagree with a reason
 * in front of them.
 */
export const JOB_CATALOG: readonly JobCatalogEntry[] = [
  // Owners and managers
  {
    id: "owner",
    title: "Owner / Principal",
    family: "leadership",
    entitlements: [
      "approve_vendor",
      "approve_payroll",
      "approve_writeoffs",
      "approve_expenses",
      "sign_checks",
      "view_reports_only",
    ],
    description:
      "Owns the business, sets its policies, and holds final authority over spending, hiring, and pay.",
    note: "The owner approves last, usually signs, and approves the team's expense claims and card spending. Tick Spend on a company card or charge account if you hold a card, Reconcile the bank account if you check the statement against the books yourself, and Create users / assign system access if you give people their logins.",
    aliases: [
      "owner",
      "proprietor",
      "principal",
      "founder",
      "co-founder",
      "ceo",
      "chief executive officer",
      "president",
      "managing member",
      "managing partner",
      "partner",
      "practice owner",
      "owner dentist",
      "dentist owner",
      "owner operator",
      "co owner",
      "working owner",
      "sole proprietor",
      "franchise owner",
      "franchisee",
      "dealer principal",
      "dealer",
      "franchise dealer",
      "physician owner",
      "owner physician",
      "owner veterinarian",
      "equity partner",
      "name partner",
      "founding partner",
    ],
  },
  {
    id: "general-manager",
    title: "General / Operations Manager",
    family: "leadership",
    soc: "11-1021",
    entitlements: [
      "approve_vendor",
      "approve_writeoffs",
      "approve_payroll",
      "order_supplies",
      "hold_company_card",
      "approve_expenses",
      "manage_user_access",
      "view_reports_only",
    ],
    description:
      "Plans, directs, and coordinates the operations of the business, including budgeting, purchasing, and staffing, without a single functional specialty.",
    note: "A general manager approves spending, write-offs, and payroll and often controls who has system access. They usually hold a company card and approve the team's expense claims, so unless the owner reads their statement, their own spending answers to nobody.",
    aliases: [
      "general manager",
      "gm",
      "operations manager",
      "director of operations",
      "operations director",
      "coo",
      "chief operating officer",
      "practice administrator",
      "business manager",
      "regional manager",
      "district manager",
      "area manager",
      "plant manager",
      "multi unit manager",
      "vp operations",
      "vice president of operations",
      "vice president",
      "vp",
    ],
  },
  // Finance and accounting
  {
    id: "controller",
    title: "Controller / Finance Manager",
    family: "finance",
    soc: "11-3031",
    entitlements: [
      "release_payment",
      "bank_reconcile",
      "post_journal_entries",
      "sign_checks",
      "review_audit_logs",
      "review_card_statement",
      "approve_expenses",
      "view_reports_only",
    ],
    description:
      "Plans, directs, and coordinates the accounting, reporting, and banking of the business and prepares its financial statements.",
    note: "A controller releases payments, signs, posts journal entries, reconciles the bank, codes the card statements, and approves expense claims: a wide seat that the case library shows needs an owner reading the statement. Approving payroll and new suppliers stays with the owner in a small business; tick Approve payroll and Approve new suppliers if your controller does them.",
    aliases: [
      "controller",
      "comptroller",
      "finance manager",
      "finance director",
      "director of finance",
      "fractional cfo",
      "accounting manager",
      "head of finance",
      "assistant controller",
      "accounting supervisor",
    ],
  },
  {
    id: "cfo",
    title: "Chief Financial Officer",
    family: "finance",
    soc: "11-3031",
    entitlements: ["approve_vendor", "approve_expenses", "sign_checks", "view_reports_only"],
    description:
      "Directs the finances of the business, approves spending and suppliers, and signs or approves payments.",
    note: "A CFO approves new suppliers and expense claims and signs or gives the second approval on payments; the controller or bookkeeper records, releases and reconciles. Tick Approve payroll if the CFO approves each run.",
    aliases: ["cfo", "vp finance", "vice president of finance"],
  },
  {
    id: "accountant",
    title: "Accountant",
    family: "finance",
    soc: "13-2011",
    entitlements: [
      "post_journal_entries",
      "bank_reconcile",
      "post_adjustments",
      "enter_invoices",
      "review_card_statement",
      "view_reports_only",
    ],
    description:
      "Examines, analyzes, and interprets accounting records, prepares financial statements, and posts the entries that keep the ledger true.",
    note: "An accountant posts entries and write-offs, codes the card statements, reconciles, and enters supplier bills where no payables clerk does; whether the same person also pays is the question the map answers.",
    aliases: [
      "staff accountant",
      "senior accountant",
      "general ledger accountant",
      "gl accountant",
      "cpa",
      "certified public accountant",
      "cost accountant",
      "tax accountant",
      "accounting analyst",
      "financial analyst",
      "reconciliation specialist",
      "reconciliation clerk",
      "bank reconciliation specialist",
      "reconciliation analyst",
      "property accountant",
      "grants accountant",
      "trust accountant",
    ],
  },
  {
    id: "bookkeeper",
    title: "Bookkeeper",
    family: "finance",
    soc: "43-3031",
    entitlements: [
      "post_payments",
      "enter_invoices",
      "create_vendor",
      "release_payment",
      "bank_reconcile",
      "enter_payroll",
      "post_journal_entries",
      "review_card_statement",
      "view_reports_only",
    ],
    description:
      "Computes, classifies, and records financial transactions, keeps the ledger, and in a small business also pays bills and runs payroll.",
    note: "A full-charge bookkeeper in a small business records receipts, adds the suppliers whose bills they enter, pays the bills, runs payroll, codes the card statement, and reconciles the bank, which is every side of the ledger in one seat. In a store the till records sales, so you decide whether to tick Record payments received.",
    aliases: [
      "full charge bookkeeper",
      "accounting clerk",
      "accounting assistant",
      "accounting specialist",
      "accounting associate",
      "accounting coordinator",
      "junior accountant",
      "finance assistant",
      "finance coordinator",
      "finance clerk",
      "accounting",
      "finance and operations manager",
      "director of finance and operations",
      "finance and administration manager",
    ],
  },
  {
    id: "accounts-payable",
    title: "Accounts Payable Specialist",
    family: "finance",
    soc: "43-3031",
    entitlements: ["enter_invoices", "create_vendor", "view_reports_only"],
    description:
      "Enters supplier invoices, sets up suppliers, matches invoices to orders and receipts, and prepares payments for release.",
    note: "Accounts payable enters invoices, sets up suppliers and prepares the payment run; tick Release payments if they also send the payments. The shell-vendor cases run through this seat.",
    aliases: [
      "accounts payable",
      "accounts payable clerk",
      "accounts payable coordinator",
      "accounts payable analyst",
      "ap specialist",
      "ap clerk",
      "ap coordinator",
      "ap analyst",
      "payables clerk",
      "payables specialist",
      "disbursements clerk",
      "ap",
      "ap manager",
      "accounts payable manager",
      "ap supervisor",
      "ap lead",
      "payables manager",
    ],
  },
  {
    id: "accounts-receivable",
    title: "Accounts Receivable / Collections",
    family: "finance",
    soc: "43-3031",
    entitlements: ["post_payments", "post_adjustments", "view_reports_only"],
    description:
      "Records customer payments, follows up on unpaid balances, and posts the adjustments and credits that settle accounts.",
    note: "Receivables posts what customers pay and adjusts what they owe, which is where lapping and write-off cover happen; a manager or the owner approves refunds of credit balances unless you tick Issue customer refunds.",
    aliases: [
      "accounts receivable",
      "accounts receivable specialist",
      "accounts receivable clerk",
      "accounts receivable coordinator",
      "ar specialist",
      "ar clerk",
      "ar coordinator",
      "collections specialist",
      "collections",
      "collector",
      "credit and collections",
      "credit analyst",
      "ar",
      "ar manager",
      "accounts receivable manager",
      "credit manager",
      "collections manager",
      "credit and collections manager",
      "cash applications",
      "cash applications specialist",
      "cash application specialist",
      "cash poster",
      "cash posting clerk",
    ],
  },
  {
    id: "billing",
    title: "Billing Specialist",
    family: "finance",
    soc: "43-3021",
    entitlements: ["submit_claims", "post_payments", "post_adjustments", "view_reports_only"],
    description:
      "Compiles and posts charges, prepares invoices or claims, and posts what comes back from customers and payers.",
    note: "Billing submits claims or invoices, posts what comes back, and writes off the difference.",
    aliases: [
      "billing coordinator",
      "billing clerk",
      "billing",
      "biller",
      "medical biller",
      "dental biller",
      "revenue cycle specialist",
      "revenue cycle",
      "claims specialist",
      "claims processor",
      "posting clerk",
      "external billing service",
      "billing service",
    ],
  },
  {
    id: "payroll",
    title: "Payroll Administrator",
    family: "finance",
    soc: "43-3051",
    entitlements: ["enter_payroll", "edit_payroll_master", "view_reports_only"],
    description:
      "Compiles employee time and pay data, enters and processes payroll, and maintains the employee records payroll reads from.",
    note: "Payroll enters hours and usually also maintains the employee records the run reads from; the ghost-employee cases need both.",
    aliases: [
      "payroll specialist",
      "payroll clerk",
      "payroll coordinator",
      "payroll manager",
      "payroll",
      "payroll and benefits",
      "payroll and benefits administrator",
      "timekeeping clerk",
      "timekeeper",
    ],
  },
  {
    id: "treasurer",
    title: "Treasurer / Cash Manager",
    family: "finance",
    soc: "11-3031",
    entitlements: ["sign_checks", "initiate_ach", "bank_reconcile", "view_reports_only"],
    description:
      "Manages the cash of the business: signs or releases payments, moves funds between accounts, and reconciles the bank.",
    note: "A treasurer moves the money out and, in a small organization, often reconciles the account it leaves from.",
    aliases: ["treasurer", "cash manager", "treasury analyst", "treasury"],
  },
  {
    id: "purchasing",
    title: "Purchasing / Procurement",
    family: "finance",
    soc: "13-1023",
    entitlements: [
      "order_supplies",
      "create_vendor",
      "approve_vendor",
      "hold_company_card",
      "view_reports_only",
    ],
    description:
      "Buys goods and services for the business, selects and sets up suppliers, and places and follows orders.",
    note: "Purchasing chooses and sets up suppliers and places the orders, on account or on a purchasing card; kickback and shell-vendor cases start here.",
    aliases: [
      "purchasing agent",
      "purchasing",
      "buyer",
      "purchasing manager",
      "purchasing coordinator",
      "procurement specialist",
      "procurement manager",
      "procurement",
      "supply chain coordinator",
      "supply chain manager",
      "materials manager",
      "sourcing specialist",
      "procurement coordinator",
    ],
  },
  {
    id: "tax-preparer",
    title: "Tax Preparer",
    family: "finance",
    soc: "13-2082",
    entitlements: ["collect_cash", "view_reports_only"],
    description: "Prepares tax returns for individuals or small businesses and collects the fee.",
    note: "A preparer takes the client's fee; the refund itself should never pass through the firm.",
    aliases: ["tax professional", "tax associate", "tax senior", "enrolled agent", "tax advisor"],
  },
  {
    id: "auditor",
    title: "Auditor",
    family: "finance",
    soc: "13-2011",
    entitlements: ["review_audit_logs", "view_reports_only"],
    description:
      "Examines records and controls, tests transactions, and reports findings; holds no transaction duty.",
    note: "An auditor reads the logs and the records and should hold no transaction duty.",
    aliases: [
      "staff auditor",
      "audit senior",
      "audit associate",
      "internal auditor",
      "audit manager",
    ],
  },
  {
    id: "loan-officer",
    title: "Loan Officer / Processor",
    family: "finance",
    soc: "13-2072",
    entitlements: ["edit_patient_master", "view_reports_only"],
    description:
      "Evaluates, authorizes, or recommends approval of loan applications and maintains borrower records.",
    note: "Lending staff maintain the borrower record; funding and disbursement belong to someone else.",
    aliases: [
      "loan officer",
      "mortgage loan officer",
      "loan processor",
      "underwriter",
      "credit officer",
      "lending officer",
      "mortgage broker",
    ],
  },
  {
    id: "project-accountant",
    title: "Project / Job Cost Accountant",
    family: "finance",
    entitlements: [
      "post_journal_entries",
      "enter_invoices",
      "post_adjustments",
      "submit_claims",
      "view_reports_only",
    ],
    description:
      "Tracks cost and billing by job or project, bills progress, and posts the entries that allocate cost.",
    note: "A project accountant bills progress, enters subcontractor invoices, and posts the entries that move cost between jobs.",
    aliases: [
      "project accountant",
      "job cost accountant",
      "construction accountant",
      "job cost",
      "project controller",
      "billing accountant",
    ],
  },
  // Front office and administration
  {
    id: "office-manager",
    title: "Office Manager",
    family: "office",
    soc: "43-1011",
    entitlements: [
      "post_payments",
      "prepare_deposit",
      "create_vendor",
      "enter_invoices",
      "release_payment",
      "enter_payroll",
      "hold_company_card",
      "review_card_statement",
      "view_reports_only",
    ],
    description:
      "Supervises the office and administrative staff and, in a small business, runs the daily money work: payments, deposits, bills, and payroll.",
    note: "In a small office the office manager records payments, makes the deposit, pays the bills, runs payroll, and codes the statement of the company card they buy supplies on. In a dental, medical or veterinary office they usually reconcile the bank too, and a practice administrator or business manager is read as this seat. Tick Enter write-offs or Administer the system and its user roles if they do it; untick what someone else does.",
    aliases: [
      "practice manager",
      "administrative manager",
      "front office manager",
      "business office manager",
      "clinic manager",
      "office lead",
      "hospital manager",
      "hospital administrator",
      "veterinary practice manager",
      "veterinary hospital manager",
    ],
  },
  {
    id: "office-administrator",
    title: "Office Administrator",
    family: "office",
    entitlements: ["enter_invoices", "release_payment", "view_reports_only"],
    description:
      "Runs the office's paperwork, correspondence, and supplier bills, and pays them as directed.",
    note: "An office administrator enters and pays the bills; payroll, deposits and system set-up belong to a manager unless you tick them.",
    aliases: ["office admin"],
  },
  {
    id: "receptionist",
    title: "Receptionist / Front Desk",
    family: "office",
    soc: "43-4171",
    entitlements: ["collect_cash", "post_payments", "edit_patient_master", "view_reports_only"],
    description:
      "Greets and directs callers and visitors, schedules, takes payments at the desk, and keeps customer or patient records.",
    note: "The front desk takes payments, posts them, and edits customer or patient records: the skimming cases begin at this desk.",
    aliases: [
      "receptionist",
      "front desk",
      "front desk coordinator",
      "front desk receptionist",
      "front desk associate",
      "front office coordinator",
      "front office",
      "patient coordinator",
      "scheduling coordinator",
      "appointment coordinator",
      "information clerk",
      "scheduling manager",
      "hygiene coordinator",
      "front desk lead",
      "front desk supervisor",
      "front office supervisor",
      "client service representative",
      "client services representative",
      "client care representative",
      "client service lead",
    ],
  },
  {
    id: "administrative-assistant",
    title: "Administrative Assistant",
    family: "office",
    soc: "43-6014",
    entitlements: ["order_supplies", "view_reports_only"],
    description:
      "Performs routine administrative work such as correspondence, scheduling, filing, ordering supplies, and answering calls.",
    note: "An administrative assistant orders supplies and handles paperwork; tick more if they also take payments or pay bills.",
    aliases: [
      "admin assistant",
      "admin",
      "office assistant",
      "office clerk",
      "clerk",
      "secretary",
      "administrative coordinator",
      "administrative specialist",
      "office coordinator",
      "administrative support",
      "office support",
      "data entry",
      "data entry clerk",
      "business assistant",
      "scheduler",
      "chief of staff",
    ],
  },
  {
    id: "executive-assistant",
    title: "Executive Assistant",
    family: "office",
    soc: "43-6011",
    entitlements: ["enter_invoices", "release_payment", "hold_company_card", "view_reports_only"],
    description:
      "Provides high-level administrative support to the owner or executive, including correspondence, scheduling, travel, and often the executive's expenses.",
    note: "An executive assistant often holds the owner's card and pays the owner's bills, with the owner's trust standing in for review.",
    aliases: [
      "assistant to the ceo",
      "assistant to the owner",
      "owner assistant",
      "ceo assistant",
      "personal assistant",
      "executive administrative assistant",
    ],
  },
  {
    id: "insurance-coordinator",
    title: "Insurance / Benefits Coordinator",
    family: "office",
    entitlements: ["submit_claims", "post_adjustments", "view_reports_only"],
    description:
      "Verifies coverage and eligibility, submits and follows claims, and adjusts balances to what the payer allowed.",
    note: "An insurance coordinator submits claims and adjusts balances when the payer pays less than billed.",
    aliases: [
      "insurance coordinator",
      "insurance verification",
      "insurance verification specialist",
      "insurance specialist",
      "benefits coordinator",
      "claims coordinator",
      "eligibility specialist",
      "prior authorization specialist",
      "authorization coordinator",
    ],
  },
  {
    id: "treatment-coordinator",
    title: "Treatment / Financial Coordinator",
    family: "office",
    entitlements: ["edit_patient_master", "post_adjustments", "collect_cash", "view_reports_only"],
    description:
      "Presents treatment plans and fees, arranges financing, takes payment, and keeps the patient's plan current.",
    note: "A treatment coordinator presents fees, takes the payment, and adjusts the plan, which touches the record and the money together.",
    aliases: [
      "treatment coordinator",
      "treatment plan coordinator",
      "patient care coordinator",
      "financial coordinator",
      "patient financial coordinator",
      "new patient coordinator",
    ],
  },
  // Sales and customer service
  {
    id: "customer-service",
    title: "Customer Service Representative",
    family: "sales",
    soc: "43-4051",
    entitlements: ["issue_refunds", "post_adjustments", "edit_patient_master", "view_reports_only"],
    description:
      "Handles customer inquiries, complaints, orders, returns, and account changes, and issues refunds and credits within limits.",
    note: "Customer service issues refunds and credits and edits customer records; refund fraud runs through this seat.",
    aliases: [
      "customer service",
      "csr",
      "customer support",
      "customer support representative",
      "support specialist",
      "client services",
      "client service",
      "client service manager",
      "client services manager",
      "customer service manager",
      "member service manager",
      "member services manager",
      "client services coordinator",
      "member services",
      "call center agent",
      "call center representative",
      "account coordinator",
    ],
  },
  {
    id: "sales",
    title: "Sales / Account Manager",
    family: "sales",
    entitlements: ["collect_cash", "edit_patient_master", "view_reports_only"],
    description: "Sells the business's products or services and manages customer accounts.",
    note: "Sales maintains customer accounts and often takes payment from the accounts it serves; granting credits or writing off balances belongs to a manager or the owner unless you tick Enter write-offs.",
    aliases: [
      "sales manager",
      "sales director",
      "director of sales",
      "account executive",
      "account manager",
      "account representative",
      "sales representative",
      "sales",
      "salesperson",
      "business development",
      "business development manager",
      "bdm",
      "inside sales",
      "outside sales",
      "sales consultant",
      "head of sales",
      "used car manager",
      "new car manager",
      "sales lead",
      "comfort advisor",
    ],
  },
  {
    id: "insurance-agent",
    title: "Insurance Agent / Producer",
    family: "sales",
    soc: "41-3021",
    entitlements: ["collect_cash", "edit_patient_master", "view_reports_only"],
    description: "Sells insurance policies, services policyholders, and collects premiums.",
    note: "An agent takes premiums and maintains the policyholder record; premium diversion is the case pattern.",
    aliases: [
      "insurance agent",
      "insurance producer",
      "producer",
      "insurance broker",
      "agency owner",
      "insurance account manager",
      "insurance csr",
    ],
  },
  // Clinical and patient care
  {
    id: "provider",
    title: "Provider (dentist, physician, practitioner)",
    family: "clinical",
    entitlements: ["view_reports_only"],
    description:
      "Delivers the clinical or professional service the business sells; billing, adjustments, and payments belong to the office.",
    note: "An employed provider treats patients and stays out of the money: billing, adjustments, and write-off approval belong to the office and the owner. Tick Approve write-offs and voids if this provider owns the practice or grants courtesy discounts.",
    aliases: [
      "dentist",
      "associate dentist",
      "doctor",
      "physician",
      "provider",
      "dds",
      "dmd",
      "md",
      "do",
      "nurse practitioner",
      "np",
      "physician assistant",
      "pa",
      "veterinarian",
      "dvm",
      "chiropractor",
      "optometrist",
      "therapist",
      "psychologist",
      "orthodontist",
      "periodontist",
      "oral surgeon",
      "pa c",
      "physical therapist",
      "occupational therapist",
      "speech therapist",
    ],
  },
  {
    id: "dental-hygienist",
    title: "Dental Hygienist",
    family: "clinical",
    soc: "29-1292",
    entitlements: ["view_reports_only"],
    description:
      "Provides preventive dental care, cleans teeth, examines patients for oral disease, and educates patients on oral hygiene.",
    note: "A hygienist holds no money duty; they appear on the map for continuity, not conflicts.",
    aliases: ["hygienist", "rdh", "registered dental hygienist"],
  },
  {
    id: "dental-assistant",
    title: "Dental Assistant",
    family: "clinical",
    soc: "31-9091",
    entitlements: ["view_reports_only"],
    description:
      "Performs limited clinical duties under the direction of a dentist, prepares patients and instruments, and assists chairside.",
    note: "A dental assistant holds no money duty; they appear on the map for continuity, not conflicts.",
    aliases: [
      "da",
      "rda",
      "eda",
      "efda",
      "registered dental assistant",
      "expanded functions dental assistant",
      "sterilization technician",
      "cda",
      "certified dental assistant",
      "assistant dental",
    ],
  },
  {
    id: "medical-assistant",
    title: "Medical Assistant / Nurse / Technician",
    family: "clinical",
    entitlements: ["view_reports_only"],
    description:
      "Performs clinical and administrative tasks under a provider's direction, including intake, vitals, charting, and specimen handling.",
    note: "Clinical staff update the clinical chart, not the billing record, and should not touch payments or claims; tick Edit customer master records if they register patients.",
    aliases: [
      "medical assistant",
      "ma",
      "cma",
      "rma",
      "clinical assistant",
      "nurse",
      "rn",
      "lpn",
      "lvn",
      "registered nurse",
      "licensed practical nurse",
      "lab technician",
      "vet tech",
      "veterinary technician",
      "veterinary assistant",
      "phlebotomist",
      "radiology technician",
      "x-ray technician",
      "physical therapist assistant",
      "pta",
      "optician",
      "cna",
      "certified nursing assistant",
      "nursing supervisor",
      "nurse supervisor",
      "charge nurse",
      "head nurse",
      "assistant medical",
      "kennel assistant",
      "kennel attendant",
    ],
  },
  {
    id: "medical-secretary",
    title: "Medical Office Specialist",
    family: "clinical",
    soc: "43-6013",
    entitlements: [
      "collect_cash",
      "post_payments",
      "edit_patient_master",
      "submit_claims",
      "view_reports_only",
    ],
    description:
      "Performs secretarial duties using knowledge of medical terminology: schedules, registers patients, takes copays, and files claims.",
    note: "A medical office specialist takes copays, posts them, edits the patient record, and often files the claim.",
    aliases: [
      "medical secretary",
      "medical office assistant",
      "medical receptionist",
      "patient services representative",
      "patient service representative",
      "patient access representative",
      "patient access",
      "patient registrar",
      "unit clerk",
      "health unit coordinator",
      "medical records clerk",
      "medical records specialist",
      "health information technician",
    ],
  },
  {
    id: "clinic-director",
    title: "Clinic / Practice Director",
    family: "clinical",
    entitlements: [
      "approve_vendor",
      "approve_writeoffs",
      "approve_expenses",
      "manage_user_access",
      "view_reports_only",
    ],
    description:
      "Plans, directs, and coordinates the medical or clinical services of a practice or clinic and its staff.",
    note: "A clinical director approves suppliers, write-offs and staff expense claims and decides who has system access.",
    aliases: [
      "clinical director",
      "director of nursing",
      "practice director",
      "medical director",
      "director of clinical operations",
      "nurse manager",
      "clinical manager",
    ],
  },
  {
    id: "clinic-site-director",
    title: "Clinic Site Director",
    family: "clinical",
    entitlements: ["prepare_deposit", "enter_payroll", "approve_writeoffs", "view_reports_only"],
    description:
      "Runs one clinic site: schedules and supervises its staff, signs off their hours, and oversees its billing and deposits.",
    note: "A clinic director runs one site: approves write-offs and discounts, signs off the staff's hours, and makes up the site's deposit. Enter payroll starts ticked: in a business this size the manager who signs off the hours usually keys them in. Untick it if the office or a payroll service enters the run.",
    aliases: ["clinic director", "clinic director one site", "site clinic director"],
  },
  {
    id: "pharmacist",
    title: "Pharmacist",
    family: "clinical",
    soc: "29-1051",
    entitlements: ["order_supplies", "receive_goods", "approve_writeoffs", "view_reports_only"],
    description:
      "Dispenses medications, counsels patients, manages inventory including controlled substances, and supervises technicians.",
    note: "The pharmacist orders stock, receives it, and approves adjustments; controlled-substance counts are the added control.",
    aliases: ["pharmacy manager", "pharmacist in charge", "pic", "clinical pharmacist"],
  },
  {
    id: "pharmacy-technician",
    title: "Pharmacy Technician",
    family: "clinical",
    soc: "29-2052",
    entitlements: ["collect_cash", "submit_claims", "receive_goods", "view_reports_only"],
    description:
      "Prepares medications under a pharmacist's supervision, rings sales, and processes insurance claims.",
    note: "A technician rings the sale, adjudicates the claim, and often checks in the order.",
    aliases: ["cpht", "pharmacy clerk", "pharmacy assistant", "pharmacy cashier"],
  },
  {
    id: "medical-coder",
    title: "Medical Coder",
    family: "clinical",
    soc: "29-2072",
    entitlements: ["submit_claims", "post_adjustments", "view_reports_only"],
    description:
      "Assigns diagnosis and procedure codes for billing and resolves denied or adjusted claims.",
    note: "A coder decides what the practice bills and adjusts what the payer denied.",
    aliases: [
      "coder",
      "coding specialist",
      "cpc",
      "certified professional coder",
      "medical records coder",
    ],
  },
  {
    id: "billing-manager",
    title: "Billing / Revenue Cycle Manager",
    family: "clinical",
    entitlements: [
      "submit_claims",
      "post_payments",
      "post_adjustments",
      "approve_writeoffs",
      "issue_refunds",
      "view_reports_only",
    ],
    description:
      "Manages the revenue cycle: claims, posting, adjustments, write-offs, refunds, and the billing staff.",
    note: "A billing manager bills, posts, adjusts, writes off, and refunds: the whole receivable in one seat.",
    aliases: ["billing manager", "revenue cycle manager", "patient accounts manager"],
  },
  {
    id: "credentialing",
    title: "Credentialing / Provider Enrollment",
    family: "clinical",
    entitlements: ["view_reports_only"],
    description: "Enrolls and re-credentials providers with payers and licensing bodies.",
    note: "Credentialing keeps providers enrolled with payers and holds no money duty.",
    aliases: [
      "credentialing specialist",
      "credentialing coordinator",
      "provider enrollment specialist",
      "provider enrollment",
      "credentialing",
    ],
  },
  // Restaurant and food service
  {
    id: "restaurant-manager",
    title: "Restaurant Manager",
    family: "food",
    entitlements: [
      "collect_cash",
      "prepare_deposit",
      "issue_refunds",
      "approve_writeoffs",
      "order_supplies",
      "receive_goods",
      "enter_payroll",
      "hold_company_card",
      "view_reports_only",
    ],
    description:
      "Runs the restaurant or its dining room: closes the register, approves voids and comps, schedules staff, and orders stock.",
    note: "A restaurant manager closes the drawer, makes the deposit, approves voids and comps, signs off timecards, orders and receives goods, and holds the house card for the runs the suppliers do not cover. Enter payroll starts ticked: in a business this size the manager who signs off the hours usually keys them in. Untick it if the office or a payroll service enters the run.",
    aliases: [
      "assistant general manager",
      "agm",
      "dining room manager",
      "floor manager",
      "front of house manager",
      "foh manager",
    ],
  },
  {
    id: "chef",
    title: "Chef / Kitchen Manager",
    family: "food",
    soc: "35-1011",
    entitlements: ["order_supplies", "receive_goods", "hold_company_card", "view_reports_only"],
    description:
      "Directs food preparation and the kitchen staff, plans menus, and orders and receives food and supplies.",
    note: "The kitchen orders food and receives the delivery, so the check on the supplier is the same person who chose it, and the kitchen card pays for whatever the suppliers do not deliver.",
    aliases: [
      "executive chef",
      "head chef",
      "chef",
      "kitchen manager",
      "sous chef",
      "chef de cuisine",
      "head cook",
      "pastry chef",
      "back of house manager",
      "boh manager",
      "kitchen lead",
      "kitchen supervisor",
      "chef de partie",
      "station chef",
      "boh lead",
    ],
  },
  {
    id: "server",
    title: "Server",
    family: "food",
    soc: "35-3031",
    entitlements: ["collect_cash", "view_reports_only"],
    description:
      "Takes orders and serves food and drink to guests, presents the check, and collects payment.",
    note: "A server takes payment at the table; the controls are the closed check, the tip-out, and who can void.",
    aliases: [
      "waiter",
      "waitress",
      "wait staff",
      "waitstaff",
      "food server",
      "barista",
      "counter server",
      "catering server",
      "banquet server",
    ],
  },
  {
    id: "bartender",
    title: "Bartender",
    family: "food",
    soc: "35-3011",
    entitlements: ["collect_cash", "view_reports_only"],
    description:
      "Mixes and serves drinks, takes payment at the bar, and keeps the bar's stock and drawer.",
    note: "A bartender takes cash all night; the control is the pour count and the drawer count.",
    aliases: ["mixologist", "bar staff", "bar lead", "beertender"],
  },
  {
    id: "host",
    title: "Host / Busser / Barback",
    family: "food",
    soc: "35-9031",
    entitlements: ["view_reports_only"],
    description:
      "Seats guests, clears and resets tables, runs food, or stocks the bar, without handling payment.",
    note: "Hosts, bussers, runners and barbacks seat guests and support the floor and bar without a drawer; tick Take payment from customers if they ring out orders.",
    aliases: [
      "host",
      "hostess",
      "greeter",
      "busser",
      "food runner",
      "runner",
      "barback",
      "bar back",
      "restaurant host",
    ],
  },
  {
    id: "bar-manager",
    title: "Bar / Beverage Manager",
    family: "food",
    entitlements: [
      "collect_cash",
      "prepare_deposit",
      "order_supplies",
      "receive_goods",
      "view_reports_only",
    ],
    description:
      "Runs the bar: orders and receives liquor, sets the pour, schedules bar staff, and closes the bar's drawer.",
    note: "A bar manager orders and receives liquor and closes the bar drawer; inventory theft and skimming share the seat.",
    aliases: [
      "bar manager",
      "beverage manager",
      "beverage director",
      "sommelier",
      "wine director",
      "taproom manager",
      "tasting room manager",
    ],
  },
  {
    id: "head-brewer",
    title: "Head Brewer / Brewmaster",
    family: "food",
    entitlements: ["order_supplies", "receive_goods", "view_reports_only"],
    description:
      "Plans production, orders brewing ingredients and packaging, and supervises the brewing and cellar staff.",
    note: "The head brewer orders malt, hops and packaging and signs for them, so the check on the supplier is the same person who chose it.",
    aliases: ["head brewer", "brewmaster", "brew master", "brewing manager"],
  },
  {
    id: "brewer",
    title: "Brewer / Cellar / Packaging",
    family: "food",
    entitlements: ["view_reports_only"],
    description: "Brews, ferments, conditions, and packages the product; holds no money duty.",
    note: "Brewing, cellar and packaging staff make the product and hold no money duty; they appear on the map for continuity.",
    aliases: [
      "brewer",
      "assistant brewer",
      "cellarperson",
      "cellar person",
      "cellarman",
      "cellar operator",
      "packaging lead",
      "packaging operator",
    ],
  },
  {
    id: "catering-manager",
    title: "Catering / Events Manager",
    family: "food",
    entitlements: ["collect_cash", "post_adjustments", "approve_writeoffs", "view_reports_only"],
    description: "Sells and runs catered events, takes deposits, and settles event bills.",
    note: "Events takes deposits, adjusts the bill, and comps: money and its record in one seat, usually off the main register.",
    aliases: [
      "catering manager",
      "events manager",
      "event manager",
      "event coordinator",
      "banquet manager",
      "sales and catering",
      "catering sales",
      "private events",
    ],
  },
  {
    id: "kitchen-staff",
    title: "Kitchen Staff",
    family: "food",
    entitlements: ["view_reports_only"],
    description: "Prepares ingredients, washes, and supports the kitchen; holds no money duty.",
    note: "Kitchen staff hold no money duty; they appear on the map for continuity.",
    aliases: [
      "dishwasher",
      "kitchen assistant",
      "kitchen porter",
      "steward",
      "kitchen helper",
      "food prep",
      "prep",
      "expo",
      "expeditor",
      "food expeditor",
      "cook",
      "line cook",
      "prep cook",
      "cook line",
      "grill cook",
      "fry cook",
    ],
  },
  // Retail
  {
    id: "store-manager",
    title: "Store / Branch Manager",
    family: "retail",
    entitlements: [
      "collect_cash",
      "prepare_deposit",
      "issue_refunds",
      "approve_writeoffs",
      "receive_goods",
      "hold_company_card",
      "view_reports_only",
    ],
    description:
      "Supervises and coordinates the retail staff of a store or department, including cash handling, returns, deliveries, and schedules.",
    note: "A store manager takes and banks cash, approves returns and markdowns, signs for deliveries, and holds a store card for supplies. Tick Order supplies / services, Enter payroll and Create users / assign system access if they do them rather than the owner or the office.",
    aliases: [
      "store manager",
      "retail manager",
      "shop manager",
      "branch manager",
      "department manager",
      "location manager",
      "salon manager",
      "spa manager",
      "gym manager",
      "fitness center manager",
      "studio manager",
    ],
  },
  {
    id: "assistant-manager",
    title: "Assistant Manager (store or restaurant)",
    family: "retail",
    entitlements: ["collect_cash", "prepare_deposit", "issue_refunds", "view_reports_only"],
    description:
      "Supports the store or restaurant manager and runs shifts: opens and closes the registers, bags the deposit, and handles returns.",
    note: "An assistant manager closes registers, bags the deposit and processes refunds; tick Approve write-offs and voids if they hold the manager's override, and Order supplies / services or Enter payroll if they do those.",
    aliases: [
      "assistant manager",
      "assistant store manager",
      "assistant shop manager",
      "assistant retail manager",
    ],
  },
  {
    id: "shift-lead",
    title: "Shift Lead / Key Holder",
    family: "retail",
    entitlements: ["collect_cash", "prepare_deposit", "view_reports_only"],
    description:
      "Leads a shift or a station, opens and closes the register, and stands in for the manager when none is present.",
    note: "A shift lead or key holder takes cash and counts and bags the drawer; a manager issues refunds unless you tick Issue customer refunds.",
    aliases: [
      "shift lead",
      "shift leader",
      "shift supervisor",
      "shift manager",
      "key holder",
      "keyholder",
      "lead cashier",
      "head cashier",
      "floor supervisor",
      "night manager",
      "closing manager",
      "opening manager",
      "opening supervisor",
      "closing supervisor",
      "store lead",
    ],
  },
  {
    id: "cashier",
    title: "Cashier / Sales Associate",
    family: "retail",
    soc: "41-2011",
    entitlements: ["collect_cash", "view_reports_only"],
    description: "Receives and disburses money at a register, records the sale, and makes change.",
    note: "A cashier takes payment; the controls are the count, the deposit, and who can void or refund.",
    aliases: [
      "cashier",
      "checkout",
      "checker",
      "teller",
      "sales associate",
      "retail associate",
      "store associate",
      "sales clerk",
      "retail sales",
      "counter staff",
      "counter associate",
      "customer service associate",
      "front end associate",
      "register",
      "counter sales",
      "sales floor associate",
      "grocery associate",
      "deli associate",
      "floor associate",
    ],
  },
  {
    id: "security",
    title: "Security / Loss Prevention",
    family: "retail",
    soc: "33-9032",
    entitlements: ["view_reports_only"],
    description:
      "Guards, patrols, or monitors premises to prevent theft, violence, or infractions of rules.",
    note: "Security watches the premises and the registers and holds no money duty of its own.",
    aliases: [
      "security guard",
      "security officer",
      "loss prevention",
      "loss prevention officer",
      "asset protection",
      "asset protection associate",
      "security",
    ],
  },
  {
    id: "ecommerce",
    title: "E-commerce / Fulfillment",
    family: "retail",
    entitlements: ["issue_refunds", "view_reports_only"],
    description: "Runs online sales channels and fulfills orders, including returns and refunds.",
    note: "Online sales issues refunds against orders nobody else sees; tick Enter write-offs if they also grant store credit or adjust orders.",
    aliases: [
      "e-commerce specialist",
      "ecommerce specialist",
      "ecommerce manager",
      "e-commerce manager",
      "online sales",
      "marketplace manager",
      "fulfillment associate",
      "fulfillment specialist",
      "order fulfillment",
      "fulfillment",
      "e-commerce coordinator",
      "ecommerce coordinator",
      "online store coordinator",
      "online store manager",
    ],
  },
  {
    id: "merchandiser",
    title: "Merchandiser / Category Manager",
    family: "retail",
    entitlements: ["order_supplies", "view_reports_only"],
    description:
      "Plans and selects the products the business carries and how the store presents them.",
    note: "A merchandiser decides what the business buys; receiving and paying belong to others.",
    aliases: [
      "visual merchandiser",
      "merchandiser",
      "merchandising manager",
      "category manager",
      "merchandise planner",
      "retail planner",
      "inventory planner",
      "merchandise allocator",
    ],
  },
  {
    id: "cash-office",
    title: "Cash Office / Deposit Clerk",
    family: "retail",
    entitlements: ["collect_cash", "prepare_deposit", "view_reports_only"],
    description:
      "Counts register drawers, prepares the bank deposit, and keeps the cash-office records for a store or branch.",
    note: "A cash-office clerk counts the drawers and makes up the deposit; whoever reconciles the bank account must be someone else.",
    aliases: [
      "cash office",
      "cash office associate",
      "cash office clerk",
      "cash office lead",
      "cash room clerk",
      "cash room",
      "deposit clerk",
      "vault teller",
      "cash control clerk",
      "cash handler",
    ],
  },
  // Trades, field, and construction
  {
    id: "receiving",
    title: "Receiving / Inventory / Warehouse",
    family: "trades",
    soc: "43-5071",
    entitlements: ["receive_goods", "view_reports_only"],
    description:
      "Verifies and records incoming and outgoing shipments and keeps the inventory count.",
    note: "Receiving confirms what arrived, which is the check on purchasing; a supervisor here also often approves hours.",
    aliases: [
      "receiving clerk",
      "receiving",
      "shipping and receiving",
      "shipping clerk",
      "inventory clerk",
      "inventory specialist",
      "inventory manager",
      "inventory control",
      "warehouse associate",
      "warehouse worker",
      "warehouse supervisor",
      "warehouse manager",
      "warehouse lead",
      "stock clerk",
      "stocker",
      "materials handler",
      "logistics coordinator",
      "inventory lead",
      "yard manager",
      "yard foreman",
      "yard worker",
      "stock associate",
      "warehouse",
      "stockroom associate",
      "parts runner",
      "inventory coordinator",
      "inventory associate",
    ],
  },
  {
    id: "estimator",
    title: "Estimator",
    family: "trades",
    soc: "13-1051",
    entitlements: ["change_fee_schedule", "view_reports_only"],
    description: "Prepares cost estimates and prices for jobs, bids, and change orders.",
    note: "An estimator sets the price and the discount on each bid; writing off what a customer owes belongs to someone else.",
    aliases: ["cost estimator", "project estimator", "sales estimator", "estimating"],
  },
  {
    id: "dispatcher",
    title: "Dispatcher / Service Coordinator",
    family: "trades",
    soc: "43-5032",
    entitlements: ["edit_patient_master", "collect_cash", "view_reports_only"],
    description:
      "Schedules and dispatches technicians and drivers, keeps customer and job records, and takes payments by phone.",
    note: "A dispatcher, or the CSR who books and dispatches the calls, maintains customer records and takes phone payments; refunds and credits go to the office. The field cases where a tech and dispatcher split a cash job start here.",
    aliases: [
      "dispatcher",
      "dispatch",
      "service coordinator",
      "service dispatcher",
      "scheduling dispatcher",
      "fleet coordinator",
      "dispatcher csr",
      "csr dispatcher",
    ],
  },
  {
    id: "field-technician",
    title: "Field Technician / Crew",
    family: "trades",
    entitlements: ["collect_cash", "view_reports_only"],
    description:
      "Performs the trade or service work in the field or on site and may collect payment from the customer on completion.",
    note: "A technician who collects at the job holds cash the office never sees until they deposit it.",
    aliases: [
      "field technician",
      "service technician",
      "installer",
      "crew member",
      "laborer",
      "labourer",
      "journeyman",
      "plumber",
      "electrician",
      "hvac technician",
      "operator",
      "equipment operator",
      "carpenter",
      "painter",
      "roofer",
      "install technician",
      "installation technician",
      "hvac install technician",
      "pipefitter",
      "helper",
      "trade helper",
    ],
  },
  {
    id: "foreman",
    title: "Foreman / Superintendent",
    family: "trades",
    entitlements: ["receive_goods", "order_supplies", "hold_company_card", "view_reports_only"],
    description:
      "Supervises and coordinates the crew on site, orders and receives materials, and approves the crew's hours.",
    note: "A foreman orders and receives material, buys the rest on the company card or the supply-house account, and signs off the crew's timesheets, which the office then enters into payroll: the ghost-timesheet cases run through this seat.",
    aliases: [
      "foreman",
      "superintendent",
      "site supervisor",
      "site manager",
      "construction manager",
      "project superintendent",
      "lead technician",
      "field supervisor",
      "operations supervisor",
      "production supervisor",
      "production manager",
      "crew chief",
      "crew foreman",
      "install manager",
      "installation manager",
    ],
  },
  {
    id: "driver",
    title: "Driver / Delivery",
    family: "trades",
    soc: "53-3033",
    entitlements: ["collect_cash", "view_reports_only"],
    description: "Drives delivery or service routes and may collect payment on delivery.",
    note: "A driver who collects on delivery holds cash and checks until the route settles.",
    aliases: [
      "driver",
      "delivery driver",
      "truck driver",
      "cdl driver",
      "courier",
      "route driver",
      "route sales",
      "route salesperson",
      "delivery",
      "route sales rep",
    ],
  },
  {
    id: "fleet-manager",
    title: "Fleet / Logistics Manager",
    family: "trades",
    entitlements: [
      "approve_vendor",
      "order_supplies",
      "receive_goods",
      "enter_payroll",
      "hold_company_card",
      "view_reports_only",
    ],
    description: "Manages vehicles, drivers, routing, fuel, and repair suppliers.",
    note: "A fleet manager approves fuel, repair, and equipment suppliers, holds the fuel and repair cards, and signs off drivers' hours. Enter payroll starts ticked: in a business this size the manager who signs off the hours usually keys them in. Untick it if the office or a payroll service enters the run.",
    aliases: [
      "fleet manager",
      "transportation manager",
      "logistics manager",
      "dispatch manager",
      "distribution manager",
      "routing manager",
      "equipment manager",
      "equipment coordinator",
    ],
  },
  {
    id: "facilities",
    title: "Facilities / Maintenance Manager",
    family: "trades",
    entitlements: [
      "order_supplies",
      "receive_goods",
      "approve_vendor",
      "enter_invoices",
      "hold_company_card",
      "view_reports_only",
    ],
    description:
      "Maintains buildings and equipment, hires and directs contractors, and orders parts and supplies.",
    note: "Facilities chooses the contractors, orders the parts on account or on the company card, confirms the work, and enters the invoice.",
    aliases: [
      "facilities manager",
      "facility manager",
      "building manager",
      "maintenance manager",
      "maintenance supervisor",
      "plant engineer",
      "building engineer",
      "facilities coordinator",
      "maintenance coordinator",
      "maintenance scheduler",
    ],
  },
  {
    id: "custodial",
    title: "Cleaner / Custodian / Groundskeeper",
    family: "trades",
    soc: "37-2011",
    entitlements: ["view_reports_only"],
    description: "Cleans, maintains and repairs the premises and grounds; holds no money duty.",
    note: "Cleaning, grounds and maintenance staff hold no money duty by default; tick anything they actually do.",
    aliases: [
      "cleaner",
      "custodian",
      "janitor",
      "janitorial",
      "groundskeeper",
      "landscaper",
      "maintenance",
      "maintenance worker",
      "maintenance technician",
      "porter",
      "building attendant",
    ],
  },
  // IT and systems
  {
    id: "it-administrator",
    title: "IT Administrator",
    family: "it",
    soc: "15-1244",
    entitlements: [
      "pms_admin_roles",
      "manage_user_access",
      "manage_backups",
      "export_bulk_data",
      "hold_company_card",
      "view_reports_only",
    ],
    description:
      "Installs, configures, and maintains the business's systems, networks, user accounts, and backups.",
    note: "IT administers the system, grants access, holds the backups, can export everything, and puts the software subscriptions on a company card; the data-theft and data-destruction cases sit here. Someone else should review the access logs: tick Review system audit / access logs here only if IT does it.",
    aliases: [
      "systems administrator",
      "system administrator",
      "sysadmin",
      "it manager",
      "it director",
      "network administrator",
      "it support",
      "it support specialist",
      "help desk",
      "helpdesk",
      "it specialist",
      "it technician",
      "managed service provider",
      "msp",
      "cto",
      "chief technology officer",
      "it",
      "information technology",
      "database administrator",
      "dba",
      "desktop support",
      "it support technician",
      "systems engineer",
    ],
  },
  // Human resources
  {
    id: "hr",
    title: "Human Resources",
    family: "people",
    soc: "13-1071",
    entitlements: ["edit_payroll_master", "view_reports_only"],
    description:
      "Recruits, hires, and onboards staff, maintains employee records, and administers pay changes and benefits.",
    note: "HR adds employees and changes pay rates and bank details; the check is that someone else runs the payroll that reads them.",
    aliases: [
      "hr generalist",
      "hr manager",
      "hr director",
      "human resources manager",
      "human resources generalist",
      "hr specialist",
      "hr coordinator",
      "hr administrator",
      "hr assistant",
      "hr",
      "people operations",
      "people manager",
      "hr business partner",
      "hrbp",
      "recruiter",
      "talent acquisition",
      "benefits administrator",
      "benefits manager",
      "people and culture manager",
      "people and culture",
      "talent manager",
    ],
  },
  // Legal
  {
    id: "firm-administrator",
    title: "Firm / Legal Administrator",
    family: "legal",
    entitlements: [
      "prepare_deposit",
      "bank_reconcile",
      "enter_invoices",
      "create_vendor",
      "release_payment",
      "enter_payroll",
      "hold_company_card",
      "review_card_statement",
      "pms_admin_roles",
      "view_reports_only",
    ],
    description:
      "Manages a law firm's finances, trust and operating accounts, staff, payroll, facilities, and practice systems.",
    note: "A firm administrator runs the firm's money and systems: makes the deposit, pays the bills, runs payroll, holds the firm card and codes its statement, reconciles the operating and trust accounts and administers the practice software, while billing posts client payments. Untick what someone else does.",
    aliases: ["firm administrator", "law firm administrator", "legal administrator"],
  },
  {
    id: "paralegal",
    title: "Paralegal / Legal Assistant",
    family: "legal",
    soc: "23-2011",
    entitlements: ["view_reports_only"],
    description:
      "Assists attorneys by preparing documents, organizing files, and managing deadlines and client contact.",
    note: "A paralegal or legal assistant works the matters and holds no money duty by default; tick Issue invoices or claims or Record payments received if they do the firm's billing.",
    aliases: [
      "paralegal",
      "legal assistant",
      "legal secretary",
      "law clerk",
      "litigation assistant",
      "litigation paralegal",
      "legal administrative assistant",
      "intake specialist",
      "intake coordinator",
      "legal assistant secretary",
      "legal secretary assistant",
    ],
  },
  {
    id: "attorney",
    title: "Attorney",
    family: "legal",
    soc: "23-1011",
    entitlements: ["view_reports_only"],
    description:
      "Represents clients, gives legal advice, and records the time billed on their matters.",
    note: "An associate or employed attorney bills time; a partner approves write-downs, and billing and trust deposits belong to someone else, so tick Approve write-offs and voids only for an attorney who grants them.",
    aliases: [
      "lawyer",
      "associate attorney",
      "counsel",
      "senior associate",
      "general counsel",
      "solicitor",
    ],
  },
  // Professional and project staff
  {
    id: "project-manager",
    title: "Project Manager",
    family: "professional",
    entitlements: ["view_reports_only"],
    description:
      "Plans and delivers projects, manages the budget and the subcontractors, and approves work and invoices against it.",
    note: "A project manager approves subcontractor bills and change orders against the job budget: tick Approve bills for payment if they do. Entering the bills, paying them, and approving new suppliers belong to the office and the owner. Tick Order supplies / services if they place the orders.",
    aliases: [
      "pm",
      "project coordinator",
      "program manager",
      "project lead",
      "account director",
      "delivery manager",
      "engagement manager",
    ],
  },
  {
    id: "consultant",
    title: "Consultant / Engineer / Analyst",
    family: "professional",
    entitlements: ["view_reports_only"],
    description:
      "Delivers professional, technical, or personal services to clients and bills time or fees for the work.",
    note: "Fee-earning staff usually hold no money duty; tick Take payment from customers if they take it at the chair or the desk.",
    aliases: [
      "consultant",
      "senior consultant",
      "engineer",
      "software engineer",
      "developer",
      "designer",
      "analyst",
      "architect",
      "specialist",
      "advisor",
      "adviser",
      "associate consultant",
      "financial planner",
      "financial advisor",
      "event planner",
      "wedding planner",
      "trainer",
      "instructor",
      "coach",
      "stylist",
      "esthetician",
      "massage therapist",
      "tech lead",
      "technical lead",
      "engineering lead",
      "dev lead",
      "development lead",
      "design lead",
      "product manager",
      "product owner",
      "scrum master",
      "qa lead",
      "nail technician",
      "barber",
      "hairstylist",
      "hair stylist",
      "groomer",
      "pet groomer",
      "personal trainer",
      "fitness instructor",
    ],
  },
  {
    id: "contracts-administrator",
    title: "Contracts Administrator",
    family: "professional",
    entitlements: ["create_vendor", "approve_vendor", "enter_invoices", "view_reports_only"],
    description:
      "Prepares, sets up, and administers contracts and subcontracts and their invoices.",
    note: "A contracts administrator sets up and approves subcontractors and enters their invoices against the contract.",
    aliases: [
      "contract administrator",
      "contracts manager",
      "contract manager",
      "subcontract administrator",
      "procurement administrator",
    ],
  },
  {
    id: "compliance",
    title: "Compliance / Quality / Safety",
    family: "professional",
    entitlements: ["review_audit_logs", "view_reports_only"],
    description:
      "Monitors compliance with laws, standards, and internal policy; tests controls and reads the logs.",
    note: "Compliance reads the logs and tests the controls and should hold no transaction duty.",
    aliases: [
      "compliance officer",
      "compliance manager",
      "compliance specialist",
      "risk manager",
      "quality manager",
      "quality assurance manager",
      "qa manager",
      "safety manager",
      "safety coordinator",
      "ehs manager",
      "privacy officer",
      "information security officer",
    ],
  },
  {
    id: "intern",
    title: "Intern / Volunteer",
    family: "professional",
    entitlements: ["view_reports_only"],
    description:
      "Works in a temporary or learning role and holds no money duty unless assigned one.",
    note: "An intern holds no money duty by default; tick anything they actually do.",
    aliases: ["intern", "volunteer", "student worker", "work study", "co-op student", "apprentice"],
  },
  // Hotels and hospitality
  {
    id: "hotel-front-desk",
    title: "Hotel Front Desk Agent",
    family: "hospitality",
    soc: "43-4081",
    entitlements: [
      "collect_cash",
      "post_payments",
      "issue_refunds",
      "edit_patient_master",
      "view_reports_only",
    ],
    description:
      "Registers guests, assigns rooms, keeps guest accounts, makes and confirms reservations, and collects payment at checkout.",
    note: "A desk agent takes payment, posts it to the folio, and can refund; the folio is the record and the money together. Tick Enter write-offs if they also adjust folio charges.",
    aliases: [
      "hotel front desk",
      "front desk agent",
      "desk clerk",
      "guest services agent",
      "guest service agent",
      "guest services representative",
      "guest service representative",
      "reservations agent",
      "reservationist",
      "reservations",
    ],
  },
  {
    id: "night-auditor",
    title: "Night Auditor",
    family: "hospitality",
    entitlements: ["post_payments", "post_adjustments", "view_reports_only"],
    description:
      "Works the overnight desk, posts the day's charges and payments, and balances the day's accounts before the morning shift.",
    note: "The night auditor posts the day's charges and payments and balances the property system's day, alone and overnight. Tick Reconcile the bank account only if they also reconcile the bank statement.",
    aliases: ["night audit", "night audit clerk", "overnight front desk"],
  },
  {
    id: "housekeeping-supervisor",
    title: "Housekeeping Supervisor",
    family: "hospitality",
    soc: "37-1011",
    entitlements: ["order_supplies", "enter_payroll", "view_reports_only"],
    description:
      "Supervises and coordinates the cleaning staff, inspects rooms and areas, and orders cleaning supplies.",
    note: "Housekeeping orders supplies and signs off the crew's hours. Enter payroll starts ticked: in a business this size the manager who signs off the hours usually keys them in. Untick it if the office or a payroll service enters the run.",
    aliases: [
      "executive housekeeper",
      "housekeeping manager",
      "head housekeeper",
      "janitorial supervisor",
      "custodial supervisor",
    ],
  },
  {
    id: "hotel-manager",
    title: "Hotel / Lodging Manager",
    family: "hospitality",
    entitlements: [
      "approve_writeoffs",
      "issue_refunds",
      "prepare_deposit",
      "approve_vendor",
      "enter_payroll",
      "hold_company_card",
      "manage_user_access",
      "view_reports_only",
    ],
    description:
      "Plans, directs, and coordinates the operations of a hotel or lodging property and its staff.",
    note: "A lodging manager approves rate adjustments and refunds, banks the deposit, approves suppliers, holds the property card, and holds the property system's admin.",
    aliases: [
      "hotel manager",
      "lodging manager",
      "resort manager",
      "innkeeper",
      "hospitality manager",
      "rooms division manager",
      "guest services manager",
      "guest service manager",
    ],
  },
  {
    id: "housekeeping-staff",
    title: "Housekeeping / Room Attendant",
    family: "hospitality",
    entitlements: ["view_reports_only"],
    description:
      "Cleans and services guest rooms and public areas of a hotel or property; holds no money duty.",
    note: "Housekeeping staff hold no money duty by default; tick anything they actually do.",
    aliases: [
      "housekeeper",
      "room attendant",
      "housekeeping attendant",
      "housekeeping aide",
      "laundry attendant",
      "houseman",
      "houseperson",
      "housekeeping",
    ],
  },
  // Auto dealership and service
  {
    id: "service-advisor",
    title: "Service Advisor / Writer",
    family: "automotive",
    entitlements: [
      "collect_cash",
      "post_payments",
      "post_adjustments",
      "edit_patient_master",
      "view_reports_only",
    ],
    description:
      "Greets service customers, writes the repair order, quotes and adjusts the work, and takes payment.",
    note: "A service advisor writes and adjusts the repair order and takes and records the customer's payment at the counter; the service manager approves goodwill write-offs unless you tick Approve write-offs and voids.",
    aliases: ["service advisor", "service writer", "service consultant", "shop advisor"],
  },
  {
    id: "parts",
    title: "Parts Manager / Counter",
    family: "automotive",
    entitlements: ["order_supplies", "receive_goods", "collect_cash", "view_reports_only"],
    description: "Orders, receives, stocks, and sells parts over the counter and to the shop.",
    note: "Parts orders stock, receives it, and sells it over the counter, which is ordering, receiving, and cash in one seat.",
    aliases: [
      "parts manager",
      "parts counter",
      "parts specialist",
      "parts advisor",
      "parts clerk",
      "parts associate",
      "parts counterperson",
      "counterperson",
      "parts counter person",
      "parts sales",
    ],
  },
  {
    id: "fi-manager",
    title: "Finance and Insurance Manager",
    family: "automotive",
    entitlements: ["collect_cash", "approve_writeoffs", "edit_patient_master", "view_reports_only"],
    description:
      "Arranges financing and sells protection products on vehicle sales, structures the deal, and collects down payments.",
    note: "The F&I office takes down payments, structures the deal, and adjusts what the customer pays; the deal jacket is the control.",
    aliases: ["f&i manager", "f&i", "dealership finance manager"],
  },
  {
    id: "title-clerk",
    title: "Title / Deal Clerk",
    family: "automotive",
    entitlements: ["post_payments", "post_adjustments", "view_reports_only"],
    description:
      "Processes the paperwork on vehicle sales: titles, registrations, and the posting of the deal to the books.",
    note: "A title clerk posts the deal and its adjustments after the sale; the money has usually moved before the clerk writes the record.",
    aliases: [
      "title clerk",
      "deal clerk",
      "dmv clerk",
      "tag and title clerk",
      "deal processor",
      "title and registration clerk",
      "registration clerk",
      "tag and title",
    ],
  },
  {
    id: "service-manager",
    title: "Service Manager (repair, dealership)",
    family: "automotive",
    entitlements: [
      "approve_writeoffs",
      "order_supplies",
      "receive_goods",
      "enter_payroll",
      "hold_company_card",
      "view_reports_only",
    ],
    description:
      "Runs a repair or dealership service department: schedules the shop, approves goodwill and warranty write-offs, submits technicians' hours, and orders parts.",
    note: "A service manager approves goodwill and warranty write-offs, signs off the technicians' hours, orders and receives parts, and holds the shop card for sublet and outside purchases. Enter payroll starts ticked: in a business this size the manager who signs off the hours usually keys them in. Untick it if the office or a payroll service enters the run.",
    aliases: [
      "service manager",
      "service department manager",
      "fixed operations manager",
      "service director",
    ],
  },
  {
    id: "automotive-support",
    title: "Lot / Detail / BDC Staff",
    family: "automotive",
    entitlements: ["view_reports_only"],
    description:
      "Prepares, moves and cleans vehicles or sets sales and service appointments at a dealership; holds no money duty.",
    note: "Lot, detail and business-development-center staff hold no money duty by default; tick anything they actually do.",
    aliases: [
      "detailer",
      "lot attendant",
      "lot porter",
      "bdc",
      "bdc representative",
      "bdc agent",
      "business development center",
      "car washer",
    ],
  },
  {
    id: "shop-technician",
    title: "Shop / Automotive Technician",
    family: "automotive",
    entitlements: ["view_reports_only"],
    description:
      "Diagnoses and repairs vehicles or equipment in a shop against a repair order; holds no money duty.",
    note: "A shop technician works the repair order; the advisor or cashier takes the money, so the technician holds no money duty by default.",
    aliases: [
      "shop technician",
      "automotive technician",
      "auto technician",
      "mechanic",
      "diesel technician",
      "lube technician",
      "tire technician",
      "master technician",
      "ase technician",
      "technician a",
      "technician b",
      "technician c",
      "line technician",
      "flat rate technician",
      "body technician",
      "collision technician",
      "apprentice technician",
      "general service technician",
      "gs technician",
    ],
  },
  // Property and real estate
  {
    id: "property-manager",
    title: "Property Manager",
    family: "property",
    soc: "11-9141",
    entitlements: [
      "collect_cash",
      "post_payments",
      "approve_vendor",
      "release_payment",
      "approve_writeoffs",
      "hold_company_card",
      "view_reports_only",
    ],
    description:
      "Manages residential or commercial property for owners: collects rent, hires and pays contractors, and keeps the accounts.",
    note: "A property manager collects rent, posts it, chooses and pays the contractors, buys repairs on the company card, and writes off balances: custody, recording, and approval in one seat.",
    aliases: [
      "community association manager",
      "association manager",
      "hoa manager",
      "apartment manager",
      "leasing manager",
      "portfolio manager",
      "asset manager",
    ],
  },
  {
    id: "assistant-property-manager",
    title: "Assistant Property Manager",
    family: "property",
    entitlements: ["collect_cash", "post_payments", "view_reports_only"],
    description:
      "Supports the property manager: collects and posts rent, handles tenant accounts, and coordinates service requests.",
    note: "An assistant property manager collects and posts rent; choosing and paying contractors stays with the property manager unless you tick it.",
    aliases: ["assistant community manager"],
  },
  {
    id: "leasing-agent",
    title: "Leasing Agent",
    family: "property",
    entitlements: ["collect_cash", "edit_patient_master", "view_reports_only"],
    description: "Shows units, takes applications, deposits, and fees, and sets up tenant records.",
    note: "A leasing agent takes deposits and application fees and sets up the tenant record.",
    aliases: ["leasing consultant", "leasing specialist", "rental agent", "leasing associate"],
  },
  {
    id: "real-estate-agent",
    title: "Real Estate Agent / Broker",
    family: "property",
    soc: "41-9022",
    entitlements: ["collect_cash", "view_reports_only"],
    description:
      "Rents, buys, or sells property for clients, shows listings, negotiates terms, and handles earnest money to escrow.",
    note: "An agent handles earnest money and fees on the way to escrow; the control is that deposits go to the trust account the same day.",
    aliases: [
      "real estate agent",
      "realtor",
      "real estate broker",
      "real estate salesperson",
      "listing agent",
      "buyer's agent",
    ],
  },
  {
    id: "transaction-coordinator",
    title: "Transaction / Closing Coordinator",
    family: "property",
    entitlements: ["post_payments", "edit_patient_master", "view_reports_only"],
    description:
      "Manages the documents, deadlines, and funds of a real estate transaction from contract to closing.",
    note: "A closing coordinator records the funds that move through a transaction and maintains the parties' records.",
    aliases: [
      "transaction coordinator",
      "closing coordinator",
      "escrow assistant",
      "escrow officer",
      "closing agent",
      "settlement agent",
      "escrow manager",
    ],
  },
  // Nonprofit and association
  {
    id: "executive-director",
    title: "Executive Director",
    family: "nonprofit",
    entitlements: [
      "approve_vendor",
      "approve_payroll",
      "approve_writeoffs",
      "sign_checks",
      "hold_company_card",
      "approve_expenses",
      "manage_user_access",
      "view_reports_only",
    ],
    description:
      "Leads a nonprofit or association, directs its programs and staff, and holds final authority over its spending.",
    note: "An executive director approves suppliers, payroll, write-offs and staff expenses, signs, and holds the organization's card; a board treasurer who reads the bank and card statements is the check.",
    aliases: ["ed", "nonprofit director", "association executive"],
  },
  {
    id: "development-director",
    title: "Development / Fundraising",
    family: "nonprofit",
    entitlements: ["collect_cash", "edit_patient_master", "view_reports_only"],
    description:
      "Raises funds from donors, members, and events and maintains the donor and member records.",
    note: "Development receives gifts and maintains donor records; a gift that reaches the donor database but not the bank is the case pattern.",
    aliases: [
      "development director",
      "director of development",
      "fundraising manager",
      "fundraiser",
      "development coordinator",
      "development associate",
      "donor relations",
      "advancement director",
      "major gifts officer",
      "membership coordinator",
      "membership manager",
    ],
  },
  {
    id: "grants-manager",
    title: "Grants Manager",
    family: "nonprofit",
    entitlements: ["submit_claims", "view_reports_only"],
    description: "Finds, writes, and administers grants and bills funders for reimbursable costs.",
    note: "A grants manager bills funders for reimbursement, which is a claim against a payer.",
    aliases: [
      "grant writer",
      "grants coordinator",
      "grant administrator",
      "grants administrator",
      "grant manager",
    ],
  },
  {
    id: "board-treasurer",
    title: "Board Treasurer",
    family: "nonprofit",
    entitlements: ["sign_checks", "approve_payroll", "review_card_statement", "view_reports_only"],
    description:
      "Serves on the board, oversees the finances, signs or approves payments, and reviews the reconciliations.",
    note: "A volunteer treasurer co-signs, reads the executive director's card statement, and reviews the reconciliation someone else prepares; tick Reconcile the bank account only if the treasurer does the reconciliation, and when the treasurer also keeps the books there is no second reader.",
    aliases: ["volunteer treasurer", "finance committee chair", "church treasurer"],
  },
  {
    id: "program-director",
    title: "Program Director",
    family: "nonprofit",
    entitlements: ["order_supplies", "approve_invoices", "view_reports_only"],
    description:
      "Plans and runs the organization's programs, supervises program staff, and manages the program budget and grant-funded costs.",
    note: "A program director buys program supplies and approves program bills against the budget or grant; tick Confirm receipt of goods / services if they also sign for the deliveries.",
    aliases: ["director of programs", "programs director", "program services director"],
  },
  {
    id: "volunteer-coordinator",
    title: "Volunteer / Program Coordinator",
    family: "nonprofit",
    entitlements: ["view_reports_only"],
    description: "Recruits and schedules volunteers and delivers the organization's programs.",
    note: "Program staff hold no money duty; they appear on the map for continuity.",
    aliases: [
      "volunteer coordinator",
      "volunteer manager",
      "outreach coordinator",
      "community coordinator",
      "program coordinator",
      "program assistant",
      "case worker",
      "case coordinator",
      "care coordinator",
      "social worker",
    ],
  },
  {
    id: "board-member",
    title: "Board Member / Trustee",
    family: "nonprofit",
    entitlements: ["view_reports_only"],
    description:
      "Serves on the governing board of a nonprofit or association, approving budgets and policies and reading financial reports.",
    note: "A board member approves budgets and reads reports. If a board member also signs, reconciles or approves payroll, give that person the Board Treasurer title instead.",
    aliases: [
      "board member",
      "trustee",
      "board director",
      "board chair",
      "board president",
      "board secretary",
      "board vice chair",
    ],
  },
  {
    id: "church-administrator",
    title: "Church Administrator",
    family: "nonprofit",
    entitlements: [
      "post_payments",
      "prepare_deposit",
      "enter_invoices",
      "release_payment",
      "enter_payroll",
      "hold_company_card",
      "view_reports_only",
    ],
    description:
      "Runs a congregation's office and finances: records offerings and gifts, makes the deposit, pays the bills, and runs payroll.",
    note: "A church administrator records the offering, makes the deposit, pays the bills and runs payroll: the office manager's seat in a congregation. Untick what the treasurer or a counting team does; the offering count and the bank statement need someone else.",
    aliases: [
      "church business administrator",
      "church business manager",
      "parish administrator",
      "church office manager",
      "church secretary",
    ],
  },
  {
    id: "pastor",
    title: "Pastor / Minister",
    family: "nonprofit",
    entitlements: ["view_reports_only"],
    description:
      "Leads a congregation's worship, teaching, and pastoral care and oversees its staff.",
    note: "A pastor usually holds no money duty; tick Approve expense claims and card spending if they approve benevolence or discretionary-fund spending, and Sign / release checks if they sign.",
    aliases: [
      "pastor",
      "senior pastor",
      "lead pastor",
      "associate pastor",
      "minister",
      "priest",
      "rector",
      "rabbi",
      "imam",
      "clergy",
    ],
  },
  // Marketing and communications
  {
    id: "marketing",
    title: "Marketing Manager / Director",
    family: "marketing",
    soc: "11-2021",
    entitlements: ["order_supplies", "hold_company_card", "view_reports_only"],
    description:
      "Plans and runs marketing and communications, manages agencies and ad spend, and maintains the brand.",
    note: "Marketing buys agency, print, and ad-platform services, usually on a company card the owner never itemizes; entering and paying the bills belong to the office.",
    aliases: [
      "marketing manager",
      "marketing director",
      "director of marketing",
      "marketing",
      "social media manager",
      "content manager",
      "communications manager",
      "communications director",
      "digital marketing manager",
      "brand manager",
      "cmo",
      "chief marketing officer",
      "public relations",
      "pr manager",
      "community manager social media",
      "social media community manager",
      "online community manager",
      "community engagement manager",
    ],
  },
  {
    id: "marketing-coordinator",
    title: "Marketing Coordinator / Specialist",
    family: "marketing",
    soc: "13-1161",
    entitlements: ["view_reports_only"],
    description:
      "Coordinates campaigns, content, social media, and events under a marketing manager or the owner.",
    note: "A marketing coordinator runs campaigns and content; buying the ads and paying for them sit with a manager or the office unless you tick them.",
    aliases: [
      "marketing coordinator",
      "marketing specialist",
      "marketing associate",
      "marketing assistant",
      "social media coordinator",
      "communications coordinator",
    ],
  },
  // Education and childcare
  {
    id: "center-director",
    title: "Center / School Director",
    family: "education",
    entitlements: [
      "collect_cash",
      "prepare_deposit",
      "approve_vendor",
      "enter_payroll",
      "hold_company_card",
      "manage_user_access",
      "view_reports_only",
    ],
    description:
      "Directs a childcare center or school: enrollment, tuition, staffing, suppliers, and compliance.",
    note: "A director takes tuition, makes the deposit, approves suppliers, buys supplies on the center's card, and signs off hours, usually with no one above them on site. Enter payroll starts ticked: in a business this size the manager who signs off the hours usually keys them in. Untick it if the office or a payroll service enters the run.",
    aliases: [
      "center director",
      "childcare director",
      "daycare director",
      "preschool director",
      "school director",
      "head of school",
      "academy director",
      "site director",
      "school principal",
      "assistant principal",
    ],
  },
  {
    id: "assistant-director",
    title: "Assistant Center Director",
    family: "education",
    entitlements: ["collect_cash", "post_payments", "view_reports_only"],
    description:
      "Assists the center director with enrollment, family accounts, and tuition payments, and runs the front office.",
    note: "An assistant director takes tuition payments at the front desk and records them on families' accounts; the deposit and supplier approvals stay with the director unless you tick them.",
    aliases: [
      "assistant director",
      "assistant childcare director",
      "assistant daycare director",
      "assistant preschool director",
    ],
  },
  {
    id: "teacher",
    title: "Teacher / Caregiver",
    family: "education",
    entitlements: ["view_reports_only"],
    description: "Teaches or cares for children or students and holds no money duty.",
    note: "Teaching staff hold no money duty; they appear on the map for continuity.",
    aliases: [
      "teacher",
      "special education teacher",
      "special ed teacher",
      "education technician",
      "ed tech",
      "ed assistant",
      "paraeducator",
      "lead teacher",
      "assistant teacher",
      "teacher assistant",
      "teacher aide",
      "tutor",
      "childcare worker",
      "caregiver",
      "aide",
      "educator",
      "paraprofessional",
      "floater",
      "floating teacher",
      "school age lead",
      "school age teacher",
    ],
  },
  {
    id: "transport-driver",
    title: "Bus / Van Driver",
    family: "education",
    soc: "53-3051",
    entitlements: ["view_reports_only"],
    description: "Drives a bus or van carrying children, clients, or staff; holds no money duty.",
    note: "A bus or van driver carries children, clients or staff and collects nothing; tick Take payment from customers if they collect fares.",
    aliases: [
      "bus driver",
      "school bus driver",
      "van driver",
      "shuttle driver",
      "transportation driver",
    ],
  },
];

/**
 * A bare title that means one seat in one line of business: "Associate" is
 * an attorney in a law firm and a sales associate in a store; "Assistant" is
 * a dental assistant in a dental office; a "Crew Lead" runs a field crew in a
 * general or trades business and a shift in a store or restaurant; a
 * "Business Assistant" is the front desk of a dental office. Anywhere else
 * the catalog's own reading stands (or, for a level word, nothing).
 */
export const INDUSTRY_HINTS: Record<string, Record<string, string>> = {
  associate: { professional_services: "attorney", retail: "cashier", restaurant: "server" },
  assistant: { dental: "dental-assistant" },
  technician: { dental: "dental-assistant" },
  partner: { professional_services: "owner" },
  "crew lead": {
    general: "foreman",
    construction: "foreman",
    retail: "shift-lead",
    restaurant: "shift-lead",
  },
  "crew leader": {
    general: "foreman",
    construction: "foreman",
    retail: "shift-lead",
    restaurant: "shift-lead",
  },
  // A team lead takes the drawer only in a store or a restaurant.
  "team lead": { retail: "shift-lead", restaurant: "shift-lead" },
  "team leader": { retail: "shift-lead", restaurant: "shift-lead" },
  // On a job site a "super" is the superintendent.
  super: { construction: "foreman" },
  // A nonprofit's treasurer is a board officer, its CEO or president is its
  // executive director, and its principal runs a school.
  treasurer: { nonprofit: "board-treasurer" },
  ceo: { nonprofit: "executive-director" },
  "chief executive officer": { nonprofit: "executive-director" },
  "chief executive": { nonprofit: "executive-director" },
  president: { nonprofit: "executive-director" },
  principal: { nonprofit: "center-director" },
  // A nonprofit's program manager runs a program, not a client project.
  "program manager": { nonprofit: "program-director" },
  "business assistant": { dental: "receptionist" },
  // A CSR in a dental, medical or veterinary office is the front desk.
  csr: { dental: "receptionist" },
  "customer service representative": { dental: "receptionist" },
  // In a dental, medical or veterinary office the practice administrator or
  // business manager keeps the books like the office manager, the business
  // office runs the billing, the care coordinator takes payment for the plan,
  // and the registrar registers patients at the desk. A law firm's practice
  // administrator is its firm administrator.
  "practice administrator": {
    dental: "office-manager",
    professional_services: "firm-administrator",
  },
  "business manager": { dental: "office-manager" },
  "business office manager": { dental: "billing-manager" },
  "care coordinator": { dental: "treatment-coordinator" },
  "case coordinator": { dental: "treatment-coordinator" },
  registrar: { dental: "medical-secretary" },
  // A restaurant's general manager runs the floor and the drawer as well as the books.
  "general manager": { restaurant: "restaurant-manager" },
  gm: { restaurant: "restaurant-manager" },
  // A community manager keeps a property in a general business and a
  // following everywhere else.
  "community manager": {
    general: "property-manager",
    nonprofit: "marketing",
    professional_services: "marketing",
    retail: "marketing",
    restaurant: "marketing",
  },
  // A restaurant's event planner sells and runs its catered events.
  "event planner": { restaurant: "catering-manager" },
};

/**
 * How a seat differs in one line of business from its usual duties. In a
 * dental, medical or veterinary office the office manager usually keeps the
 * practice's books, bank reconciliation included. In a store the till records
 * the sales, so the bookkeeper posts the takings as a journal entry rather
 * than recording customer payments. In a law or accounting firm the front
 * desk takes payments and billing records them. A contractor's project
 * manager approves subcontractor bills; a nonprofit's development office
 * records the gifts it receives.
 */
export const INDUSTRY_SEATS: Record<
  string,
  Record<string, { add?: readonly EntitlementId[]; remove?: readonly EntitlementId[] }>
> = {
  dental: { "office-manager": { add: ["bank_reconcile"] } },
  retail: { bookkeeper: { remove: ["post_payments"] } },
  professional_services: { receptionist: { remove: ["post_payments"] } },
  // A contractor's project manager approves subcontractor pay applications
  // and orders materials for the job.
  construction: { "project-manager": { add: ["approve_invoices", "order_supplies"] } },
  // Development enters the gifts it receives in the donor database.
  nonprofit: { "development-director": { add: ["post_payments"] } },
};

const BY_ID = new Map(JOB_CATALOG.map((e) => [e.id, e]));
