/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FirmRouteImport } from './routes/firm'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ReportRouteImport } from './routes/report'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ThreatRouteImport } from './routes/threat'
import { Route as ApiErrorsRouteImport } from './routes/api/errors'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as JoinTokenRouteImport } from './routes/join.$token'
import { Route as ShareTokenRouteImport } from './routes/share.$token'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiCronDigestRouteImport } from './routes/api/cron/digest'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe/webhook'
import { Route as ApiIntegrationsQboCallbackRouteImport } from './routes/api/integrations/qbo/callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FirmRoute = FirmRouteImport.update({
  id: '/firm',
  path: '/firm',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ThreatRoute = ThreatRouteImport.update({
  id: '/threat',
  path: '/threat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiErrorsRoute = ApiErrorsRouteImport.update({
  id: '/api/errors',
  path: '/api/errors',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinTokenRoute = JoinTokenRouteImport.update({
  id: '/join/$token',
  path: '/join/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareTokenRoute = ShareTokenRouteImport.update({
  id: '/share/$token',
  path: '/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronDigestRoute = ApiCronDigestRouteImport.update({
  id: '/api/cron/digest',
  path: '/api/cron/digest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIntegrationsQboCallbackRoute =
  ApiIntegrationsQboCallbackRouteImport.update({
    id: '/api/integrations/qbo/callback',
    path: '/api/integrations/qbo/callback',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/firm': typeof FirmRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/report': typeof ReportRoute
  '/terms': typeof TermsRoute
  '/threat': typeof ThreatRoute
  '/api/errors': typeof ApiErrorsRoute
  '/api/health': typeof ApiHealthRoute
  '/join/$token': typeof JoinTokenRoute
  '/share/$token': typeof ShareTokenRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/digest': typeof ApiCronDigestRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/integrations/qbo/callback': typeof ApiIntegrationsQboCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/firm': typeof FirmRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/report': typeof ReportRoute
  '/terms': typeof TermsRoute
  '/threat': typeof ThreatRoute
  '/api/errors': typeof ApiErrorsRoute
  '/api/health': typeof ApiHealthRoute
  '/join/$token': typeof JoinTokenRoute
  '/share/$token': typeof ShareTokenRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/digest': typeof ApiCronDigestRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/integrations/qbo/callback': typeof ApiIntegrationsQboCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/firm': typeof FirmRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/report': typeof ReportRoute
  '/terms': typeof TermsRoute
  '/threat': typeof ThreatRoute
  '/api/errors': typeof ApiErrorsRoute
  '/api/health': typeof ApiHealthRoute
  '/join/$token': typeof JoinTokenRoute
  '/share/$token': typeof ShareTokenRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/digest': typeof ApiCronDigestRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/integrations/qbo/callback': typeof ApiIntegrationsQboCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/firm'
    | '/login'
    | '/privacy'
    | '/report'
    | '/terms'
    | '/threat'
    | '/api/errors'
    | '/api/health'
    | '/join/$token'
    | '/share/$token'
    | '/api/auth/$'
    | '/api/cron/digest'
    | '/api/stripe/webhook'
    | '/api/integrations/qbo/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/firm'
    | '/login'
    | '/privacy'
    | '/report'
    | '/terms'
    | '/threat'
    | '/api/errors'
    | '/api/health'
    | '/join/$token'
    | '/share/$token'
    | '/api/auth/$'
    | '/api/cron/digest'
    | '/api/stripe/webhook'
    | '/api/integrations/qbo/callback'
  id:
    | '__root__'
    | '/'
    | '/firm'
    | '/login'
    | '/privacy'
    | '/report'
    | '/terms'
    | '/threat'
    | '/api/errors'
    | '/api/health'
    | '/join/$token'
    | '/share/$token'
    | '/api/auth/$'
    | '/api/cron/digest'
    | '/api/stripe/webhook'
    | '/api/integrations/qbo/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FirmRoute: typeof FirmRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  ReportRoute: typeof ReportRoute
  TermsRoute: typeof TermsRoute
  ThreatRoute: typeof ThreatRoute
  ApiErrorsRoute: typeof ApiErrorsRoute
  ApiHealthRoute: typeof ApiHealthRoute
  JoinTokenRoute: typeof JoinTokenRoute
  ShareTokenRoute: typeof ShareTokenRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCronDigestRoute: typeof ApiCronDigestRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
  ApiIntegrationsQboCallbackRoute: typeof ApiIntegrationsQboCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/firm': {
      id: '/firm'
      path: '/firm'
      fullPath: '/firm'
      preLoaderRoute: typeof FirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/threat': {
      id: '/threat'
      path: '/threat'
      fullPath: '/threat'
      preLoaderRoute: typeof ThreatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/errors': {
      id: '/api/errors'
      path: '/api/errors'
      fullPath: '/api/errors'
      preLoaderRoute: typeof ApiErrorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$token': {
      id: '/join/$token'
      path: '/join/$token'
      fullPath: '/join/$token'
      preLoaderRoute: typeof JoinTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$token': {
      id: '/share/$token'
      path: '/share/$token'
      fullPath: '/share/$token'
      preLoaderRoute: typeof ShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/digest': {
      id: '/api/cron/digest'
      path: '/api/cron/digest'
      fullPath: '/api/cron/digest'
      preLoaderRoute: typeof ApiCronDigestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/qbo/callback': {
      id: '/api/integrations/qbo/callback'
      path: '/api/integrations/qbo/callback'
      fullPath: '/api/integrations/qbo/callback'
      preLoaderRoute: typeof ApiIntegrationsQboCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FirmRoute: FirmRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  ReportRoute: ReportRoute,
  TermsRoute: TermsRoute,
  ThreatRoute: ThreatRoute,
  ApiErrorsRoute: ApiErrorsRoute,
  ApiHealthRoute: ApiHealthRoute,
  JoinTokenRoute: JoinTokenRoute,
  ShareTokenRoute: ShareTokenRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCronDigestRoute: ApiCronDigestRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
  ApiIntegrationsQboCallbackRoute: ApiIntegrationsQboCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
