/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as ReportRouteImport } from './routes/report'
import { Route as ThreatRouteImport } from './routes/threat'
import { Route as CheckinTokenRouteImport } from './routes/checkin.$token'
import { Route as ShareTokenRouteImport } from './routes/share.$token'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const ThreatRoute = ThreatRouteImport.update({
  id: '/threat',
  path: '/threat',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckinTokenRoute = CheckinTokenRouteImport.update({
  id: '/checkin/$token',
  path: '/checkin/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareTokenRoute = ShareTokenRouteImport.update({
  id: '/share/$token',
  path: '/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/portfolio': typeof PortfolioRoute
  '/report': typeof ReportRoute
  '/threat': typeof ThreatRoute
  '/checkin/$token': typeof CheckinTokenRoute
  '/share/$token': typeof ShareTokenRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/portfolio': typeof PortfolioRoute
  '/report': typeof ReportRoute
  '/threat': typeof ThreatRoute
  '/checkin/$token': typeof CheckinTokenRoute
  '/share/$token': typeof ShareTokenRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/portfolio': typeof PortfolioRoute
  '/report': typeof ReportRoute
  '/threat': typeof ThreatRoute
  '/checkin/$token': typeof CheckinTokenRoute
  '/share/$token': typeof ShareTokenRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/portfolio'
    | '/report'
    | '/threat'
    | '/checkin/$token'
    | '/share/$token'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/portfolio'
    | '/report'
    | '/threat'
    | '/checkin/$token'
    | '/share/$token'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/portfolio'
    | '/report'
    | '/threat'
    | '/checkin/$token'
    | '/share/$token'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  PortfolioRoute: typeof PortfolioRoute
  ReportRoute: typeof ReportRoute
  ThreatRoute: typeof ThreatRoute
  CheckinTokenRoute: typeof CheckinTokenRoute
  ShareTokenRoute: typeof ShareTokenRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/threat': {
      id: '/threat'
      path: '/threat'
      fullPath: '/threat'
      preLoaderRoute: typeof ThreatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkin/$token': {
      id: '/checkin/$token'
      path: '/checkin/$token'
      fullPath: '/checkin/$token'
      preLoaderRoute: typeof CheckinTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$token': {
      id: '/share/$token'
      path: '/share/$token'
      fullPath: '/share/$token'
      preLoaderRoute: typeof ShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  PortfolioRoute: PortfolioRoute,
  ReportRoute: ReportRoute,
  ThreatRoute: ThreatRoute,
  CheckinTokenRoute: CheckinTokenRoute,
  ShareTokenRoute: ShareTokenRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
