/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FirmRouteImport } from './routes/firm'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OperatorRouteImport } from './routes/operator'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ReportRouteImport } from './routes/report'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ThreatRouteImport } from './routes/threat'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as ApiDigestEmailRouteImport } from './routes/api/digest-email'
import { Route as ApiErrorsRouteImport } from './routes/api/errors'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiOwnerEmailRouteImport } from './routes/api/owner-email'
import { Route as ApiProcedureImageRouteImport } from './routes/api/procedure-image'
import { Route as JoinTokenRouteImport } from './routes/join.$token'
import { Route as ShareTokenRouteImport } from './routes/share.$token'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiCronDigestRouteImport } from './routes/api/cron/digest'
import { Route as ApiResendWebhookRouteImport } from './routes/api/resend/webhook'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe/webhook'
import { Route as JoinClientTokenRouteImport } from './routes/join/client/$token'
import { Route as ShareReportTokenRouteImport } from './routes/share.report.$token'
import { Route as ApiIntegrationsQboCallbackRouteImport } from './routes/api/integrations/qbo/callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FirmRoute = FirmRouteImport.update({
  id: '/firm',
  path: '/firm',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorRoute = OperatorRouteImport.update({
  id: '/operator',
  path: '/operator',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ThreatRoute = ThreatRouteImport.update({
  id: '/threat',
  path: '/threat',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDigestEmailRoute = ApiDigestEmailRouteImport.update({
  id: '/api/digest-email',
  path: '/api/digest-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiErrorsRoute = ApiErrorsRouteImport.update({
  id: '/api/errors',
  path: '/api/errors',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOwnerEmailRoute = ApiOwnerEmailRouteImport.update({
  id: '/api/owner-email',
  path: '/api/owner-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProcedureImageRoute = ApiProcedureImageRouteImport.update({
  id: '/api/procedure-image',
  path: '/api/procedure-image',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinTokenRoute = JoinTokenRouteImport.update({
  id: '/join/$token',
  path: '/join/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareTokenRoute = ShareTokenRouteImport.update({
  id: '/share/$token',
  path: '/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronDigestRoute = ApiCronDigestRouteImport.update({
  id: '/api/cron/digest',
  path: '/api/cron/digest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiResendWebhookRoute = ApiResendWebhookRouteImport.update({
  id: '/api/resend/webhook',
  path: '/api/resend/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinClientTokenRoute = JoinClientTokenRouteImport.update({
  id: '/join/client/$token',
  path: '/join/client/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareReportTokenRoute = ShareReportTokenRouteImport.update({
  id: '/share/report/$token',
  path: '/share/report/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIntegrationsQboCallbackRoute =
  ApiIntegrationsQboCallbackRouteImport.update({
    id: '/api/integrations/qbo/callback',
    path: '/api/integrations/qbo/callback',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/firm': typeof FirmRoute
  '/login': typeof LoginRoute
  '/operator': typeof OperatorRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/report': typeof ReportRoute
  '/terms': typeof TermsRoute
  '/threat': typeof ThreatRoute
  '/welcome': typeof WelcomeRoute
  '/api/digest-email': typeof ApiDigestEmailRoute
  '/api/errors': typeof ApiErrorsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/owner-email': typeof ApiOwnerEmailRoute
  '/api/procedure-image': typeof ApiProcedureImageRoute
  '/join/$token': typeof JoinTokenRoute
  '/share/$token': typeof ShareTokenRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/digest': typeof ApiCronDigestRoute
  '/api/resend/webhook': typeof ApiResendWebhookRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/join/client/$token': typeof JoinClientTokenRoute
  '/share/report/$token': typeof ShareReportTokenRoute
  '/api/integrations/qbo/callback': typeof ApiIntegrationsQboCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/firm': typeof FirmRoute
  '/login': typeof LoginRoute
  '/operator': typeof OperatorRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/report': typeof ReportRoute
  '/terms': typeof TermsRoute
  '/threat': typeof ThreatRoute
  '/welcome': typeof WelcomeRoute
  '/api/digest-email': typeof ApiDigestEmailRoute
  '/api/errors': typeof ApiErrorsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/owner-email': typeof ApiOwnerEmailRoute
  '/api/procedure-image': typeof ApiProcedureImageRoute
  '/join/$token': typeof JoinTokenRoute
  '/share/$token': typeof ShareTokenRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/digest': typeof ApiCronDigestRoute
  '/api/resend/webhook': typeof ApiResendWebhookRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/join/client/$token': typeof JoinClientTokenRoute
  '/share/report/$token': typeof ShareReportTokenRoute
  '/api/integrations/qbo/callback': typeof ApiIntegrationsQboCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/firm': typeof FirmRoute
  '/login': typeof LoginRoute
  '/operator': typeof OperatorRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/report': typeof ReportRoute
  '/terms': typeof TermsRoute
  '/threat': typeof ThreatRoute
  '/welcome': typeof WelcomeRoute
  '/api/digest-email': typeof ApiDigestEmailRoute
  '/api/errors': typeof ApiErrorsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/owner-email': typeof ApiOwnerEmailRoute
  '/api/procedure-image': typeof ApiProcedureImageRoute
  '/join/$token': typeof JoinTokenRoute
  '/share/$token': typeof ShareTokenRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/digest': typeof ApiCronDigestRoute
  '/api/resend/webhook': typeof ApiResendWebhookRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/join/client/$token': typeof JoinClientTokenRoute
  '/share/report/$token': typeof ShareReportTokenRoute
  '/api/integrations/qbo/callback': typeof ApiIntegrationsQboCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/firm'
    | '/login'
    | '/operator'
    | '/pricing'
    | '/privacy'
    | '/report'
    | '/terms'
    | '/threat'
    | '/welcome'
    | '/api/digest-email'
    | '/api/errors'
    | '/api/health'
    | '/api/owner-email'
    | '/api/procedure-image'
    | '/join/$token'
    | '/share/$token'
    | '/api/auth/$'
    | '/api/cron/digest'
    | '/api/resend/webhook'
    | '/api/stripe/webhook'
    | '/join/client/$token'
    | '/share/report/$token'
    | '/api/integrations/qbo/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/firm'
    | '/login'
    | '/operator'
    | '/pricing'
    | '/privacy'
    | '/report'
    | '/terms'
    | '/threat'
    | '/welcome'
    | '/api/digest-email'
    | '/api/errors'
    | '/api/health'
    | '/api/owner-email'
    | '/api/procedure-image'
    | '/join/$token'
    | '/share/$token'
    | '/api/auth/$'
    | '/api/cron/digest'
    | '/api/resend/webhook'
    | '/api/stripe/webhook'
    | '/join/client/$token'
    | '/share/report/$token'
    | '/api/integrations/qbo/callback'
  id:
    | '__root__'
    | '/'
    | '/firm'
    | '/login'
    | '/operator'
    | '/pricing'
    | '/privacy'
    | '/report'
    | '/terms'
    | '/threat'
    | '/welcome'
    | '/api/digest-email'
    | '/api/errors'
    | '/api/health'
    | '/api/owner-email'
    | '/api/procedure-image'
    | '/join/$token'
    | '/share/$token'
    | '/api/auth/$'
    | '/api/cron/digest'
    | '/api/resend/webhook'
    | '/api/stripe/webhook'
    | '/join/client/$token'
    | '/share/report/$token'
    | '/api/integrations/qbo/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FirmRoute: typeof FirmRoute
  LoginRoute: typeof LoginRoute
  OperatorRoute: typeof OperatorRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ReportRoute: typeof ReportRoute
  TermsRoute: typeof TermsRoute
  ThreatRoute: typeof ThreatRoute
  WelcomeRoute: typeof WelcomeRoute
  ApiDigestEmailRoute: typeof ApiDigestEmailRoute
  ApiErrorsRoute: typeof ApiErrorsRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiOwnerEmailRoute: typeof ApiOwnerEmailRoute
  ApiProcedureImageRoute: typeof ApiProcedureImageRoute
  JoinTokenRoute: typeof JoinTokenRoute
  ShareTokenRoute: typeof ShareTokenRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCronDigestRoute: typeof ApiCronDigestRoute
  ApiResendWebhookRoute: typeof ApiResendWebhookRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
  JoinClientTokenRoute: typeof JoinClientTokenRoute
  ShareReportTokenRoute: typeof ShareReportTokenRoute
  ApiIntegrationsQboCallbackRoute: typeof ApiIntegrationsQboCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/firm': {
      id: '/firm'
      path: '/firm'
      fullPath: '/firm'
      preLoaderRoute: typeof FirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operator': {
      id: '/operator'
      path: '/operator'
      fullPath: '/operator'
      preLoaderRoute: typeof OperatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/threat': {
      id: '/threat'
      path: '/threat'
      fullPath: '/threat'
      preLoaderRoute: typeof ThreatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/digest-email': {
      id: '/api/digest-email'
      path: '/api/digest-email'
      fullPath: '/api/digest-email'
      preLoaderRoute: typeof ApiDigestEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/errors': {
      id: '/api/errors'
      path: '/api/errors'
      fullPath: '/api/errors'
      preLoaderRoute: typeof ApiErrorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/owner-email': {
      id: '/api/owner-email'
      path: '/api/owner-email'
      fullPath: '/api/owner-email'
      preLoaderRoute: typeof ApiOwnerEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/procedure-image': {
      id: '/api/procedure-image'
      path: '/api/procedure-image'
      fullPath: '/api/procedure-image'
      preLoaderRoute: typeof ApiProcedureImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$token': {
      id: '/join/$token'
      path: '/join/$token'
      fullPath: '/join/$token'
      preLoaderRoute: typeof JoinTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$token': {
      id: '/share/$token'
      path: '/share/$token'
      fullPath: '/share/$token'
      preLoaderRoute: typeof ShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/digest': {
      id: '/api/cron/digest'
      path: '/api/cron/digest'
      fullPath: '/api/cron/digest'
      preLoaderRoute: typeof ApiCronDigestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/resend/webhook': {
      id: '/api/resend/webhook'
      path: '/api/resend/webhook'
      fullPath: '/api/resend/webhook'
      preLoaderRoute: typeof ApiResendWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/client/$token': {
      id: '/join/client/$token'
      path: '/join/client/$token'
      fullPath: '/join/client/$token'
      preLoaderRoute: typeof JoinClientTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/report/$token': {
      id: '/share/report/$token'
      path: '/share/report/$token'
      fullPath: '/share/report/$token'
      preLoaderRoute: typeof ShareReportTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/qbo/callback': {
      id: '/api/integrations/qbo/callback'
      path: '/api/integrations/qbo/callback'
      fullPath: '/api/integrations/qbo/callback'
      preLoaderRoute: typeof ApiIntegrationsQboCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FirmRoute: FirmRoute,
  LoginRoute: LoginRoute,
  OperatorRoute: OperatorRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ReportRoute: ReportRoute,
  TermsRoute: TermsRoute,
  ThreatRoute: ThreatRoute,
  WelcomeRoute: WelcomeRoute,
  ApiDigestEmailRoute: ApiDigestEmailRoute,
  ApiErrorsRoute: ApiErrorsRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiOwnerEmailRoute: ApiOwnerEmailRoute,
  ApiProcedureImageRoute: ApiProcedureImageRoute,
  JoinTokenRoute: JoinTokenRoute,
  ShareTokenRoute: ShareTokenRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCronDigestRoute: ApiCronDigestRoute,
  ApiResendWebhookRoute: ApiResendWebhookRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
  JoinClientTokenRoute: JoinClientTokenRoute,
  ShareReportTokenRoute: ShareReportTokenRoute,
  ApiIntegrationsQboCallbackRoute: ApiIntegrationsQboCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
